// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/13       [393741]
Creator        : leure
Date           : Tue Jun  6 18:41:16 2017
Host           : Linux vocms029.cern.ch 2.6.32-504.12.2.el6.x86_64 #1 SMP Thu Mar 12 07:33:00 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /data/leure/TMVA_Luke/myTMVA
Training events: 576
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                                                         'F'    [0.511792123318,13.9487380981]
DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                                                      'F'    [0.950958848,20.4582691193]
DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                                                      'F'    [0.541395664215,19.5425701141]
DtktkRespt                    DtktkRespt                    DtktkRespt                    DtktkRespt                                                      'F'    [8.03139591217,21.8248806]
Dchi2cl                       Dchi2cl                       Dchi2cl                       Dchi2cl                                                         'F'    [0.0501248650253,0.999834001064]
DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl                                                 'F'    [0.0509073212743,0.99915009737]
Dalpha                        Dalpha                        Dalpha                        Dalpha                                                          'F'    [0.000363119848771,0.19725073874]
DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                                                  'F'    [0.000838859472424,0.199973419309]
DsvpvDistance/DsvpvDisErr     DsvpvDistance_D_DsvpvDisErr   DsvpvDistance/DsvpvDisErr     DsvpvDistance/DsvpvDisErr                                       'F'    [2.00301671028,633.239868164]
DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance_D_DtktkRes_svpvDisErr DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance/DtktkRes_svpvDisErr                                                   'F'    [2.03857517242,100.371292114]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Dtrk1Pt", "DRestrk1Pt", "DRestrk2Pt", "DtktkRespt", "Dchi2cl", "DtktkRes_chi2cl", "Dalpha", "DtktkRes_alpha", "DsvpvDistance/DsvpvDisErr", "DtktkRes_svpvDistance/DtktkRes_svpvDisErr" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][10];
   double fMax_1[3][10];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[16][11];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][16];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 11; fWeights[0] = new double[11]; 
   fLayerSize[1] = 16; fWeights[1] = new double[16]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -1.88299367741026;
   fWeightMatrix0to1[1][0] = 1.16251537834873;
   fWeightMatrix0to1[2][0] = 2.54167706522716;
   fWeightMatrix0to1[3][0] = 2.43670157461424;
   fWeightMatrix0to1[4][0] = -2.39634989077117;
   fWeightMatrix0to1[5][0] = -3.15052766282258;
   fWeightMatrix0to1[6][0] = 1.07328324873859;
   fWeightMatrix0to1[7][0] = 0.726351151918584;
   fWeightMatrix0to1[8][0] = 0.385688014194758;
   fWeightMatrix0to1[9][0] = -2.89861530697746;
   fWeightMatrix0to1[10][0] = -0.717987958591457;
   fWeightMatrix0to1[11][0] = -3.75861632837427;
   fWeightMatrix0to1[12][0] = -0.589040310738401;
   fWeightMatrix0to1[13][0] = 2.06031979347058;
   fWeightMatrix0to1[14][0] = 0.0792547332589588;
   fWeightMatrix0to1[0][1] = 0.322465196839916;
   fWeightMatrix0to1[1][1] = -0.932875219347569;
   fWeightMatrix0to1[2][1] = 1.41388341389604;
   fWeightMatrix0to1[3][1] = -1.54795428885159;
   fWeightMatrix0to1[4][1] = -0.147327495624105;
   fWeightMatrix0to1[5][1] = 1.11902661387431;
   fWeightMatrix0to1[6][1] = -5.1127690613393;
   fWeightMatrix0to1[7][1] = 0.99296573909566;
   fWeightMatrix0to1[8][1] = -4.25714174677737;
   fWeightMatrix0to1[9][1] = 2.78158128754539;
   fWeightMatrix0to1[10][1] = 1.11531836330804;
   fWeightMatrix0to1[11][1] = 2.52709432403041;
   fWeightMatrix0to1[12][1] = -0.478238946396988;
   fWeightMatrix0to1[13][1] = -5.82756977537528;
   fWeightMatrix0to1[14][1] = -1.2116654055922;
   fWeightMatrix0to1[0][2] = -1.10467075409835;
   fWeightMatrix0to1[1][2] = 0.612594513630146;
   fWeightMatrix0to1[2][2] = 1.02756381054381;
   fWeightMatrix0to1[3][2] = -0.816802703740651;
   fWeightMatrix0to1[4][2] = -0.078784091822667;
   fWeightMatrix0to1[5][2] = 0.584933732359146;
   fWeightMatrix0to1[6][2] = -1.60966953880036;
   fWeightMatrix0to1[7][2] = 1.16310446837126;
   fWeightMatrix0to1[8][2] = -1.36937602454781;
   fWeightMatrix0to1[9][2] = 0.298124389714195;
   fWeightMatrix0to1[10][2] = 2.91403570288289;
   fWeightMatrix0to1[11][2] = -1.26992654399849;
   fWeightMatrix0to1[12][2] = 3.38545568725836;
   fWeightMatrix0to1[13][2] = 1.5100540400987;
   fWeightMatrix0to1[14][2] = -1.30758987916278;
   fWeightMatrix0to1[0][3] = -0.481995145841089;
   fWeightMatrix0to1[1][3] = 1.03927979043607;
   fWeightMatrix0to1[2][3] = -1.06873093332528;
   fWeightMatrix0to1[3][3] = 0.935133128633942;
   fWeightMatrix0to1[4][3] = 1.43841730531685;
   fWeightMatrix0to1[5][3] = 3.39500768211177;
   fWeightMatrix0to1[6][3] = -1.29971782112588;
   fWeightMatrix0to1[7][3] = -0.617368320933924;
   fWeightMatrix0to1[8][3] = -1.24710570882383;
   fWeightMatrix0to1[9][3] = -0.346263473733591;
   fWeightMatrix0to1[10][3] = -0.966014283078915;
   fWeightMatrix0to1[11][3] = 1.1451806162565;
   fWeightMatrix0to1[12][3] = -2.32816329130706;
   fWeightMatrix0to1[13][3] = -0.629419173384153;
   fWeightMatrix0to1[14][3] = -0.343395350521338;
   fWeightMatrix0to1[0][4] = -2.79624182481923;
   fWeightMatrix0to1[1][4] = 0.949247001321058;
   fWeightMatrix0to1[2][4] = -1.65512135381826;
   fWeightMatrix0to1[3][4] = 1.3657154148519;
   fWeightMatrix0to1[4][4] = 1.86396135378821;
   fWeightMatrix0to1[5][4] = -1.16058082604706;
   fWeightMatrix0to1[6][4] = -1.10422338965447;
   fWeightMatrix0to1[7][4] = -0.397987858877877;
   fWeightMatrix0to1[8][4] = -0.691661793743677;
   fWeightMatrix0to1[9][4] = -0.995865607921191;
   fWeightMatrix0to1[10][4] = 0.736616973665036;
   fWeightMatrix0to1[11][4] = 0.307691322196917;
   fWeightMatrix0to1[12][4] = -1.43853939789187;
   fWeightMatrix0to1[13][4] = 5.85318321683092;
   fWeightMatrix0to1[14][4] = 2.80012529191274;
   fWeightMatrix0to1[0][5] = -1.26690566683512;
   fWeightMatrix0to1[1][5] = -1.84580863169183;
   fWeightMatrix0to1[2][5] = -1.16816111979451;
   fWeightMatrix0to1[3][5] = 0.679152175549145;
   fWeightMatrix0to1[4][5] = 0.515589214124702;
   fWeightMatrix0to1[5][5] = -0.52346613297083;
   fWeightMatrix0to1[6][5] = 3.54751301499285;
   fWeightMatrix0to1[7][5] = 0.131173175104944;
   fWeightMatrix0to1[8][5] = 1.97410522383346;
   fWeightMatrix0to1[9][5] = -6.28898522144374;
   fWeightMatrix0to1[10][5] = 0.112359510455376;
   fWeightMatrix0to1[11][5] = -0.876434099152219;
   fWeightMatrix0to1[12][5] = -0.432051369314577;
   fWeightMatrix0to1[13][5] = 1.43857950532304;
   fWeightMatrix0to1[14][5] = 0.314873107116426;
   fWeightMatrix0to1[0][6] = -4.07704698781839;
   fWeightMatrix0to1[1][6] = -0.728692957017167;
   fWeightMatrix0to1[2][6] = 3.64453478098668;
   fWeightMatrix0to1[3][6] = -1.55946514763059;
   fWeightMatrix0to1[4][6] = -1.98784753091929;
   fWeightMatrix0to1[5][6] = 4.00628134061069;
   fWeightMatrix0to1[6][6] = 1.93976421616064;
   fWeightMatrix0to1[7][6] = -1.32762542747504;
   fWeightMatrix0to1[8][6] = 1.5609656902071;
   fWeightMatrix0to1[9][6] = 6.08191161927422;
   fWeightMatrix0to1[10][6] = -0.253153553033869;
   fWeightMatrix0to1[11][6] = -4.38076842154783;
   fWeightMatrix0to1[12][6] = 4.78843166430988;
   fWeightMatrix0to1[13][6] = -3.43713895981558;
   fWeightMatrix0to1[14][6] = -1.51820054512547;
   fWeightMatrix0to1[0][7] = 0.21606652659267;
   fWeightMatrix0to1[1][7] = -1.73819671462673;
   fWeightMatrix0to1[2][7] = 0.0119494612314071;
   fWeightMatrix0to1[3][7] = -0.170954463452203;
   fWeightMatrix0to1[4][7] = 0.125701126093575;
   fWeightMatrix0to1[5][7] = -2.4656100699022;
   fWeightMatrix0to1[6][7] = -2.10699145992396;
   fWeightMatrix0to1[7][7] = -0.761408359501495;
   fWeightMatrix0to1[8][7] = -1.82858198719411;
   fWeightMatrix0to1[9][7] = -2.07784025128063;
   fWeightMatrix0to1[10][7] = 2.72330212111765;
   fWeightMatrix0to1[11][7] = -0.497432343314713;
   fWeightMatrix0to1[12][7] = -1.12538759117194;
   fWeightMatrix0to1[13][7] = 1.95018034114619;
   fWeightMatrix0to1[14][7] = -1.79808323937651;
   fWeightMatrix0to1[0][8] = -3.22470098316239;
   fWeightMatrix0to1[1][8] = -2.62638978770127;
   fWeightMatrix0to1[2][8] = 2.79058318601714;
   fWeightMatrix0to1[3][8] = -1.09711273955486;
   fWeightMatrix0to1[4][8] = -2.16155486652691;
   fWeightMatrix0to1[5][8] = 1.34955481283144;
   fWeightMatrix0to1[6][8] = -5.0229117244726;
   fWeightMatrix0to1[7][8] = -1.5629271258447;
   fWeightMatrix0to1[8][8] = -6.45954685395986;
   fWeightMatrix0to1[9][8] = 4.2169275174437;
   fWeightMatrix0to1[10][8] = 1.3060491329642;
   fWeightMatrix0to1[11][8] = -6.28168732847351;
   fWeightMatrix0to1[12][8] = 4.37058602800179;
   fWeightMatrix0to1[13][8] = -4.88490724712637;
   fWeightMatrix0to1[14][8] = -1.95658907495066;
   fWeightMatrix0to1[0][9] = -2.59601860816208;
   fWeightMatrix0to1[1][9] = 0.0673720359046318;
   fWeightMatrix0to1[2][9] = 0.256967440185608;
   fWeightMatrix0to1[3][9] = -0.583094748108299;
   fWeightMatrix0to1[4][9] = -0.882105931927809;
   fWeightMatrix0to1[5][9] = 1.74044317602124;
   fWeightMatrix0to1[6][9] = -3.3375671625387;
   fWeightMatrix0to1[7][9] = -2.39599482713023;
   fWeightMatrix0to1[8][9] = -4.25800998283686;
   fWeightMatrix0to1[9][9] = 1.82970192671635;
   fWeightMatrix0to1[10][9] = 4.40507500942798;
   fWeightMatrix0to1[11][9] = -1.26744656615871;
   fWeightMatrix0to1[12][9] = 2.20946820245295;
   fWeightMatrix0to1[13][9] = -4.2959118772943;
   fWeightMatrix0to1[14][9] = -1.05992601234288;
   fWeightMatrix0to1[0][10] = 3.55889804360896;
   fWeightMatrix0to1[1][10] = 3.54110354456242;
   fWeightMatrix0to1[2][10] = -1.32222673927764;
   fWeightMatrix0to1[3][10] = 2.67104228273133;
   fWeightMatrix0to1[4][10] = 2.46554777895888;
   fWeightMatrix0to1[5][10] = -1.36683011519683;
   fWeightMatrix0to1[6][10] = 5.56830697276202;
   fWeightMatrix0to1[7][10] = 2.3528908175408;
   fWeightMatrix0to1[8][10] = 5.49311370119332;
   fWeightMatrix0to1[9][10] = -4.99808200799416;
   fWeightMatrix0to1[10][10] = -3.61260695724676;
   fWeightMatrix0to1[11][10] = 5.50861077840861;
   fWeightMatrix0to1[12][10] = -3.72241796854407;
   fWeightMatrix0to1[13][10] = 4.16163184545221;
   fWeightMatrix0to1[14][10] = 2.97859974498579;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -4.49613008079587;
   fWeightMatrix1to2[0][1] = 3.01735718434369;
   fWeightMatrix1to2[0][2] = -1.42370224570343;
   fWeightMatrix1to2[0][3] = 2.52018569612572;
   fWeightMatrix1to2[0][4] = -1.86211855599789;
   fWeightMatrix1to2[0][5] = -0.368980132103571;
   fWeightMatrix1to2[0][6] = 3.66600831275032;
   fWeightMatrix1to2[0][7] = 0.632869823628423;
   fWeightMatrix1to2[0][8] = 3.96665651606174;
   fWeightMatrix1to2[0][9] = 0.377976518474414;
   fWeightMatrix1to2[0][10] = 5.45141642774366;
   fWeightMatrix1to2[0][11] = -7.09926659383928;
   fWeightMatrix1to2[0][12] = 4.6943180683179;
   fWeightMatrix1to2[0][13] = -0.633644720059927;
   fWeightMatrix1to2[0][14] = 5.35595577878887;
   fWeightMatrix1to2[0][15] = 4.66644105809581;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.553826928139;
   fMax_1[0][0] = 13.9487380981;
   fMin_1[1][0] = 0.511792123318;
   fMax_1[1][0] = 9.48964977264;
   fMin_1[2][0] = 0.511792123318;
   fMax_1[2][0] = 13.9487380981;
   fMin_1[0][1] = 0.950958848;
   fMax_1[0][1] = 18.7872695923;
   fMin_1[1][1] = 1.32190299034;
   fMax_1[1][1] = 20.4582691193;
   fMin_1[2][1] = 0.950958848;
   fMax_1[2][1] = 20.4582691193;
   fMin_1[0][2] = 0.541395664215;
   fMax_1[0][2] = 17.7745265961;
   fMin_1[1][2] = 0.651882708073;
   fMax_1[1][2] = 19.5425701141;
   fMin_1[2][2] = 0.541395664215;
   fMax_1[2][2] = 19.5425701141;
   fMin_1[0][3] = 8.03139591217;
   fMax_1[0][3] = 21.5482387543;
   fMin_1[1][3] = 12.0475664139;
   fMax_1[1][3] = 21.8248806;
   fMin_1[2][3] = 8.03139591217;
   fMax_1[2][3] = 21.8248806;
   fMin_1[0][4] = 0.0501248650253;
   fMax_1[0][4] = 0.999834001064;
   fMin_1[1][4] = 0.0506580136716;
   fMax_1[1][4] = 0.984503746033;
   fMin_1[2][4] = 0.0501248650253;
   fMax_1[2][4] = 0.999834001064;
   fMin_1[0][5] = 0.0509073212743;
   fMax_1[0][5] = 0.99915009737;
   fMin_1[1][5] = 0.0554051734507;
   fMax_1[1][5] = 0.965280473232;
   fMin_1[2][5] = 0.0509073212743;
   fMax_1[2][5] = 0.99915009737;
   fMin_1[0][6] = 0.000363119848771;
   fMax_1[0][6] = 0.19725073874;
   fMin_1[1][6] = 0.00345219043083;
   fMax_1[1][6] = 0.186850979924;
   fMin_1[2][6] = 0.000363119848771;
   fMax_1[2][6] = 0.19725073874;
   fMin_1[0][7] = 0.00185923371464;
   fMax_1[0][7] = 0.199973419309;
   fMin_1[1][7] = 0.000838859472424;
   fMax_1[1][7] = 0.186899185181;
   fMin_1[2][7] = 0.000838859472424;
   fMax_1[2][7] = 0.199973419309;
   fMin_1[0][8] = 2.00301671028;
   fMax_1[0][8] = 212.443771362;
   fMin_1[1][8] = 2.01786613464;
   fMax_1[1][8] = 633.239868164;
   fMin_1[2][8] = 2.00301671028;
   fMax_1[2][8] = 633.239868164;
   fMin_1[0][9] = 2.05955266953;
   fMax_1[0][9] = 100.371292114;
   fMin_1[1][9] = 2.03857517242;
   fMax_1[1][9] = 23.1527786255;
   fMin_1[2][9] = 2.03857517242;
   fMax_1[2][9] = 100.371292114;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 10;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<10;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
