// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/13       [393741]
Creator        : leure
Date           : Wed Jun  7 21:04:47 2017
Host           : Linux vocms029.cern.ch 2.6.32-504.12.2.el6.x86_64 #1 SMP Thu Mar 12 07:33:00 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /data/leure/TMVA_Luke/myTMVA
Training events: 12459
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                                                         'F'    [0.502701044083,86.3675079346]
DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                                                      'F'    [0.547004878521,87.8757324219]
DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                                                      'F'    [0.501080751419,85.395324707]
DtktkRespt                    DtktkRespt                    DtktkRespt                    DtktkRespt                                                      'F'    [8.01869392395,97.6102981567]
Dchi2cl                       Dchi2cl                       Dchi2cl                       Dchi2cl                                                         'F'    [0.0500933974981,0.999967932701]
DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl                                                 'F'    [0.0500601939857,0.999930679798]
Dalpha                        Dalpha                        Dalpha                        Dalpha                                                          'F'    [2.90316274913e-05,0.199813067913]
DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                                                  'F'    [7.98378823674e-05,0.198054850101]
DsvpvDistance/DsvpvDisErr     DsvpvDistance_D_DsvpvDisErr   DsvpvDistance/DsvpvDisErr     DsvpvDistance/DsvpvDisErr                                       'F'    [2.0015206337,798.914794922]
DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance_D_DtktkRes_svpvDisErr DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance/DtktkRes_svpvDisErr                                                   'F'    [2.008061409,531.915466309]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Dtrk1Pt", "DRestrk1Pt", "DRestrk2Pt", "DtktkRespt", "Dchi2cl", "DtktkRes_chi2cl", "Dalpha", "DtktkRes_alpha", "DsvpvDistance/DsvpvDisErr", "DtktkRes_svpvDistance/DtktkRes_svpvDisErr" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][10];
   double fMax_1[3][10];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[16][11];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][16];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 11; fWeights[0] = new double[11]; 
   fLayerSize[1] = 16; fWeights[1] = new double[16]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.368841872562429;
   fWeightMatrix0to1[1][0] = 1.95634318012047;
   fWeightMatrix0to1[2][0] = 0.854750881637899;
   fWeightMatrix0to1[3][0] = 1.87945611800117;
   fWeightMatrix0to1[4][0] = -1.81280196714257;
   fWeightMatrix0to1[5][0] = -1.17099492522396;
   fWeightMatrix0to1[6][0] = -0.248811360091804;
   fWeightMatrix0to1[7][0] = 1.94052972879207;
   fWeightMatrix0to1[8][0] = -1.38461750686535;
   fWeightMatrix0to1[9][0] = -1.39620564213111;
   fWeightMatrix0to1[10][0] = -2.00540695038603;
   fWeightMatrix0to1[11][0] = -0.383701228412986;
   fWeightMatrix0to1[12][0] = -1.19710376618211;
   fWeightMatrix0to1[13][0] = -0.288803109550943;
   fWeightMatrix0to1[14][0] = -0.820201357536726;
   fWeightMatrix0to1[0][1] = 0.865693482090674;
   fWeightMatrix0to1[1][1] = -0.30587436408603;
   fWeightMatrix0to1[2][1] = 1.57610148228125;
   fWeightMatrix0to1[3][1] = 0.333453265122887;
   fWeightMatrix0to1[4][1] = 1.38785765510734;
   fWeightMatrix0to1[5][1] = -0.0809910945100928;
   fWeightMatrix0to1[6][1] = -0.67371199714504;
   fWeightMatrix0to1[7][1] = 0.480779927112069;
   fWeightMatrix0to1[8][1] = -0.126267411285154;
   fWeightMatrix0to1[9][1] = -1.25708064954209;
   fWeightMatrix0to1[10][1] = -0.832537811644277;
   fWeightMatrix0to1[11][1] = 1.33279665003463;
   fWeightMatrix0to1[12][1] = -0.81099204470819;
   fWeightMatrix0to1[13][1] = -1.75964071600521;
   fWeightMatrix0to1[14][1] = -0.338419193868024;
   fWeightMatrix0to1[0][2] = 0.818411885100956;
   fWeightMatrix0to1[1][2] = 1.70412157307077;
   fWeightMatrix0to1[2][2] = -0.498473537726001;
   fWeightMatrix0to1[3][2] = 0.224647043520327;
   fWeightMatrix0to1[4][2] = 0.380827601070905;
   fWeightMatrix0to1[5][2] = 0.588201619589625;
   fWeightMatrix0to1[6][2] = -1.93683945226273;
   fWeightMatrix0to1[7][2] = 1.53988554544056;
   fWeightMatrix0to1[8][2] = -1.40164532151989;
   fWeightMatrix0to1[9][2] = -0.144908200644122;
   fWeightMatrix0to1[10][2] = 0.635173238869974;
   fWeightMatrix0to1[11][2] = 0.852956834657632;
   fWeightMatrix0to1[12][2] = 2.06594643260961;
   fWeightMatrix0to1[13][2] = 1.31355393957698;
   fWeightMatrix0to1[14][2] = -1.13328543380887;
   fWeightMatrix0to1[0][3] = -1.43617908162423;
   fWeightMatrix0to1[1][3] = 0.838579969350501;
   fWeightMatrix0to1[2][3] = -0.109506060489757;
   fWeightMatrix0to1[3][3] = 1.5711111777408;
   fWeightMatrix0to1[4][3] = 1.4520853150209;
   fWeightMatrix0to1[5][3] = 2.05082339805564;
   fWeightMatrix0to1[6][3] = 0.995920712566985;
   fWeightMatrix0to1[7][3] = -1.92907830781272;
   fWeightMatrix0to1[8][3] = 1.14370671205795;
   fWeightMatrix0to1[9][3] = -2.20769443677828;
   fWeightMatrix0to1[10][3] = -1.23472991315729;
   fWeightMatrix0to1[11][3] = -1.44021838803091;
   fWeightMatrix0to1[12][3] = -1.52203614952778;
   fWeightMatrix0to1[13][3] = 1.57368565473245;
   fWeightMatrix0to1[14][3] = 0.249434973799004;
   fWeightMatrix0to1[0][4] = -1.59032938003523;
   fWeightMatrix0to1[1][4] = 0.335864368186405;
   fWeightMatrix0to1[2][4] = -0.239551839934006;
   fWeightMatrix0to1[3][4] = 0.50730178997181;
   fWeightMatrix0to1[4][4] = 1.67788299165352;
   fWeightMatrix0to1[5][4] = -0.400698392307806;
   fWeightMatrix0to1[6][4] = 0.143833719788185;
   fWeightMatrix0to1[7][4] = -0.825190643614707;
   fWeightMatrix0to1[8][4] = 0.508800706869727;
   fWeightMatrix0to1[9][4] = -0.139975215520586;
   fWeightMatrix0to1[10][4] = -0.728521485159594;
   fWeightMatrix0to1[11][4] = -1.18887487451319;
   fWeightMatrix0to1[12][4] = 0.561302537002738;
   fWeightMatrix0to1[13][4] = 1.13956719218558;
   fWeightMatrix0to1[14][4] = 0.878015175467167;
   fWeightMatrix0to1[0][5] = -0.296781022493465;
   fWeightMatrix0to1[1][5] = -1.86646522363865;
   fWeightMatrix0to1[2][5] = -1.74163523730118;
   fWeightMatrix0to1[3][5] = 0.745916419738302;
   fWeightMatrix0to1[4][5] = 0.526602597335824;
   fWeightMatrix0to1[5][5] = 1.42843849675002;
   fWeightMatrix0to1[6][5] = 0.328295727078879;
   fWeightMatrix0to1[7][5] = 0.797831569612472;
   fWeightMatrix0to1[8][5] = -0.692497450594389;
   fWeightMatrix0to1[9][5] = -0.603595809446814;
   fWeightMatrix0to1[10][5] = -0.0150938693897909;
   fWeightMatrix0to1[11][5] = 0.854128245444754;
   fWeightMatrix0to1[12][5] = -1.12583218782656;
   fWeightMatrix0to1[13][5] = -1.45898964015667;
   fWeightMatrix0to1[14][5] = -1.34773504570999;
   fWeightMatrix0to1[0][6] = -0.0323931331189859;
   fWeightMatrix0to1[1][6] = -0.0326261826934204;
   fWeightMatrix0to1[2][6] = 1.41021684069403;
   fWeightMatrix0to1[3][6] = -0.989241532141652;
   fWeightMatrix0to1[4][6] = -0.686885304720837;
   fWeightMatrix0to1[5][6] = 1.66620300203485;
   fWeightMatrix0to1[6][6] = -0.732544564375719;
   fWeightMatrix0to1[7][6] = -1.64972213341551;
   fWeightMatrix0to1[8][6] = -1.64424909904288;
   fWeightMatrix0to1[9][6] = -1.57839028261121;
   fWeightMatrix0to1[10][6] = -1.54550903631672;
   fWeightMatrix0to1[11][6] = -1.94225111828531;
   fWeightMatrix0to1[12][6] = 0.961898311468889;
   fWeightMatrix0to1[13][6] = 1.7878944397319;
   fWeightMatrix0to1[14][6] = -1.34634715478938;
   fWeightMatrix0to1[0][7] = 1.53848090179773;
   fWeightMatrix0to1[1][7] = -0.892504224062566;
   fWeightMatrix0to1[2][7] = -0.696928103333739;
   fWeightMatrix0to1[3][7] = 0.342648364667346;
   fWeightMatrix0to1[4][7] = 0.475610477530897;
   fWeightMatrix0to1[5][7] = -1.28325105548236;
   fWeightMatrix0to1[6][7] = 0.460557606912132;
   fWeightMatrix0to1[7][7] = 0.0722904125817839;
   fWeightMatrix0to1[8][7] = 0.309606259322797;
   fWeightMatrix0to1[9][7] = -1.80011389216719;
   fWeightMatrix0to1[10][7] = 1.07312107803111;
   fWeightMatrix0to1[11][7] = 0.432010738112154;
   fWeightMatrix0to1[12][7] = -0.904209909678584;
   fWeightMatrix0to1[13][7] = 0.977058388543073;
   fWeightMatrix0to1[14][7] = -0.946045311335642;
   fWeightMatrix0to1[0][8] = -1.47387648519402;
   fWeightMatrix0to1[1][8] = 0.201366220377412;
   fWeightMatrix0to1[2][8] = -0.457953054954909;
   fWeightMatrix0to1[3][8] = 2.00875506974094;
   fWeightMatrix0to1[4][8] = 0.950792745286071;
   fWeightMatrix0to1[5][8] = 0.539299168753582;
   fWeightMatrix0to1[6][8] = -0.413488268952349;
   fWeightMatrix0to1[7][8] = -0.0140909064491486;
   fWeightMatrix0to1[8][8] = -1.87587243273731;
   fWeightMatrix0to1[9][8] = 0.435172098347625;
   fWeightMatrix0to1[10][8] = -0.999106112944799;
   fWeightMatrix0to1[11][8] = -1.83582995601085;
   fWeightMatrix0to1[12][8] = 0.89845763213486;
   fWeightMatrix0to1[13][8] = -1.21438855277352;
   fWeightMatrix0to1[14][8] = -0.505510136427695;
   fWeightMatrix0to1[0][9] = 1.27027243667343;
   fWeightMatrix0to1[1][9] = 1.84152793747955;
   fWeightMatrix0to1[2][9] = -2.02225559639519;
   fWeightMatrix0to1[3][9] = 0.546418749319463;
   fWeightMatrix0to1[4][9] = 1.72092992070848;
   fWeightMatrix0to1[5][9] = 2.06640716759861;
   fWeightMatrix0to1[6][9] = 0.263978541068569;
   fWeightMatrix0to1[7][9] = -1.56504674711727;
   fWeightMatrix0to1[8][9] = -0.238326583552642;
   fWeightMatrix0to1[9][9] = -1.86884492178743;
   fWeightMatrix0to1[10][9] = 0.512809521297016;
   fWeightMatrix0to1[11][9] = 1.16466270978632;
   fWeightMatrix0to1[12][9] = -0.27528898205723;
   fWeightMatrix0to1[13][9] = -0.182439709198196;
   fWeightMatrix0to1[14][9] = -0.410431104623301;
   fWeightMatrix0to1[0][10] = -1.49350642200452;
   fWeightMatrix0to1[1][10] = 0.502819700503478;
   fWeightMatrix0to1[2][10] = 1.89076692572681;
   fWeightMatrix0to1[3][10] = -1.1854745287354;
   fWeightMatrix0to1[4][10] = -0.802666094081592;
   fWeightMatrix0to1[5][10] = -0.476335518275823;
   fWeightMatrix0to1[6][10] = 1.09992376811561;
   fWeightMatrix0to1[7][10] = 0.798976435040264;
   fWeightMatrix0to1[8][10] = 1.20155149415795;
   fWeightMatrix0to1[9][10] = -0.321519842975151;
   fWeightMatrix0to1[10][10] = 2.58132663979747;
   fWeightMatrix0to1[11][10] = 0.847158028685675;
   fWeightMatrix0to1[12][10] = 0.226321097806056;
   fWeightMatrix0to1[13][10] = 0.377490089668329;
   fWeightMatrix0to1[14][10] = 1.52435188951526;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.00248903030562335;
   fWeightMatrix1to2[0][1] = 0.0128407850846228;
   fWeightMatrix1to2[0][2] = -0.00230012451517292;
   fWeightMatrix1to2[0][3] = 0.0441997370544225;
   fWeightMatrix1to2[0][4] = 0.023542769376307;
   fWeightMatrix1to2[0][5] = -0.0919098028545089;
   fWeightMatrix1to2[0][6] = 1.18864988131728;
   fWeightMatrix1to2[0][7] = 0.0318821376578989;
   fWeightMatrix1to2[0][8] = 1.64497583760828;
   fWeightMatrix1to2[0][9] = 1.39224181729597;
   fWeightMatrix1to2[0][10] = -0.949358460034827;
   fWeightMatrix1to2[0][11] = -0.0335703205708286;
   fWeightMatrix1to2[0][12] = 0.0110578451534615;
   fWeightMatrix1to2[0][13] = -0.00673965195960958;
   fWeightMatrix1to2[0][14] = -0.989088537961275;
   fWeightMatrix1to2[0][15] = -1.29413882982391;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.526233792305;
   fMax_1[0][0] = 86.3675079346;
   fMin_1[1][0] = 0.502701044083;
   fMax_1[1][0] = 75.455329895;
   fMin_1[2][0] = 0.502701044083;
   fMax_1[2][0] = 86.3675079346;
   fMin_1[0][1] = 0.547004878521;
   fMax_1[0][1] = 87.8757324219;
   fMin_1[1][1] = 0.565647721291;
   fMax_1[1][1] = 65.9077224731;
   fMin_1[2][1] = 0.547004878521;
   fMax_1[2][1] = 87.8757324219;
   fMin_1[0][2] = 0.501080751419;
   fMax_1[0][2] = 85.395324707;
   fMin_1[1][2] = 0.675592899323;
   fMax_1[1][2] = 80.6340332031;
   fMin_1[2][2] = 0.501080751419;
   fMax_1[2][2] = 85.395324707;
   fMin_1[0][3] = 8.01869392395;
   fMax_1[0][3] = 97.6102981567;
   fMin_1[1][3] = 8.56177043915;
   fMax_1[1][3] = 91.5057144165;
   fMin_1[2][3] = 8.01869392395;
   fMax_1[2][3] = 97.6102981567;
   fMin_1[0][4] = 0.0500933974981;
   fMax_1[0][4] = 0.999967932701;
   fMin_1[1][4] = 0.0661060735583;
   fMax_1[1][4] = 0.973337829113;
   fMin_1[2][4] = 0.0500933974981;
   fMax_1[2][4] = 0.999967932701;
   fMin_1[0][5] = 0.0500601939857;
   fMax_1[0][5] = 0.999930679798;
   fMin_1[1][5] = 0.0535034202039;
   fMax_1[1][5] = 0.998563885689;
   fMin_1[2][5] = 0.0500601939857;
   fMax_1[2][5] = 0.999930679798;
   fMin_1[0][6] = 2.90316274913e-05;
   fMax_1[0][6] = 0.199813067913;
   fMin_1[1][6] = 0.00191284308676;
   fMax_1[1][6] = 0.191084235907;
   fMin_1[2][6] = 2.90316274913e-05;
   fMax_1[2][6] = 0.199813067913;
   fMin_1[0][7] = 7.98378823674e-05;
   fMax_1[0][7] = 0.198054850101;
   fMin_1[1][7] = 0.000534758786671;
   fMax_1[1][7] = 0.157269135118;
   fMin_1[2][7] = 7.98378823674e-05;
   fMax_1[2][7] = 0.198054850101;
   fMin_1[0][8] = 2.0015206337;
   fMax_1[0][8] = 798.914794922;
   fMin_1[1][8] = 2.02741146088;
   fMax_1[1][8] = 279.54486084;
   fMin_1[2][8] = 2.0015206337;
   fMax_1[2][8] = 798.914794922;
   fMin_1[0][9] = 2.008061409;
   fMax_1[0][9] = 531.915466309;
   fMin_1[1][9] = 2.01771521568;
   fMax_1[1][9] = 267.912597656;
   fMin_1[2][9] = 2.008061409;
   fMax_1[2][9] = 531.915466309;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 10;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<10;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
