// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/13       [393741]
Creator        : leure
Date           : Tue Jun  6 18:43:09 2017
Host           : Linux vocms029.cern.ch 2.6.32-504.12.2.el6.x86_64 #1 SMP Thu Mar 12 07:33:00 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /data/leure/TMVA_Luke/myTMVA
Training events: 1194
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                                                         'F'    [0.511286377907,16.9143886566]
DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                                                      'F'    [0.611003220081,22.8015193939]
DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                                                      'F'    [0.500483810902,21.6606121063]
DtktkRespt                    DtktkRespt                    DtktkRespt                    DtktkRespt                                                      'F'    [8.03139591217,24.6242904663]
Dchi2cl                       Dchi2cl                       Dchi2cl                       Dchi2cl                                                         'F'    [0.0503599233925,0.999834001064]
DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl                                                 'F'    [0.0503450036049,0.999168813229]
Dalpha                        Dalpha                        Dalpha                        Dalpha                                                          'F'    [0.000363119848771,0.199750348926]
DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                                                  'F'    [0.00018514196563,0.199973419309]
DsvpvDistance/DsvpvDisErr     DsvpvDistance_D_DsvpvDisErr   DsvpvDistance/DsvpvDisErr     DsvpvDistance/DsvpvDisErr                                       'F'    [2.01438426971,2133.9609375]
DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance_D_DtktkRes_svpvDisErr DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance/DtktkRes_svpvDisErr                                                   'F'    [2.01058912277,154.844345093]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Dtrk1Pt", "DRestrk1Pt", "DRestrk2Pt", "DtktkRespt", "Dchi2cl", "DtktkRes_chi2cl", "Dalpha", "DtktkRes_alpha", "DsvpvDistance/DsvpvDisErr", "DtktkRes_svpvDistance/DtktkRes_svpvDisErr" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 0.99999988079071;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][10];
   double fMax_1[3][10];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[16][11];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][16];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 11; fWeights[0] = new double[11]; 
   fLayerSize[1] = 16; fWeights[1] = new double[16]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.663087899570335;
   fWeightMatrix0to1[1][0] = 1.77104120797412;
   fWeightMatrix0to1[2][0] = 0.902985621117279;
   fWeightMatrix0to1[3][0] = 1.82873620811987;
   fWeightMatrix0to1[4][0] = -1.78520078600784;
   fWeightMatrix0to1[5][0] = -1.39615116762004;
   fWeightMatrix0to1[6][0] = -0.803364764828966;
   fWeightMatrix0to1[7][0] = 2.24596399542151;
   fWeightMatrix0to1[8][0] = -1.31528915078811;
   fWeightMatrix0to1[9][0] = -0.916552752427151;
   fWeightMatrix0to1[10][0] = -1.53545980705526;
   fWeightMatrix0to1[11][0] = 2.24900250613436;
   fWeightMatrix0to1[12][0] = -0.94081398866435;
   fWeightMatrix0to1[13][0] = -0.320450465944619;
   fWeightMatrix0to1[14][0] = -0.468883728521323;
   fWeightMatrix0to1[0][1] = 0.504205027081838;
   fWeightMatrix0to1[1][1] = -0.524434587412863;
   fWeightMatrix0to1[2][1] = 1.50759735634643;
   fWeightMatrix0to1[3][1] = 0.205808647184127;
   fWeightMatrix0to1[4][1] = 1.25068300922475;
   fWeightMatrix0to1[5][1] = -0.0441805885768588;
   fWeightMatrix0to1[6][1] = -0.996706257551256;
   fWeightMatrix0to1[7][1] = 0.850541268863087;
   fWeightMatrix0to1[8][1] = -0.323976043559122;
   fWeightMatrix0to1[9][1] = -1.09792412838352;
   fWeightMatrix0to1[10][1] = -0.209034088302626;
   fWeightMatrix0to1[11][1] = 0.786706934543419;
   fWeightMatrix0to1[12][1] = -0.875185899444526;
   fWeightMatrix0to1[13][1] = -1.72881639136603;
   fWeightMatrix0to1[14][1] = 0.000842886078414563;
   fWeightMatrix0to1[0][2] = 0.722404990133445;
   fWeightMatrix0to1[1][2] = 1.7222372557456;
   fWeightMatrix0to1[2][2] = -0.459294065384887;
   fWeightMatrix0to1[3][2] = 0.0661849078633893;
   fWeightMatrix0to1[4][2] = 0.221526018556489;
   fWeightMatrix0to1[5][2] = 0.0373168380321737;
   fWeightMatrix0to1[6][2] = -1.37241752683895;
   fWeightMatrix0to1[7][2] = 1.40055509861115;
   fWeightMatrix0to1[8][2] = -1.00456158238773;
   fWeightMatrix0to1[9][2] = 1.07702516052504;
   fWeightMatrix0to1[10][2] = 0.676952865378444;
   fWeightMatrix0to1[11][2] = 0.74981704388253;
   fWeightMatrix0to1[12][2] = 1.91077735052114;
   fWeightMatrix0to1[13][2] = 1.31901350374948;
   fWeightMatrix0to1[14][2] = -1.23479828114937;
   fWeightMatrix0to1[0][3] = -1.48709466935216;
   fWeightMatrix0to1[1][3] = 0.875192765064357;
   fWeightMatrix0to1[2][3] = -0.105447435418926;
   fWeightMatrix0to1[3][3] = 1.52613910027096;
   fWeightMatrix0to1[4][3] = 1.25614290708658;
   fWeightMatrix0to1[5][3] = 1.68437200168717;
   fWeightMatrix0to1[6][3] = 1.21105292345193;
   fWeightMatrix0to1[7][3] = -1.90438534128858;
   fWeightMatrix0to1[8][3] = 1.2135819472702;
   fWeightMatrix0to1[9][3] = -1.84126427540796;
   fWeightMatrix0to1[10][3] = -1.26325668036063;
   fWeightMatrix0to1[11][3] = -1.37191318773979;
   fWeightMatrix0to1[12][3] = -1.88676519264453;
   fWeightMatrix0to1[13][3] = 1.55547477247297;
   fWeightMatrix0to1[14][3] = 0.356269830765786;
   fWeightMatrix0to1[0][4] = -1.72549432856811;
   fWeightMatrix0to1[1][4] = 0.164312159815421;
   fWeightMatrix0to1[2][4] = -0.115178770202347;
   fWeightMatrix0to1[3][4] = 0.488514100775038;
   fWeightMatrix0to1[4][4] = 1.94954789865981;
   fWeightMatrix0to1[5][4] = -0.554133855081612;
   fWeightMatrix0to1[6][4] = -0.0868767613637571;
   fWeightMatrix0to1[7][4] = -0.68468084940046;
   fWeightMatrix0to1[8][4] = 0.168552367205917;
   fWeightMatrix0to1[9][4] = 0.0600532584009989;
   fWeightMatrix0to1[10][4] = -0.38104783015892;
   fWeightMatrix0to1[11][4] = 0.0946207000754497;
   fWeightMatrix0to1[12][4] = 0.223487550990077;
   fWeightMatrix0to1[13][4] = 1.24487703554728;
   fWeightMatrix0to1[14][4] = 0.8125096948759;
   fWeightMatrix0to1[0][5] = -0.262360357748189;
   fWeightMatrix0to1[1][5] = -1.76186545236546;
   fWeightMatrix0to1[2][5] = -1.68196946359782;
   fWeightMatrix0to1[3][5] = 0.761605100608658;
   fWeightMatrix0to1[4][5] = 0.49829883426654;
   fWeightMatrix0to1[5][5] = 1.13985107712433;
   fWeightMatrix0to1[6][5] = 0.397909070313539;
   fWeightMatrix0to1[7][5] = 0.868352835131648;
   fWeightMatrix0to1[8][5] = -0.620332863213328;
   fWeightMatrix0to1[9][5] = -1.4744287948247;
   fWeightMatrix0to1[10][5] = 0.503687695859664;
   fWeightMatrix0to1[11][5] = 0.0737856427903517;
   fWeightMatrix0to1[12][5] = -0.911564849189681;
   fWeightMatrix0to1[13][5] = -1.67260530078132;
   fWeightMatrix0to1[14][5] = -1.39436526746684;
   fWeightMatrix0to1[0][6] = -0.335106705667721;
   fWeightMatrix0to1[1][6] = -0.0839233176974614;
   fWeightMatrix0to1[2][6] = 1.29072366618348;
   fWeightMatrix0to1[3][6] = -1.18153650320601;
   fWeightMatrix0to1[4][6] = -0.840410644528027;
   fWeightMatrix0to1[5][6] = 1.79418012775821;
   fWeightMatrix0to1[6][6] = -0.803153051376045;
   fWeightMatrix0to1[7][6] = -1.5240119691956;
   fWeightMatrix0to1[8][6] = -1.50849198971687;
   fWeightMatrix0to1[9][6] = -0.222621011784802;
   fWeightMatrix0to1[10][6] = -1.95575338685615;
   fWeightMatrix0to1[11][6] = -0.691130606546318;
   fWeightMatrix0to1[12][6] = 1.11742303676439;
   fWeightMatrix0to1[13][6] = 1.77607404023614;
   fWeightMatrix0to1[14][6] = -0.859714972859047;
   fWeightMatrix0to1[0][7] = 1.36892798184888;
   fWeightMatrix0to1[1][7] = -1.27961224008478;
   fWeightMatrix0to1[2][7] = -0.781049068140068;
   fWeightMatrix0to1[3][7] = 0.0548125441364989;
   fWeightMatrix0to1[4][7] = 0.353851926895724;
   fWeightMatrix0to1[5][7] = -1.31461739200755;
   fWeightMatrix0to1[6][7] = 0.51638206518121;
   fWeightMatrix0to1[7][7] = 0.327059267358832;
   fWeightMatrix0to1[8][7] = 0.36718259623233;
   fWeightMatrix0to1[9][7] = -0.700943690562077;
   fWeightMatrix0to1[10][7] = 1.5011801281782;
   fWeightMatrix0to1[11][7] = 0.444515354973559;
   fWeightMatrix0to1[12][7] = -0.991761081319036;
   fWeightMatrix0to1[13][7] = 0.867114247325859;
   fWeightMatrix0to1[14][7] = -0.343737588762767;
   fWeightMatrix0to1[0][8] = -2.01164696252208;
   fWeightMatrix0to1[1][8] = -0.0889251361664201;
   fWeightMatrix0to1[2][8] = -0.696318349169364;
   fWeightMatrix0to1[3][8] = 2.2072266689254;
   fWeightMatrix0to1[4][8] = 0.797916101266546;
   fWeightMatrix0to1[5][8] = 0.8063380401298;
   fWeightMatrix0to1[6][8] = -0.515838112557376;
   fWeightMatrix0to1[7][8] = 0.11385854856606;
   fWeightMatrix0to1[8][8] = -1.79534481270855;
   fWeightMatrix0to1[9][8] = 1.20448203436052;
   fWeightMatrix0to1[10][8] = -0.246389713888594;
   fWeightMatrix0to1[11][8] = -3.01416225359068;
   fWeightMatrix0to1[12][8] = 1.22223046716686;
   fWeightMatrix0to1[13][8] = -1.02233102163829;
   fWeightMatrix0to1[14][8] = -0.789373376210894;
   fWeightMatrix0to1[0][9] = 0.693543245911891;
   fWeightMatrix0to1[1][9] = 1.51282665928528;
   fWeightMatrix0to1[2][9] = -2.09701524338293;
   fWeightMatrix0to1[3][9] = 0.552340976487306;
   fWeightMatrix0to1[4][9] = 1.6997137908858;
   fWeightMatrix0to1[5][9] = 1.96588714010338;
   fWeightMatrix0to1[6][9] = -0.0493992333545622;
   fWeightMatrix0to1[7][9] = -1.29127578147906;
   fWeightMatrix0to1[8][9] = -0.263179851803766;
   fWeightMatrix0to1[9][9] = -1.20050254923514;
   fWeightMatrix0to1[10][9] = 1.11916997579959;
   fWeightMatrix0to1[11][9] = 2.00133856833901;
   fWeightMatrix0to1[12][9] = -0.0438502459543236;
   fWeightMatrix0to1[13][9] = 0.0150570451994597;
   fWeightMatrix0to1[14][9] = -0.628212194822258;
   fWeightMatrix0to1[0][10] = -0.920779555272135;
   fWeightMatrix0to1[1][10] = 0.82740512926049;
   fWeightMatrix0to1[2][10] = 2.09741535847129;
   fWeightMatrix0to1[3][10] = -1.00676958795879;
   fWeightMatrix0to1[4][10] = -0.618635194150958;
   fWeightMatrix0to1[5][10] = -0.578520305771827;
   fWeightMatrix0to1[6][10] = 1.19175007387404;
   fWeightMatrix0to1[7][10] = 0.632328200682111;
   fWeightMatrix0to1[8][10] = 1.16528569123065;
   fWeightMatrix0to1[9][10] = -1.57402217819889;
   fWeightMatrix0to1[10][10] = 1.9101858964941;
   fWeightMatrix0to1[11][10] = 2.10667797017297;
   fWeightMatrix0to1[12][10] = -0.0865254284986998;
   fWeightMatrix0to1[13][10] = 0.187368117236131;
   fWeightMatrix0to1[14][10] = 1.62841375077263;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.00100714003237803;
   fWeightMatrix1to2[0][1] = -0.0128611633231498;
   fWeightMatrix1to2[0][2] = 0.0918329602095279;
   fWeightMatrix1to2[0][3] = -0.352108428205058;
   fWeightMatrix1to2[0][4] = 0.00683964994390169;
   fWeightMatrix1to2[0][5] = 0.0824168542335659;
   fWeightMatrix1to2[0][6] = 0.970591321070596;
   fWeightMatrix1to2[0][7] = -0.00904097452825687;
   fWeightMatrix1to2[0][8] = 1.21958696891704;
   fWeightMatrix1to2[0][9] = -0.0298575389568612;
   fWeightMatrix1to2[0][10] = -0.0626514526079752;
   fWeightMatrix1to2[0][11] = 0.957001549991986;
   fWeightMatrix1to2[0][12] = 0.0639423870630129;
   fWeightMatrix1to2[0][13] = 0.0228994338360919;
   fWeightMatrix1to2[0][14] = -0.93043481555033;
   fWeightMatrix1to2[0][15] = -1.44682708657065;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.511286377907;
   fMax_1[0][0] = 16.9143886566;
   fMin_1[1][0] = 0.511792123318;
   fMax_1[1][0] = 15.1881942749;
   fMin_1[2][0] = 0.511286377907;
   fMax_1[2][0] = 16.9143886566;
   fMin_1[0][1] = 0.611003220081;
   fMax_1[0][1] = 22.8015193939;
   fMin_1[1][1] = 0.626341223717;
   fMax_1[1][1] = 21.8260803223;
   fMin_1[2][1] = 0.611003220081;
   fMax_1[2][1] = 22.8015193939;
   fMin_1[0][2] = 0.500483810902;
   fMax_1[0][2] = 20.3572921753;
   fMin_1[1][2] = 0.651882708073;
   fMax_1[1][2] = 21.6606121063;
   fMin_1[2][2] = 0.500483810902;
   fMax_1[2][2] = 21.6606121063;
   fMin_1[0][3] = 8.03139591217;
   fMax_1[0][3] = 24.4367542267;
   fMin_1[1][3] = 9.19473171234;
   fMax_1[1][3] = 24.6242904663;
   fMin_1[2][3] = 8.03139591217;
   fMax_1[2][3] = 24.6242904663;
   fMin_1[0][4] = 0.0503599233925;
   fMax_1[0][4] = 0.999834001064;
   fMin_1[1][4] = 0.0506580136716;
   fMax_1[1][4] = 0.984503746033;
   fMin_1[2][4] = 0.0503599233925;
   fMax_1[2][4] = 0.999834001064;
   fMin_1[0][5] = 0.0503450036049;
   fMax_1[0][5] = 0.999168813229;
   fMin_1[1][5] = 0.0554051734507;
   fMax_1[1][5] = 0.979975402355;
   fMin_1[2][5] = 0.0503450036049;
   fMax_1[2][5] = 0.999168813229;
   fMin_1[0][6] = 0.000363119848771;
   fMax_1[0][6] = 0.199750348926;
   fMin_1[1][6] = 0.00140371813904;
   fMax_1[1][6] = 0.191456958652;
   fMin_1[2][6] = 0.000363119848771;
   fMax_1[2][6] = 0.199750348926;
   fMin_1[0][7] = 0.00172958220355;
   fMax_1[0][7] = 0.199973419309;
   fMin_1[1][7] = 0.00018514196563;
   fMax_1[1][7] = 0.186899185181;
   fMin_1[2][7] = 0.00018514196563;
   fMax_1[2][7] = 0.199973419309;
   fMin_1[0][8] = 2.06552958488;
   fMax_1[0][8] = 212.443771362;
   fMin_1[1][8] = 2.01438426971;
   fMax_1[1][8] = 2133.9609375;
   fMin_1[2][8] = 2.01438426971;
   fMax_1[2][8] = 2133.9609375;
   fMin_1[0][9] = 2.12771296501;
   fMax_1[0][9] = 113.762290955;
   fMin_1[1][9] = 2.01058912277;
   fMax_1[1][9] = 154.844345093;
   fMin_1[2][9] = 2.01058912277;
   fMax_1[2][9] = 154.844345093;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 10;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<10;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
