// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/13       [393741]
Creator        : leure
Date           : Tue Jun  6 19:51:46 2017
Host           : Linux vocms029.cern.ch 2.6.32-504.12.2.el6.x86_64 #1 SMP Thu Mar 12 07:33:00 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /data/leure/TMVA_Luke/myTMVA
Training events: 6651
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                                                         'F'    [0.501860499382,51.7713851929]
DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                                                      'F'    [0.693660438061,56.3495254517]
DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                                                      'F'    [0.501416265965,50.7236557007]
DtktkRespt                    DtktkRespt                    DtktkRespt                    DtktkRespt                                                      'F'    [8.00832366943,58.8731307983]
Dchi2cl                       Dchi2cl                       Dchi2cl                       Dchi2cl                                                         'F'    [0.0501119084656,0.999967932701]
DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl                                                 'F'    [0.0501329638064,0.999576151371]
Dalpha                        Dalpha                        Dalpha                        Dalpha                                                          'F'    [2.90316274913e-05,0.199643790722]
DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                                                  'F'    [7.98378823674e-05,0.199953570962]
DsvpvDistance/DsvpvDisErr     DsvpvDistance_D_DsvpvDisErr   DsvpvDistance/DsvpvDisErr     DsvpvDistance/DsvpvDisErr                                       'F'    [2.0015206337,587.856567383]
DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance_D_DtktkRes_svpvDisErr DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance/DtktkRes_svpvDisErr                                                   'F'    [2.010004282,503.130828857]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Dtrk1Pt", "DRestrk1Pt", "DRestrk2Pt", "DtktkRespt", "Dchi2cl", "DtktkRes_chi2cl", "Dalpha", "DtktkRes_alpha", "DsvpvDistance/DsvpvDisErr", "DtktkRes_svpvDistance/DtktkRes_svpvDisErr" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 0.99999988079071;
      fVmin[8] = -1;
      fVmax[8] = 0.99999988079071;
      fVmin[9] = -1;
      fVmax[9] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][10];
   double fMax_1[3][10];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[16][11];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][16];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 11; fWeights[0] = new double[11]; 
   fLayerSize[1] = 16; fWeights[1] = new double[16]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.382805411936011;
   fWeightMatrix0to1[1][0] = 1.80358812157148;
   fWeightMatrix0to1[2][0] = 0.7613555352759;
   fWeightMatrix0to1[3][0] = 1.80961163154309;
   fWeightMatrix0to1[4][0] = -1.97543832051997;
   fWeightMatrix0to1[5][0] = -1.36967211892498;
   fWeightMatrix0to1[6][0] = 0.347708945732838;
   fWeightMatrix0to1[7][0] = 1.92220731528113;
   fWeightMatrix0to1[8][0] = -1.4586899506436;
   fWeightMatrix0to1[9][0] = -0.351495704548054;
   fWeightMatrix0to1[10][0] = -1.98664910463126;
   fWeightMatrix0to1[11][0] = -0.291203957141303;
   fWeightMatrix0to1[12][0] = -0.474638845696409;
   fWeightMatrix0to1[13][0] = 0.0833315698779483;
   fWeightMatrix0to1[14][0] = -0.862187892003234;
   fWeightMatrix0to1[0][1] = -0.0473558559494725;
   fWeightMatrix0to1[1][1] = -0.429898557384478;
   fWeightMatrix0to1[2][1] = 1.35260284320911;
   fWeightMatrix0to1[3][1] = 0.388249078460823;
   fWeightMatrix0to1[4][1] = 1.50463639642997;
   fWeightMatrix0to1[5][1] = -0.309224366284851;
   fWeightMatrix0to1[6][1] = -0.967466483503535;
   fWeightMatrix0to1[7][1] = 0.885964053397009;
   fWeightMatrix0to1[8][1] = -0.243767594588342;
   fWeightMatrix0to1[9][1] = -1.12949639972552;
   fWeightMatrix0to1[10][1] = -0.265658943753746;
   fWeightMatrix0to1[11][1] = 1.03797449338334;
   fWeightMatrix0to1[12][1] = -0.271933600976181;
   fWeightMatrix0to1[13][1] = -1.46215411328559;
   fWeightMatrix0to1[14][1] = 0.398835067190608;
   fWeightMatrix0to1[0][2] = 0.56574098804934;
   fWeightMatrix0to1[1][2] = 1.80460996303997;
   fWeightMatrix0to1[2][2] = -0.546380933130643;
   fWeightMatrix0to1[3][2] = 0.0402871054523707;
   fWeightMatrix0to1[4][2] = 0.283621475748243;
   fWeightMatrix0to1[5][2] = -0.0450605962221533;
   fWeightMatrix0to1[6][2] = -2.0760307705737;
   fWeightMatrix0to1[7][2] = 1.69977402860158;
   fWeightMatrix0to1[8][2] = -1.34379264521164;
   fWeightMatrix0to1[9][2] = 0.988968930424848;
   fWeightMatrix0to1[10][2] = 0.429756526448768;
   fWeightMatrix0to1[11][2] = 0.809776212551681;
   fWeightMatrix0to1[12][2] = 1.93976398988206;
   fWeightMatrix0to1[13][2] = 1.40422079793181;
   fWeightMatrix0to1[14][2] = -0.444316173521063;
   fWeightMatrix0to1[0][3] = -1.887282583388;
   fWeightMatrix0to1[1][3] = 0.861299810774255;
   fWeightMatrix0to1[2][3] = -0.0867190377555852;
   fWeightMatrix0to1[3][3] = 1.59985913286006;
   fWeightMatrix0to1[4][3] = 1.53190351758229;
   fWeightMatrix0to1[5][3] = 1.62032396345943;
   fWeightMatrix0to1[6][3] = 0.606719596898565;
   fWeightMatrix0to1[7][3] = -1.6386166605877;
   fWeightMatrix0to1[8][3] = 1.22948854662085;
   fWeightMatrix0to1[9][3] = -2.12792534998681;
   fWeightMatrix0to1[10][3] = -0.935953551870115;
   fWeightMatrix0to1[11][3] = -1.58497039147478;
   fWeightMatrix0to1[12][3] = -1.86769164073182;
   fWeightMatrix0to1[13][3] = 1.45451472686537;
   fWeightMatrix0to1[14][3] = 1.06869381798979;
   fWeightMatrix0to1[0][4] = -1.42670026938054;
   fWeightMatrix0to1[1][4] = 0.342323082920399;
   fWeightMatrix0to1[2][4] = 0.0550518446161578;
   fWeightMatrix0to1[3][4] = 0.455107855323028;
   fWeightMatrix0to1[4][4] = 1.66022552934364;
   fWeightMatrix0to1[5][4] = 0.150903531797439;
   fWeightMatrix0to1[6][4] = 0.113852480503639;
   fWeightMatrix0to1[7][4] = -1.48385815843797;
   fWeightMatrix0to1[8][4] = 0.391541399456423;
   fWeightMatrix0to1[9][4] = -0.109385307706747;
   fWeightMatrix0to1[10][4] = -0.499269080410097;
   fWeightMatrix0to1[11][4] = -0.97152221720142;
   fWeightMatrix0to1[12][4] = 0.103964979934789;
   fWeightMatrix0to1[13][4] = 0.733576156022249;
   fWeightMatrix0to1[14][4] = 1.47377497684455;
   fWeightMatrix0to1[0][5] = 0.105571839138679;
   fWeightMatrix0to1[1][5] = -1.80243824413676;
   fWeightMatrix0to1[2][5] = -1.56169429485409;
   fWeightMatrix0to1[3][5] = 0.904443906051325;
   fWeightMatrix0to1[4][5] = 0.473592624993355;
   fWeightMatrix0to1[5][5] = 1.75837675715101;
   fWeightMatrix0to1[6][5] = 0.140560547579545;
   fWeightMatrix0to1[7][5] = 0.794801059828933;
   fWeightMatrix0to1[8][5] = -0.624345970719717;
   fWeightMatrix0to1[9][5] = -1.27015076880462;
   fWeightMatrix0to1[10][5] = 0.354031854009726;
   fWeightMatrix0to1[11][5] = 0.824090209848586;
   fWeightMatrix0to1[12][5] = -0.399170225983935;
   fWeightMatrix0to1[13][5] = -1.60544227576754;
   fWeightMatrix0to1[14][5] = -1.48135597246771;
   fWeightMatrix0to1[0][6] = -0.844412945121757;
   fWeightMatrix0to1[1][6] = -0.0332669914717695;
   fWeightMatrix0to1[2][6] = 1.01018778542665;
   fWeightMatrix0to1[3][6] = -1.16064949139925;
   fWeightMatrix0to1[4][6] = -0.541984038414883;
   fWeightMatrix0to1[5][6] = 1.67444095307686;
   fWeightMatrix0to1[6][6] = -0.902056930470309;
   fWeightMatrix0to1[7][6] = -1.37807213600613;
   fWeightMatrix0to1[8][6] = -1.68598813951741;
   fWeightMatrix0to1[9][6] = 0.053044133921586;
   fWeightMatrix0to1[10][6] = -1.93103630648063;
   fWeightMatrix0to1[11][6] = -2.02865631184776;
   fWeightMatrix0to1[12][6] = 1.67721699491782;
   fWeightMatrix0to1[13][6] = 2.30003332025737;
   fWeightMatrix0to1[14][6] = -0.62158936533195;
   fWeightMatrix0to1[0][7] = 1.41007268625343;
   fWeightMatrix0to1[1][7] = -0.97127472291933;
   fWeightMatrix0to1[2][7] = -1.00027528129126;
   fWeightMatrix0to1[3][7] = 0.114064809369641;
   fWeightMatrix0to1[4][7] = 0.368716648313519;
   fWeightMatrix0to1[5][7] = -1.4992915058563;
   fWeightMatrix0to1[6][7] = 0.22050867334202;
   fWeightMatrix0to1[7][7] = 0.278369620531187;
   fWeightMatrix0to1[8][7] = 0.29905673008167;
   fWeightMatrix0to1[9][7] = -0.63233677877479;
   fWeightMatrix0to1[10][7] = 1.12878729916244;
   fWeightMatrix0to1[11][7] = 0.16432728189977;
   fWeightMatrix0to1[12][7] = -0.252076336129276;
   fWeightMatrix0to1[13][7] = 1.39079963936907;
   fWeightMatrix0to1[14][7] = -1.26626551964011;
   fWeightMatrix0to1[0][8] = -2.29700638847376;
   fWeightMatrix0to1[1][8] = 0.109978962747922;
   fWeightMatrix0to1[2][8] = -0.553998526739638;
   fWeightMatrix0to1[3][8] = 1.94163230888716;
   fWeightMatrix0to1[4][8] = 0.797683884332778;
   fWeightMatrix0to1[5][8] = 0.289910887018276;
   fWeightMatrix0to1[6][8] = -0.496763557759267;
   fWeightMatrix0to1[7][8] = 0.226895800572016;
   fWeightMatrix0to1[8][8] = -1.71279798906431;
   fWeightMatrix0to1[9][8] = 1.64145438754666;
   fWeightMatrix0to1[10][8] = -0.850519470902575;
   fWeightMatrix0to1[11][8] = -1.94911750799246;
   fWeightMatrix0to1[12][8] = 1.48806518032401;
   fWeightMatrix0to1[13][8] = -0.540716827743911;
   fWeightMatrix0to1[14][8] = 0.112532075670522;
   fWeightMatrix0to1[0][9] = 0.390811259510572;
   fWeightMatrix0to1[1][9] = 1.74734775337322;
   fWeightMatrix0to1[2][9] = -2.16072916469496;
   fWeightMatrix0to1[3][9] = 0.57320557135042;
   fWeightMatrix0to1[4][9] = 1.58830094411084;
   fWeightMatrix0to1[5][9] = 1.86291419143807;
   fWeightMatrix0to1[6][9] = 0.234380579927097;
   fWeightMatrix0to1[7][9] = -1.3542728416659;
   fWeightMatrix0to1[8][9] = -0.297594006831618;
   fWeightMatrix0to1[9][9] = -0.910225762785326;
   fWeightMatrix0to1[10][9] = 0.64872565440303;
   fWeightMatrix0to1[11][9] = 1.04800078326781;
   fWeightMatrix0to1[12][9] = 0.571766197476377;
   fWeightMatrix0to1[13][9] = 0.48053080554319;
   fWeightMatrix0to1[14][9] = 0.202478174847055;
   fWeightMatrix0to1[0][10] = -0.537945948901359;
   fWeightMatrix0to1[1][10] = 0.564839758368612;
   fWeightMatrix0to1[2][10] = 2.30058344922141;
   fWeightMatrix0to1[3][10] = -1.00991394612748;
   fWeightMatrix0to1[4][10] = -0.741114584125226;
   fWeightMatrix0to1[5][10] = 0.0344674382672171;
   fWeightMatrix0to1[6][10] = 1.21683678347893;
   fWeightMatrix0to1[7][10] = 0.451095579060004;
   fWeightMatrix0to1[8][10] = 1.41973946131193;
   fWeightMatrix0to1[9][10] = -1.76333126691226;
   fWeightMatrix0to1[10][10] = 2.49171067996411;
   fWeightMatrix0to1[11][10] = 1.14399979148368;
   fWeightMatrix0to1[12][10] = -0.80392010345838;
   fWeightMatrix0to1[13][10] = -0.292301143657685;
   fWeightMatrix0to1[14][10] = 0.760294777741851;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.0180091142878146;
   fWeightMatrix1to2[0][1] = 0.0112490945899081;
   fWeightMatrix1to2[0][2] = -0.0572281229405806;
   fWeightMatrix1to2[0][3] = -0.00604856404062582;
   fWeightMatrix1to2[0][4] = -0.0191630956539782;
   fWeightMatrix1to2[0][5] = 0.00356159637027433;
   fWeightMatrix1to2[0][6] = 1.31116918098502;
   fWeightMatrix1to2[0][7] = 0.00756491516196296;
   fWeightMatrix1to2[0][8] = 1.71875607945066;
   fWeightMatrix1to2[0][9] = -0.00606831824002989;
   fWeightMatrix1to2[0][10] = -0.384771708904536;
   fWeightMatrix1to2[0][11] = 0.0781590160632316;
   fWeightMatrix1to2[0][12] = 0.50384249247495;
   fWeightMatrix1to2[0][13] = 0.0234374878817655;
   fWeightMatrix1to2[0][14] = 0.00111976337748571;
   fWeightMatrix1to2[0][15] = -1.14428366907581;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.501860499382;
   fMax_1[0][0] = 51.7713851929;
   fMin_1[1][0] = 0.543673932552;
   fMax_1[1][0] = 47.3534812927;
   fMin_1[2][0] = 0.501860499382;
   fMax_1[2][0] = 51.7713851929;
   fMin_1[0][1] = 0.693660438061;
   fMax_1[0][1] = 56.3495254517;
   fMin_1[1][1] = 0.865977704525;
   fMax_1[1][1] = 49.8389167786;
   fMin_1[2][1] = 0.693660438061;
   fMax_1[2][1] = 56.3495254517;
   fMin_1[0][2] = 0.501416265965;
   fMax_1[0][2] = 50.7236557007;
   fMin_1[1][2] = 0.51357614994;
   fMax_1[1][2] = 47.2640914917;
   fMin_1[2][2] = 0.501416265965;
   fMax_1[2][2] = 50.7236557007;
   fMin_1[0][3] = 8.00832366943;
   fMax_1[0][3] = 58.8731307983;
   fMin_1[1][3] = 8.63385009766;
   fMax_1[1][3] = 55.84608078;
   fMin_1[2][3] = 8.00832366943;
   fMax_1[2][3] = 58.8731307983;
   fMin_1[0][4] = 0.0501119084656;
   fMax_1[0][4] = 0.999967932701;
   fMin_1[1][4] = 0.064377643168;
   fMax_1[1][4] = 0.982714831829;
   fMin_1[2][4] = 0.0501119084656;
   fMax_1[2][4] = 0.999967932701;
   fMin_1[0][5] = 0.0501329638064;
   fMax_1[0][5] = 0.999576151371;
   fMin_1[1][5] = 0.0515683032572;
   fMax_1[1][5] = 0.933959305286;
   fMin_1[2][5] = 0.0501329638064;
   fMax_1[2][5] = 0.999576151371;
   fMin_1[0][6] = 2.90316274913e-05;
   fMax_1[0][6] = 0.199643790722;
   fMin_1[1][6] = 0.00562079064548;
   fMax_1[1][6] = 0.180297493935;
   fMin_1[2][6] = 2.90316274913e-05;
   fMax_1[2][6] = 0.199643790722;
   fMin_1[0][7] = 7.98378823674e-05;
   fMax_1[0][7] = 0.199953570962;
   fMin_1[1][7] = 0.00241724262014;
   fMax_1[1][7] = 0.167199268937;
   fMin_1[2][7] = 7.98378823674e-05;
   fMax_1[2][7] = 0.199953570962;
   fMin_1[0][8] = 2.0015206337;
   fMax_1[0][8] = 587.856567383;
   fMin_1[1][8] = 2.02741146088;
   fMax_1[1][8] = 226.448287964;
   fMin_1[2][8] = 2.0015206337;
   fMax_1[2][8] = 587.856567383;
   fMin_1[0][9] = 2.010004282;
   fMax_1[0][9] = 503.130828857;
   fMin_1[1][9] = 2.11274337769;
   fMax_1[1][9] = 185.494445801;
   fMin_1[2][9] = 2.010004282;
   fMax_1[2][9] = 503.130828857;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 10;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<10;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
