// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/13       [393741]
Creator        : leure
Date           : Wed Jun  7 20:26:26 2017
Host           : Linux vocms029.cern.ch 2.6.32-504.12.2.el6.x86_64 #1 SMP Thu Mar 12 07:33:00 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /data/leure/TMVA_Luke/myTMVA
Training events: 7463
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                                                         'F'    [0.501306593418,31.7663536072]
DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                                                      'F'    [0.548754513264,35.9360046387]
DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                                                      'F'    [0.510877549648,35.5400772095]
DtktkRespt                    DtktkRespt                    DtktkRespt                    DtktkRespt                                                      'F'    [8.00182914734,39.2910881042]
Dchi2cl                       Dchi2cl                       Dchi2cl                       Dchi2cl                                                         'F'    [0.0501100495458,0.999680161476]
DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl                                                 'F'    [0.0500016920269,0.999951481819]
Dalpha                        Dalpha                        Dalpha                        Dalpha                                                          'F'    [5.61032720725e-05,0.199938639998]
DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                                                  'F'    [0.00018514196563,0.199973419309]
DsvpvDistance/DsvpvDisErr     DsvpvDistance_D_DsvpvDisErr   DsvpvDistance/DsvpvDisErr     DsvpvDistance/DsvpvDisErr                                       'F'    [2.00123548508,1084.70031738]
DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance_D_DtktkRes_svpvDisErr DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance/DtktkRes_svpvDisErr                                                   'F'    [2.00810289383,367.070739746]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Dtrk1Pt", "DRestrk1Pt", "DRestrk2Pt", "DtktkRespt", "Dchi2cl", "DtktkRes_chi2cl", "Dalpha", "DtktkRes_alpha", "DsvpvDistance/DsvpvDisErr", "DtktkRes_svpvDistance/DtktkRes_svpvDisErr" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 0.99999988079071;
      fVmin[8] = -1;
      fVmax[8] = 0.99999988079071;
      fVmin[9] = -1;
      fVmax[9] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][10];
   double fMax_1[3][10];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[16][11];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][16];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 11; fWeights[0] = new double[11]; 
   fLayerSize[1] = 16; fWeights[1] = new double[16]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -1.76708265894765;
   fWeightMatrix0to1[1][0] = 1.10190954917877;
   fWeightMatrix0to1[2][0] = 1.01408520894441;
   fWeightMatrix0to1[3][0] = 1.6079388953146;
   fWeightMatrix0to1[4][0] = -1.66140678405326;
   fWeightMatrix0to1[5][0] = -4.61778806631485;
   fWeightMatrix0to1[6][0] = -0.66092538469095;
   fWeightMatrix0to1[7][0] = 0.665200886592215;
   fWeightMatrix0to1[8][0] = -1.57365629089879;
   fWeightMatrix0to1[9][0] = 0.0922978652274017;
   fWeightMatrix0to1[10][0] = -3.00354447986823;
   fWeightMatrix0to1[11][0] = 4.35197952005248;
   fWeightMatrix0to1[12][0] = 0.234452199235389;
   fWeightMatrix0to1[13][0] = 1.10190201034027;
   fWeightMatrix0to1[14][0] = -0.0634220538937538;
   fWeightMatrix0to1[0][1] = -0.102870220632284;
   fWeightMatrix0to1[1][1] = -1.53989951884376;
   fWeightMatrix0to1[2][1] = 2.01548874235385;
   fWeightMatrix0to1[3][1] = 0.379144740476655;
   fWeightMatrix0to1[4][1] = 1.35442461863434;
   fWeightMatrix0to1[5][1] = -1.50543813599065;
   fWeightMatrix0to1[6][1] = -1.34100941377448;
   fWeightMatrix0to1[7][1] = 0.300151453424525;
   fWeightMatrix0to1[8][1] = -0.172640377622585;
   fWeightMatrix0to1[9][1] = -1.13584000266172;
   fWeightMatrix0to1[10][1] = -0.214228466607015;
   fWeightMatrix0to1[11][1] = 0.332924168661962;
   fWeightMatrix0to1[12][1] = 0.563182066613642;
   fWeightMatrix0to1[13][1] = -0.316164288960813;
   fWeightMatrix0to1[14][1] = 0.540549085057259;
   fWeightMatrix0to1[0][2] = -0.511153615080931;
   fWeightMatrix0to1[1][2] = -0.999575948385693;
   fWeightMatrix0to1[2][2] = 0.041545887050768;
   fWeightMatrix0to1[3][2] = 0.155925061458878;
   fWeightMatrix0to1[4][2] = 0.90535884294505;
   fWeightMatrix0to1[5][2] = -0.470392625477739;
   fWeightMatrix0to1[6][2] = -1.5944160559148;
   fWeightMatrix0to1[7][2] = 0.217178389523156;
   fWeightMatrix0to1[8][2] = -1.55273159497515;
   fWeightMatrix0to1[9][2] = 2.07684980598562;
   fWeightMatrix0to1[10][2] = 0.315598803198728;
   fWeightMatrix0to1[11][2] = 0.180247091155689;
   fWeightMatrix0to1[12][2] = 3.44819383586528;
   fWeightMatrix0to1[13][2] = 2.11738102155769;
   fWeightMatrix0to1[14][2] = -0.402442078757093;
   fWeightMatrix0to1[0][3] = -1.95755926677639;
   fWeightMatrix0to1[1][3] = -1.33940251074849;
   fWeightMatrix0to1[2][3] = 0.320494640932081;
   fWeightMatrix0to1[3][3] = 1.55022996278668;
   fWeightMatrix0to1[4][3] = 1.42718907582792;
   fWeightMatrix0to1[5][3] = 0.666680769559431;
   fWeightMatrix0to1[6][3] = 1.08001898452226;
   fWeightMatrix0to1[7][3] = -2.24549271851117;
   fWeightMatrix0to1[8][3] = 0.999042052472584;
   fWeightMatrix0to1[9][3] = -1.9366098506148;
   fWeightMatrix0to1[10][3] = -0.983114915839562;
   fWeightMatrix0to1[11][3] = -0.745758974085688;
   fWeightMatrix0to1[12][3] = -0.238885261526232;
   fWeightMatrix0to1[13][3] = 1.94009681463078;
   fWeightMatrix0to1[14][3] = 0.753504900931136;
   fWeightMatrix0to1[0][4] = -1.56581321181969;
   fWeightMatrix0to1[1][4] = -0.0166134586467481;
   fWeightMatrix0to1[2][4] = -0.499702419134748;
   fWeightMatrix0to1[3][4] = -0.233051961459189;
   fWeightMatrix0to1[4][4] = 0.975537971323558;
   fWeightMatrix0to1[5][4] = -0.463140225207662;
   fWeightMatrix0to1[6][4] = -0.28149178931779;
   fWeightMatrix0to1[7][4] = -0.842680037253228;
   fWeightMatrix0to1[8][4] = 0.512470447550413;
   fWeightMatrix0to1[9][4] = -0.0534625892775177;
   fWeightMatrix0to1[10][4] = -0.417810972958103;
   fWeightMatrix0to1[11][4] = 0.182004656561501;
   fWeightMatrix0to1[12][4] = 0.741249385432754;
   fWeightMatrix0to1[13][4] = 1.7385691178659;
   fWeightMatrix0to1[14][4] = 0.931336262569954;
   fWeightMatrix0to1[0][5] = -0.00155106471057867;
   fWeightMatrix0to1[1][5] = -2.08706683899973;
   fWeightMatrix0to1[2][5] = -1.73388313073018;
   fWeightMatrix0to1[3][5] = 0.519544330506657;
   fWeightMatrix0to1[4][5] = -0.41568342817783;
   fWeightMatrix0to1[5][5] = 1.03830490497396;
   fWeightMatrix0to1[6][5] = -0.337018720380395;
   fWeightMatrix0to1[7][5] = -0.620885742855163;
   fWeightMatrix0to1[8][5] = -0.481608085172735;
   fWeightMatrix0to1[9][5] = -0.160966591333205;
   fWeightMatrix0to1[10][5] = -0.362402754799396;
   fWeightMatrix0to1[11][5] = 0.00238421236932798;
   fWeightMatrix0to1[12][5] = 0.493751736515757;
   fWeightMatrix0to1[13][5] = -0.780947785466136;
   fWeightMatrix0to1[14][5] = -2.43235288230609;
   fWeightMatrix0to1[0][6] = -1.35147135687697;
   fWeightMatrix0to1[1][6] = -1.42258667504552;
   fWeightMatrix0to1[2][6] = 1.93932834727737;
   fWeightMatrix0to1[3][6] = -1.00784655844328;
   fWeightMatrix0to1[4][6] = 0.397524218028005;
   fWeightMatrix0to1[5][6] = 0.0359185736800327;
   fWeightMatrix0to1[6][6] = -1.15109489407686;
   fWeightMatrix0to1[7][6] = -0.816699403467953;
   fWeightMatrix0to1[8][6] = -1.19792619769634;
   fWeightMatrix0to1[9][6] = 0.50747444063864;
   fWeightMatrix0to1[10][6] = -1.22799741066091;
   fWeightMatrix0to1[11][6] = -0.660847852934143;
   fWeightMatrix0to1[12][6] = 0.0803360138328996;
   fWeightMatrix0to1[13][6] = 2.78897709898201;
   fWeightMatrix0to1[14][6] = -1.14161033969871;
   fWeightMatrix0to1[0][7] = 0.532667836562727;
   fWeightMatrix0to1[1][7] = -0.256418557436964;
   fWeightMatrix0to1[2][7] = -0.621887204443223;
   fWeightMatrix0to1[3][7] = -0.0265650565695312;
   fWeightMatrix0to1[4][7] = 0.790504799945952;
   fWeightMatrix0to1[5][7] = -0.949128212356555;
   fWeightMatrix0to1[6][7] = 0.432775687480926;
   fWeightMatrix0to1[7][7] = -0.897858650557181;
   fWeightMatrix0to1[8][7] = 0.110449579430873;
   fWeightMatrix0to1[9][7] = -0.286574739195506;
   fWeightMatrix0to1[10][7] = 0.832325389799113;
   fWeightMatrix0to1[11][7] = 0.281035809852435;
   fWeightMatrix0to1[12][7] = 0.232935852102614;
   fWeightMatrix0to1[13][7] = 1.13570178835101;
   fWeightMatrix0to1[14][7] = -0.0293079838011718;
   fWeightMatrix0to1[0][8] = -2.73198742525486;
   fWeightMatrix0to1[1][8] = -2.36562364974365;
   fWeightMatrix0to1[2][8] = 0.282227335215211;
   fWeightMatrix0to1[3][8] = 2.66711770194947;
   fWeightMatrix0to1[4][8] = 2.1621290733911;
   fWeightMatrix0to1[5][8] = -1.22413136454722;
   fWeightMatrix0to1[6][8] = -1.11961391759243;
   fWeightMatrix0to1[7][8] = -1.99519554268636;
   fWeightMatrix0to1[8][8] = -2.09437109573596;
   fWeightMatrix0to1[9][8] = 2.49581544521276;
   fWeightMatrix0to1[10][8] = -0.967327476878342;
   fWeightMatrix0to1[11][8] = -3.1563229887996;
   fWeightMatrix0to1[12][8] = 3.20710597685964;
   fWeightMatrix0to1[13][8] = 1.0308380969078;
   fWeightMatrix0to1[14][8] = 0.995731722000043;
   fWeightMatrix0to1[0][9] = -0.296312385908151;
   fWeightMatrix0to1[1][9] = 0.776983570929058;
   fWeightMatrix0to1[2][9] = -1.24289315441932;
   fWeightMatrix0to1[3][9] = 1.20957793389984;
   fWeightMatrix0to1[4][9] = 2.89792706463307;
   fWeightMatrix0to1[5][9] = -0.530470873474688;
   fWeightMatrix0to1[6][9] = -0.707558706405668;
   fWeightMatrix0to1[7][9] = -3.39655786705265;
   fWeightMatrix0to1[8][9] = -0.571012162087315;
   fWeightMatrix0to1[9][9] = -0.0382029993152207;
   fWeightMatrix0to1[10][9] = 0.54831714352619;
   fWeightMatrix0to1[11][9] = 2.32895687412833;
   fWeightMatrix0to1[12][9] = 2.04831575598961;
   fWeightMatrix0to1[13][9] = 1.45403111173871;
   fWeightMatrix0to1[14][9] = 1.01418133193743;
   fWeightMatrix0to1[0][10] = 1.01353158223316;
   fWeightMatrix0to1[1][10] = 3.2789723114768;
   fWeightMatrix0to1[2][10] = 1.11739044633816;
   fWeightMatrix0to1[3][10] = -1.26667014516008;
   fWeightMatrix0to1[4][10] = -1.54226379930905;
   fWeightMatrix0to1[5][10] = 1.06537879468952;
   fWeightMatrix0to1[6][10] = 1.75341706329312;
   fWeightMatrix0to1[7][10] = 2.57882688249887;
   fWeightMatrix0to1[8][10] = 1.3702894096436;
   fWeightMatrix0to1[9][10] = -3.01663755385962;
   fWeightMatrix0to1[10][10] = 2.65847602970408;
   fWeightMatrix0to1[11][10] = 4.06398120659422;
   fWeightMatrix0to1[12][10] = -2.10420044714367;
   fWeightMatrix0to1[13][10] = -2.34973310012696;
   fWeightMatrix0to1[14][10] = 0.0416086617318426;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 3.52752213530849;
   fWeightMatrix1to2[0][1] = -2.21196003522485;
   fWeightMatrix1to2[0][2] = -0.00942888087044654;
   fWeightMatrix1to2[0][3] = -0.965436200577661;
   fWeightMatrix1to2[0][4] = 4.1303031411355;
   fWeightMatrix1to2[0][5] = 0.00341309578834942;
   fWeightMatrix1to2[0][6] = -2.43399604077625;
   fWeightMatrix1to2[0][7] = 2.70707972485026;
   fWeightMatrix1to2[0][8] = 2.62731960406472;
   fWeightMatrix1to2[0][9] = 0.994430048674112;
   fWeightMatrix1to2[0][10] = 2.52829153643179;
   fWeightMatrix1to2[0][11] = 0.846497857883174;
   fWeightMatrix1to2[0][12] = -0.333534223550748;
   fWeightMatrix1to2[0][13] = 2.43727493847196;
   fWeightMatrix1to2[0][14] = 0.0119243067060245;
   fWeightMatrix1to2[0][15] = -0.312678991796639;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.502681493759;
   fMax_1[0][0] = 31.7663536072;
   fMin_1[1][0] = 0.501306593418;
   fMax_1[1][0] = 29.6347255707;
   fMin_1[2][0] = 0.501306593418;
   fMax_1[2][0] = 31.7663536072;
   fMin_1[0][1] = 0.548754513264;
   fMax_1[0][1] = 35.9360046387;
   fMin_1[1][1] = 0.580357849598;
   fMax_1[1][1] = 35.1523246765;
   fMin_1[2][1] = 0.548754513264;
   fMax_1[2][1] = 35.9360046387;
   fMin_1[0][2] = 0.510877549648;
   fMax_1[0][2] = 33.682220459;
   fMin_1[1][2] = 0.533021330833;
   fMax_1[1][2] = 35.5400772095;
   fMin_1[2][2] = 0.510877549648;
   fMax_1[2][2] = 35.5400772095;
   fMin_1[0][3] = 8.00182914734;
   fMax_1[0][3] = 38.9601364136;
   fMin_1[1][3] = 8.16422939301;
   fMax_1[1][3] = 39.2910881042;
   fMin_1[2][3] = 8.00182914734;
   fMax_1[2][3] = 39.2910881042;
   fMin_1[0][4] = 0.0501248650253;
   fMax_1[0][4] = 0.999680161476;
   fMin_1[1][4] = 0.0501100495458;
   fMax_1[1][4] = 0.992317736149;
   fMin_1[2][4] = 0.0501100495458;
   fMax_1[2][4] = 0.999680161476;
   fMin_1[0][5] = 0.0500016920269;
   fMax_1[0][5] = 0.999951481819;
   fMin_1[1][5] = 0.0513061583042;
   fMax_1[1][5] = 0.997355163097;
   fMin_1[2][5] = 0.0500016920269;
   fMax_1[2][5] = 0.999951481819;
   fMin_1[0][6] = 5.61032720725e-05;
   fMax_1[0][6] = 0.199938639998;
   fMin_1[1][6] = 0.00140371813904;
   fMax_1[1][6] = 0.199936017394;
   fMin_1[2][6] = 5.61032720725e-05;
   fMax_1[2][6] = 0.199938639998;
   fMin_1[0][7] = 0.000521093723364;
   fMax_1[0][7] = 0.199973419309;
   fMin_1[1][7] = 0.00018514196563;
   fMax_1[1][7] = 0.19325864315;
   fMin_1[2][7] = 0.00018514196563;
   fMax_1[2][7] = 0.199973419309;
   fMin_1[0][8] = 2.011957407;
   fMax_1[0][8] = 356.734375;
   fMin_1[1][8] = 2.00123548508;
   fMax_1[1][8] = 1084.70031738;
   fMin_1[2][8] = 2.00123548508;
   fMax_1[2][8] = 1084.70031738;
   fMin_1[0][9] = 2.00861668587;
   fMax_1[0][9] = 367.070739746;
   fMin_1[1][9] = 2.00810289383;
   fMax_1[1][9] = 333.46270752;
   fMin_1[2][9] = 2.00810289383;
   fMax_1[2][9] = 367.070739746;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 10;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<10;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
