// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/13       [393741]
Creator        : leure
Date           : Tue Jun  6 18:44:55 2017
Host           : Linux vocms029.cern.ch 2.6.32-504.12.2.el6.x86_64 #1 SMP Thu Mar 12 07:33:00 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /data/leure/TMVA_Luke/myTMVA
Training events: 794
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                                                         'F'    [0.508002221584,14.8648700714]
DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                                                      'F'    [0.831826388836,21.4123878479]
DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                                                      'F'    [0.568991482258,20.6765480042]
DtktkRespt                    DtktkRespt                    DtktkRespt                    DtktkRespt                                                      'F'    [8.03139591217,22.7082042694]
Dchi2cl                       Dchi2cl                       Dchi2cl                       Dchi2cl                                                         'F'    [0.0501248650253,0.999834001064]
DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl                                                 'F'    [0.0503450036049,0.99915009737]
Dalpha                        Dalpha                        Dalpha                        Dalpha                                                          'F'    [0.000402642035624,0.198835387826]
DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                                                  'F'    [0.00018514196563,0.199973419309]
DsvpvDistance/DsvpvDisErr     DsvpvDistance_D_DsvpvDisErr   DsvpvDistance/DsvpvDisErr     DsvpvDistance/DsvpvDisErr                                       'F'    [2.00809788704,212.443771362]
DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance_D_DtktkRes_svpvDisErr DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance/DtktkRes_svpvDisErr                                                   'F'    [2.02267003059,108.082206726]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Dtrk1Pt", "DRestrk1Pt", "DRestrk2Pt", "DtktkRespt", "Dchi2cl", "DtktkRes_chi2cl", "Dalpha", "DtktkRes_alpha", "DsvpvDistance/DsvpvDisErr", "DtktkRes_svpvDistance/DtktkRes_svpvDisErr" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 0.99999988079071;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 0.99999988079071;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][10];
   double fMax_1[3][10];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[16][11];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][16];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 11; fWeights[0] = new double[11]; 
   fLayerSize[1] = 16; fWeights[1] = new double[16]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.386666176442599;
   fWeightMatrix0to1[1][0] = 1.64305488871924;
   fWeightMatrix0to1[2][0] = 0.972093768041177;
   fWeightMatrix0to1[3][0] = 1.65951446135928;
   fWeightMatrix0to1[4][0] = -2.04323194603306;
   fWeightMatrix0to1[5][0] = -1.03105151285041;
   fWeightMatrix0to1[6][0] = -0.673701949383414;
   fWeightMatrix0to1[7][0] = 1.99284587088518;
   fWeightMatrix0to1[8][0] = -1.24884754875866;
   fWeightMatrix0to1[9][0] = -0.593135851424931;
   fWeightMatrix0to1[10][0] = -1.75616480954018;
   fWeightMatrix0to1[11][0] = 0.982831091508529;
   fWeightMatrix0to1[12][0] = -1.4317848456756;
   fWeightMatrix0to1[13][0] = -0.38164800051118;
   fWeightMatrix0to1[14][0] = -0.767740933731191;
   fWeightMatrix0to1[0][1] = -0.117429394780265;
   fWeightMatrix0to1[1][1] = -0.637146876713064;
   fWeightMatrix0to1[2][1] = 1.2379508153516;
   fWeightMatrix0to1[3][1] = 0.54541296163186;
   fWeightMatrix0to1[4][1] = 1.17831999061869;
   fWeightMatrix0to1[5][1] = -0.559418225131694;
   fWeightMatrix0to1[6][1] = -0.945378369842034;
   fWeightMatrix0to1[7][1] = 0.712656257941228;
   fWeightMatrix0to1[8][1] = -0.194363403716444;
   fWeightMatrix0to1[9][1] = -2.04163235730188;
   fWeightMatrix0to1[10][1] = 0.075681056138941;
   fWeightMatrix0to1[11][1] = 0.325357300900418;
   fWeightMatrix0to1[12][1] = -0.722183987627578;
   fWeightMatrix0to1[13][1] = -1.82565958857714;
   fWeightMatrix0to1[14][1] = 0.16316930503295;
   fWeightMatrix0to1[0][2] = 1.07798027370216;
   fWeightMatrix0to1[1][2] = 1.48009590107393;
   fWeightMatrix0to1[2][2] = -0.43396680269707;
   fWeightMatrix0to1[3][2] = -0.180951785122471;
   fWeightMatrix0to1[4][2] = 0.272147076865239;
   fWeightMatrix0to1[5][2] = 0.189333924818572;
   fWeightMatrix0to1[6][2] = -1.31612305313533;
   fWeightMatrix0to1[7][2] = 1.87725430976111;
   fWeightMatrix0to1[8][2] = -1.27679092016002;
   fWeightMatrix0to1[9][2] = 1.07191204874852;
   fWeightMatrix0to1[10][2] = 0.478630638052016;
   fWeightMatrix0to1[11][2] = 0.39727497366248;
   fWeightMatrix0to1[12][2] = 1.81307774399293;
   fWeightMatrix0to1[13][2] = 1.36408242346443;
   fWeightMatrix0to1[14][2] = -0.902808834301085;
   fWeightMatrix0to1[0][3] = -1.76551311142607;
   fWeightMatrix0to1[1][3] = 0.937756268332767;
   fWeightMatrix0to1[2][3] = -0.0359417833367487;
   fWeightMatrix0to1[3][3] = 1.56362960810735;
   fWeightMatrix0to1[4][3] = 1.46145396694125;
   fWeightMatrix0to1[5][3] = 1.35604170818808;
   fWeightMatrix0to1[6][3] = 1.13257779272914;
   fWeightMatrix0to1[7][3] = -1.6334332890664;
   fWeightMatrix0to1[8][3] = 1.14467356815731;
   fWeightMatrix0to1[9][3] = -2.26251446201251;
   fWeightMatrix0to1[10][3] = -0.932397636262951;
   fWeightMatrix0to1[11][3] = -1.96462771110186;
   fWeightMatrix0to1[12][3] = -1.55726923079012;
   fWeightMatrix0to1[13][3] = 1.54843077501968;
   fWeightMatrix0to1[14][3] = 0.617911483114712;
   fWeightMatrix0to1[0][4] = -1.10704568905676;
   fWeightMatrix0to1[1][4] = 0.338745778841708;
   fWeightMatrix0to1[2][4] = -0.316435602806402;
   fWeightMatrix0to1[3][4] = 0.748113461573857;
   fWeightMatrix0to1[4][4] = 1.88993950054388;
   fWeightMatrix0to1[5][4] = -0.497267592899219;
   fWeightMatrix0to1[6][4] = -0.394818711283718;
   fWeightMatrix0to1[7][4] = -0.936409893565412;
   fWeightMatrix0to1[8][4] = 0.115327330434305;
   fWeightMatrix0to1[9][4] = -0.643682871823326;
   fWeightMatrix0to1[10][4] = -0.257167223729697;
   fWeightMatrix0to1[11][4] = -0.0664066365787677;
   fWeightMatrix0to1[12][4] = 1.1173393752634;
   fWeightMatrix0to1[13][4] = 0.983591844875585;
   fWeightMatrix0to1[14][4] = 1.58396588440729;
   fWeightMatrix0to1[0][5] = -0.150937415658051;
   fWeightMatrix0to1[1][5] = -1.95247704670263;
   fWeightMatrix0to1[2][5] = -1.5357432467125;
   fWeightMatrix0to1[3][5] = 0.678985003797956;
   fWeightMatrix0to1[4][5] = 0.669952395468587;
   fWeightMatrix0to1[5][5] = 1.9694750795987;
   fWeightMatrix0to1[6][5] = 0.278838199393932;
   fWeightMatrix0to1[7][5] = 1.18442392616353;
   fWeightMatrix0to1[8][5] = -0.812329644124313;
   fWeightMatrix0to1[9][5] = -0.0414103498244966;
   fWeightMatrix0to1[10][5] = 0.374558375780859;
   fWeightMatrix0to1[11][5] = 0.295512484377345;
   fWeightMatrix0to1[12][5] = -0.818015820765349;
   fWeightMatrix0to1[13][5] = -1.7476525359266;
   fWeightMatrix0to1[14][5] = -1.55982653004021;
   fWeightMatrix0to1[0][6] = -0.682586976854089;
   fWeightMatrix0to1[1][6] = -0.271011604565706;
   fWeightMatrix0to1[2][6] = 0.916931498661433;
   fWeightMatrix0to1[3][6] = -1.16674529533612;
   fWeightMatrix0to1[4][6] = -0.96299832438647;
   fWeightMatrix0to1[5][6] = 1.62034007487622;
   fWeightMatrix0to1[6][6] = -0.445308872466023;
   fWeightMatrix0to1[7][6] = -1.44429285862123;
   fWeightMatrix0to1[8][6] = -1.31092477191289;
   fWeightMatrix0to1[9][6] = -0.862662805704711;
   fWeightMatrix0to1[10][6] = -2.2244317627635;
   fWeightMatrix0to1[11][6] = -0.905431452193511;
   fWeightMatrix0to1[12][6] = 1.13893675660446;
   fWeightMatrix0to1[13][6] = 1.72985079713801;
   fWeightMatrix0to1[14][6] = -0.763197809427604;
   fWeightMatrix0to1[0][7] = 1.68864339554092;
   fWeightMatrix0to1[1][7] = -1.23974685469543;
   fWeightMatrix0to1[2][7] = -0.983126584230175;
   fWeightMatrix0to1[3][7] = 0.121823593326786;
   fWeightMatrix0to1[4][7] = 0.197852210334246;
   fWeightMatrix0to1[5][7] = -1.46791432416759;
   fWeightMatrix0to1[6][7] = 0.823660055186745;
   fWeightMatrix0to1[7][7] = 0.508220492158379;
   fWeightMatrix0to1[8][7] = 0.49324498555224;
   fWeightMatrix0to1[9][7] = -1.63148586264914;
   fWeightMatrix0to1[10][7] = 1.31425552794911;
   fWeightMatrix0to1[11][7] = 0.415721723359229;
   fWeightMatrix0to1[12][7] = -0.61292421963183;
   fWeightMatrix0to1[13][7] = 0.947369422144594;
   fWeightMatrix0to1[14][7] = -1.19086990701938;
   fWeightMatrix0to1[0][8] = -2.09456205510893;
   fWeightMatrix0to1[1][8] = -0.560966413710599;
   fWeightMatrix0to1[2][8] = -0.921569754541306;
   fWeightMatrix0to1[3][8] = 2.24166188497426;
   fWeightMatrix0to1[4][8] = 0.51701321926018;
   fWeightMatrix0to1[5][8] = 0.43626575211538;
   fWeightMatrix0to1[6][8] = -0.276705679291526;
   fWeightMatrix0to1[7][8] = 0.439260549361508;
   fWeightMatrix0to1[8][8] = -2.07857628281073;
   fWeightMatrix0to1[9][8] = 0.358420038297163;
   fWeightMatrix0to1[10][8] = -0.528057886272823;
   fWeightMatrix0to1[11][8] = -1.80139017714868;
   fWeightMatrix0to1[12][8] = 1.03497671538447;
   fWeightMatrix0to1[13][8] = -1.14595997682924;
   fWeightMatrix0to1[14][8] = -0.135679671262554;
   fWeightMatrix0to1[0][9] = 0.412390486424931;
   fWeightMatrix0to1[1][9] = 1.22588442932578;
   fWeightMatrix0to1[2][9] = -2.41856990935241;
   fWeightMatrix0to1[3][9] = 0.825821948234187;
   fWeightMatrix0to1[4][9] = 1.26509341539659;
   fWeightMatrix0to1[5][9] = 1.9097656319347;
   fWeightMatrix0to1[6][9] = 0.0996409083680887;
   fWeightMatrix0to1[7][9] = -1.18152718949861;
   fWeightMatrix0to1[8][9] = -0.560509377688134;
   fWeightMatrix0to1[9][9] = -2.14541190088013;
   fWeightMatrix0to1[10][9] = 0.987909082580173;
   fWeightMatrix0to1[11][9] = 2.32280902927257;
   fWeightMatrix0to1[12][9] = -0.172162133324774;
   fWeightMatrix0to1[13][9] = -0.141929334097065;
   fWeightMatrix0to1[14][9] = -0.0432859197318328;
   fWeightMatrix0to1[0][10] = -0.834167411279526;
   fWeightMatrix0to1[1][10] = 1.4446787473796;
   fWeightMatrix0to1[2][10] = 2.57368719739039;
   fWeightMatrix0to1[3][10] = -1.11063107232967;
   fWeightMatrix0to1[4][10] = -0.333469959412885;
   fWeightMatrix0to1[5][10] = -0.326044300708459;
   fWeightMatrix0to1[6][10] = 0.92483101278388;
   fWeightMatrix0to1[7][10] = 0.432952090038696;
   fWeightMatrix0to1[8][10] = 1.28688189340168;
   fWeightMatrix0to1[9][10] = -0.507071649506981;
   fWeightMatrix0to1[10][10] = 2.15437746879761;
   fWeightMatrix0to1[11][10] = 2.70114412537401;
   fWeightMatrix0to1[12][10] = 0.246095470338167;
   fWeightMatrix0to1[13][10] = 0.285368398265511;
   fWeightMatrix0to1[14][10] = 1.12912064314239;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.135076064081329;
   fWeightMatrix1to2[0][1] = 0.069912075332577;
   fWeightMatrix1to2[0][2] = -0.00428831644512653;
   fWeightMatrix1to2[0][3] = -0.115686805655311;
   fWeightMatrix1to2[0][4] = -0.0456691520324834;
   fWeightMatrix1to2[0][5] = -0.0470429252180047;
   fWeightMatrix1to2[0][6] = 0.833007205706831;
   fWeightMatrix1to2[0][7] = 0.0893368352701955;
   fWeightMatrix1to2[0][8] = 1.25389266555464;
   fWeightMatrix1to2[0][9] = -0.111027165053736;
   fWeightMatrix1to2[0][10] = -0.24663664603302;
   fWeightMatrix1to2[0][11] = 0.673438936464813;
   fWeightMatrix1to2[0][12] = 0.143226586099748;
   fWeightMatrix1to2[0][13] = -0.0456015009274183;
   fWeightMatrix1to2[0][14] = -0.0443429557845919;
   fWeightMatrix1to2[0][15] = -1.4296593594515;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.508002221584;
   fMax_1[0][0] = 14.8648700714;
   fMin_1[1][0] = 0.511792123318;
   fMax_1[1][0] = 4.04023694992;
   fMin_1[2][0] = 0.508002221584;
   fMax_1[2][0] = 14.8648700714;
   fMin_1[0][1] = 0.831826388836;
   fMax_1[0][1] = 20.0820999146;
   fMin_1[1][1] = 1.32190299034;
   fMax_1[1][1] = 21.4123878479;
   fMin_1[2][1] = 0.831826388836;
   fMax_1[2][1] = 21.4123878479;
   fMin_1[0][2] = 0.568991482258;
   fMax_1[0][2] = 20.6765480042;
   fMin_1[1][2] = 0.651882708073;
   fMax_1[1][2] = 19.7634506226;
   fMin_1[2][2] = 0.568991482258;
   fMax_1[2][2] = 20.6765480042;
   fMin_1[0][3] = 8.03139591217;
   fMax_1[0][3] = 22.7082042694;
   fMin_1[1][3] = 16.1138820648;
   fMax_1[1][3] = 22.5870609283;
   fMin_1[2][3] = 8.03139591217;
   fMax_1[2][3] = 22.7082042694;
   fMin_1[0][4] = 0.0501248650253;
   fMax_1[0][4] = 0.999834001064;
   fMin_1[1][4] = 0.0506580136716;
   fMax_1[1][4] = 0.984503746033;
   fMin_1[2][4] = 0.0501248650253;
   fMax_1[2][4] = 0.999834001064;
   fMin_1[0][5] = 0.0503450036049;
   fMax_1[0][5] = 0.99915009737;
   fMin_1[1][5] = 0.0554051734507;
   fMax_1[1][5] = 0.979975402355;
   fMin_1[2][5] = 0.0503450036049;
   fMax_1[2][5] = 0.99915009737;
   fMin_1[0][6] = 0.000402642035624;
   fMax_1[0][6] = 0.198835387826;
   fMin_1[1][6] = 0.00902860984206;
   fMax_1[1][6] = 0.191456958652;
   fMin_1[2][6] = 0.000402642035624;
   fMax_1[2][6] = 0.198835387826;
   fMin_1[0][7] = 0.00155728287064;
   fMax_1[0][7] = 0.199973419309;
   fMin_1[1][7] = 0.00018514196563;
   fMax_1[1][7] = 0.186899185181;
   fMin_1[2][7] = 0.00018514196563;
   fMax_1[2][7] = 0.199973419309;
   fMin_1[0][8] = 2.08111000061;
   fMax_1[0][8] = 212.443771362;
   fMin_1[1][8] = 2.00809788704;
   fMax_1[1][8] = 103.659118652;
   fMin_1[2][8] = 2.00809788704;
   fMax_1[2][8] = 212.443771362;
   fMin_1[0][9] = 2.1032063961;
   fMax_1[0][9] = 108.082206726;
   fMin_1[1][9] = 2.02267003059;
   fMax_1[1][9] = 28.8328113556;
   fMin_1[2][9] = 2.02267003059;
   fMax_1[2][9] = 108.082206726;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 10;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<10;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
