// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/13       [393741]
Creator        : leure
Date           : Tue Jun  6 17:36:33 2017
Host           : Linux vocms029.cern.ch 2.6.32-504.12.2.el6.x86_64 #1 SMP Thu Mar 12 07:33:00 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /data/leure/TMVA_Luke/myTMVA
Training events: 1850
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                                                         'F'    [0.504267275333,21.5219936371]
DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                                                      'F'    [0.611003220081,26.4953784943]
DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                                                      'F'    [0.501210987568,27.0570068359]
DtktkRespt                    DtktkRespt                    DtktkRespt                    DtktkRespt                                                      'F'    [8.00263690948,29.6220283508]
Dchi2cl                       Dchi2cl                       Dchi2cl                       Dchi2cl                                                         'F'    [0.0501793064177,0.999834001064]
DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl                                                 'F'    [0.0503450036049,0.999778449535]
Dalpha                        Dalpha                        Dalpha                        Dalpha                                                          'F'    [0.000363119848771,0.199936017394]
DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                                                  'F'    [0.000838859472424,0.199973419309]
DsvpvDistance/DsvpvDisErr     DsvpvDistance_D_DsvpvDisErr   DsvpvDistance/DsvpvDisErr     DsvpvDistance/DsvpvDisErr                                       'F'    [2.00269937515,350.292114258]
DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance_D_DtktkRes_svpvDisErr DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance/DtktkRes_svpvDisErr                                                   'F'    [2.00757074356,148.390914917]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Dtrk1Pt", "DRestrk1Pt", "DRestrk2Pt", "DtktkRespt", "Dchi2cl", "DtktkRes_chi2cl", "Dalpha", "DtktkRes_alpha", "DsvpvDistance/DsvpvDisErr", "DtktkRes_svpvDistance/DtktkRes_svpvDisErr" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][10];
   double fMax_1[3][10];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[16][11];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][16];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 11; fWeights[0] = new double[11]; 
   fLayerSize[1] = 16; fWeights[1] = new double[16]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -1.0120189737225;
   fWeightMatrix0to1[1][0] = 1.67402775106446;
   fWeightMatrix0to1[2][0] = 0.843701336422807;
   fWeightMatrix0to1[3][0] = 1.63766229832309;
   fWeightMatrix0to1[4][0] = -2.04032308165249;
   fWeightMatrix0to1[5][0] = -1.57140387725552;
   fWeightMatrix0to1[6][0] = -1.04697401946719;
   fWeightMatrix0to1[7][0] = 3.01201680236747;
   fWeightMatrix0to1[8][0] = -1.55791814491795;
   fWeightMatrix0to1[9][0] = -0.639891784966638;
   fWeightMatrix0to1[10][0] = -1.5568430829766;
   fWeightMatrix0to1[11][0] = -0.667261925715835;
   fWeightMatrix0to1[12][0] = -1.05191530101748;
   fWeightMatrix0to1[13][0] = -0.161115950797071;
   fWeightMatrix0to1[14][0] = -0.663141875617179;
   fWeightMatrix0to1[0][1] = 0.538577649390008;
   fWeightMatrix0to1[1][1] = -0.416412280916128;
   fWeightMatrix0to1[2][1] = 1.65515730293244;
   fWeightMatrix0to1[3][1] = 0.400040755934777;
   fWeightMatrix0to1[4][1] = 0.829698804251575;
   fWeightMatrix0to1[5][1] = 0.10624829652869;
   fWeightMatrix0to1[6][1] = -0.778549627637406;
   fWeightMatrix0to1[7][1] = 0.40644187249414;
   fWeightMatrix0to1[8][1] = -0.219231330808627;
   fWeightMatrix0to1[9][1] = -1.15677831196834;
   fWeightMatrix0to1[10][1] = 0.373264472496506;
   fWeightMatrix0to1[11][1] = 1.16925270367541;
   fWeightMatrix0to1[12][1] = -0.609863673161676;
   fWeightMatrix0to1[13][1] = -1.72137956968704;
   fWeightMatrix0to1[14][1] = -0.173038528255882;
   fWeightMatrix0to1[0][2] = 0.577111081376869;
   fWeightMatrix0to1[1][2] = 1.52485775452728;
   fWeightMatrix0to1[2][2] = -0.519810245188686;
   fWeightMatrix0to1[3][2] = -0.0787338212133507;
   fWeightMatrix0to1[4][2] = 0.760587601312959;
   fWeightMatrix0to1[5][2] = 0.308684092880752;
   fWeightMatrix0to1[6][2] = -1.75681560820138;
   fWeightMatrix0to1[7][2] = 0.367943111715706;
   fWeightMatrix0to1[8][2] = -1.40302908802274;
   fWeightMatrix0to1[9][2] = 0.647248081027166;
   fWeightMatrix0to1[10][2] = 0.528453372831613;
   fWeightMatrix0to1[11][2] = 0.987123195320461;
   fWeightMatrix0to1[12][2] = 2.06217263992418;
   fWeightMatrix0to1[13][2] = 1.30363013535864;
   fWeightMatrix0to1[14][2] = -0.980117567196461;
   fWeightMatrix0to1[0][3] = -1.39776954075789;
   fWeightMatrix0to1[1][3] = 0.820556613904649;
   fWeightMatrix0to1[2][3] = -0.0608048314807711;
   fWeightMatrix0to1[3][3] = 1.65692934773993;
   fWeightMatrix0to1[4][3] = 1.56995578543035;
   fWeightMatrix0to1[5][3] = 1.64663422470949;
   fWeightMatrix0to1[6][3] = 1.00688991042742;
   fWeightMatrix0to1[7][3] = -1.06882713715341;
   fWeightMatrix0to1[8][3] = 0.818195608363966;
   fWeightMatrix0to1[9][3] = -2.19933690204482;
   fWeightMatrix0to1[10][3] = -0.781491133265997;
   fWeightMatrix0to1[11][3] = -1.18278215129096;
   fWeightMatrix0to1[12][3] = -1.56891923096554;
   fWeightMatrix0to1[13][3] = 1.48357814143385;
   fWeightMatrix0to1[14][3] = 0.472917843673921;
   fWeightMatrix0to1[0][4] = -1.6176968936806;
   fWeightMatrix0to1[1][4] = 0.306729759451741;
   fWeightMatrix0to1[2][4] = 0.0100884073183715;
   fWeightMatrix0to1[3][4] = 0.637864961072511;
   fWeightMatrix0to1[4][4] = 0.431121871254677;
   fWeightMatrix0to1[5][4] = -0.164457738195419;
   fWeightMatrix0to1[6][4] = -0.0197924928712483;
   fWeightMatrix0to1[7][4] = 0.052740389383008;
   fWeightMatrix0to1[8][4] = 0.409013194238442;
   fWeightMatrix0to1[9][4] = 0.0745698666444079;
   fWeightMatrix0to1[10][4] = -0.376313301624654;
   fWeightMatrix0to1[11][4] = -0.892199217084666;
   fWeightMatrix0to1[12][4] = 0.298444435518832;
   fWeightMatrix0to1[13][4] = 1.15111067228822;
   fWeightMatrix0to1[14][4] = 0.865124151042591;
   fWeightMatrix0to1[0][5] = -0.21791069417392;
   fWeightMatrix0to1[1][5] = -1.92379855111699;
   fWeightMatrix0to1[2][5] = -1.75721884912897;
   fWeightMatrix0to1[3][5] = 0.955307068223977;
   fWeightMatrix0to1[4][5] = 0.435491655754087;
   fWeightMatrix0to1[5][5] = 0.451919173229092;
   fWeightMatrix0to1[6][5] = 0.373118788931463;
   fWeightMatrix0to1[7][5] = -0.0661972238926933;
   fWeightMatrix0to1[8][5] = -0.274617776712453;
   fWeightMatrix0to1[9][5] = -1.31841085883617;
   fWeightMatrix0to1[10][5] = -0.575124602596925;
   fWeightMatrix0to1[11][5] = 1.05019150312089;
   fWeightMatrix0to1[12][5] = -1.1060438070007;
   fWeightMatrix0to1[13][5] = -1.71577087479793;
   fWeightMatrix0to1[14][5] = -1.32319511043377;
   fWeightMatrix0to1[0][6] = -0.356636720782131;
   fWeightMatrix0to1[1][6] = 0.0235607654495267;
   fWeightMatrix0to1[2][6] = 1.30788695201056;
   fWeightMatrix0to1[3][6] = -1.2928097891925;
   fWeightMatrix0to1[4][6] = -0.844692416457299;
   fWeightMatrix0to1[5][6] = 1.97375748710726;
   fWeightMatrix0to1[6][6] = -0.852560656264541;
   fWeightMatrix0to1[7][6] = -0.901179285222124;
   fWeightMatrix0to1[8][6] = -2.10941918787836;
   fWeightMatrix0to1[9][6] = -0.54327861426406;
   fWeightMatrix0to1[10][6] = -2.0115323932361;
   fWeightMatrix0to1[11][6] = -2.18865726582511;
   fWeightMatrix0to1[12][6] = 1.15191521314061;
   fWeightMatrix0to1[13][6] = 1.75419621691981;
   fWeightMatrix0to1[14][6] = -0.918413038351383;
   fWeightMatrix0to1[0][7] = 1.04784275785535;
   fWeightMatrix0to1[1][7] = -1.21629392928959;
   fWeightMatrix0to1[2][7] = -0.67086916646129;
   fWeightMatrix0to1[3][7] = -0.1258325204653;
   fWeightMatrix0to1[4][7] = 0.0143433109775901;
   fWeightMatrix0to1[5][7] = -1.81490435401131;
   fWeightMatrix0to1[6][7] = 0.275755564807568;
   fWeightMatrix0to1[7][7] = 1.20995664117558;
   fWeightMatrix0to1[8][7] = -0.356644928100401;
   fWeightMatrix0to1[9][7] = -0.877499925929054;
   fWeightMatrix0to1[10][7] = 1.80027675596826;
   fWeightMatrix0to1[11][7] = 0.3250329318514;
   fWeightMatrix0to1[12][7] = -0.916560829056836;
   fWeightMatrix0to1[13][7] = 1.05869476528667;
   fWeightMatrix0to1[14][7] = -0.956997338664614;
   fWeightMatrix0to1[0][8] = -2.3066259310322;
   fWeightMatrix0to1[1][8] = -0.118513952751953;
   fWeightMatrix0to1[2][8] = -0.474763395195489;
   fWeightMatrix0to1[3][8] = 1.93841443785593;
   fWeightMatrix0to1[4][8] = 0.820854703455866;
   fWeightMatrix0to1[5][8] = 0.930083917560916;
   fWeightMatrix0to1[6][8] = -0.412789462906155;
   fWeightMatrix0to1[7][8] = -0.696046376155909;
   fWeightMatrix0to1[8][8] = -1.60286541627496;
   fWeightMatrix0to1[9][8] = 1.07071582696122;
   fWeightMatrix0to1[10][8] = -0.242976358155966;
   fWeightMatrix0to1[11][8] = -2.20030696233255;
   fWeightMatrix0to1[12][8] = 1.17697992665547;
   fWeightMatrix0to1[13][8] = -1.01693347525671;
   fWeightMatrix0to1[14][8] = -0.607462746852369;
   fWeightMatrix0to1[0][9] = 0.437124272868381;
   fWeightMatrix0to1[1][9] = 1.59451278132386;
   fWeightMatrix0to1[2][9] = -1.99340541748592;
   fWeightMatrix0to1[3][9] = 0.426331623484808;
   fWeightMatrix0to1[4][9] = 1.93449995364924;
   fWeightMatrix0to1[5][9] = 1.6143715314126;
   fWeightMatrix0to1[6][9] = 0.0662110090001281;
   fWeightMatrix0to1[7][9] = 0.425189082971281;
   fWeightMatrix0to1[8][9] = -0.0472099955635617;
   fWeightMatrix0to1[9][9] = -1.29864964179538;
   fWeightMatrix0to1[10][9] = 1.12008019550686;
   fWeightMatrix0to1[11][9] = 0.83335319274458;
   fWeightMatrix0to1[12][9] = -0.180291980725349;
   fWeightMatrix0to1[13][9] = -0.0229590756399704;
   fWeightMatrix0to1[14][9] = -0.551040390173785;
   fWeightMatrix0to1[0][10] = -0.667223241339673;
   fWeightMatrix0to1[1][10] = 0.880377288879595;
   fWeightMatrix0to1[2][10] = 1.96920552643035;
   fWeightMatrix0to1[3][10] = -0.88021418896939;
   fWeightMatrix0to1[4][10] = -0.460737534001633;
   fWeightMatrix0to1[5][10] = -1.19330052460589;
   fWeightMatrix0to1[6][10] = 1.15760753117712;
   fWeightMatrix0to1[7][10] = 3.92990799258123;
   fWeightMatrix0to1[8][10] = 1.05642621553965;
   fWeightMatrix0to1[9][10] = -1.25281196986397;
   fWeightMatrix0to1[10][10] = 1.83786004128075;
   fWeightMatrix0to1[11][10] = 1.26410504701262;
   fWeightMatrix0to1[12][10] = -0.270131721668664;
   fWeightMatrix0to1[13][10] = 0.151677888504611;
   fWeightMatrix0to1[14][10] = 1.57933342541695;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.0118294590795154;
   fWeightMatrix1to2[0][1] = -0.00597850635307438;
   fWeightMatrix1to2[0][2] = 0.032621424380286;
   fWeightMatrix1to2[0][3] = -0.214487411976347;
   fWeightMatrix1to2[0][4] = 0.108779575738506;
   fWeightMatrix1to2[0][5] = 0.554934833686629;
   fWeightMatrix1to2[0][6] = 0.780453334857747;
   fWeightMatrix1to2[0][7] = 1.25960114236505;
   fWeightMatrix1to2[0][8] = 1.31489339256538;
   fWeightMatrix1to2[0][9] = -0.00168544984226413;
   fWeightMatrix1to2[0][10] = -0.0211203800307691;
   fWeightMatrix1to2[0][11] = 0.0299052567037701;
   fWeightMatrix1to2[0][12] = 0.0112714554606224;
   fWeightMatrix1to2[0][13] = 0.00016718774110584;
   fWeightMatrix1to2[0][14] = -0.25656186440213;
   fWeightMatrix1to2[0][15] = -1.66000793554993;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.504267275333;
   fMax_1[0][0] = 21.5219936371;
   fMin_1[1][0] = 0.5099375844;
   fMax_1[1][0] = 15.1881942749;
   fMin_1[2][0] = 0.504267275333;
   fMax_1[2][0] = 21.5219936371;
   fMin_1[0][1] = 0.611003220081;
   fMax_1[0][1] = 26.2503547668;
   fMin_1[1][1] = 0.626341223717;
   fMax_1[1][1] = 26.4953784943;
   fMin_1[2][1] = 0.611003220081;
   fMax_1[2][1] = 26.4953784943;
   fMin_1[0][2] = 0.501210987568;
   fMax_1[0][2] = 25.5106601715;
   fMin_1[1][2] = 0.63560461998;
   fMax_1[1][2] = 27.0570068359;
   fMin_1[2][2] = 0.501210987568;
   fMax_1[2][2] = 27.0570068359;
   fMin_1[0][3] = 8.00263690948;
   fMax_1[0][3] = 28.2969665527;
   fMin_1[1][3] = 9.19473171234;
   fMax_1[1][3] = 29.6220283508;
   fMin_1[2][3] = 8.00263690948;
   fMax_1[2][3] = 29.6220283508;
   fMin_1[0][4] = 0.0501793064177;
   fMax_1[0][4] = 0.999834001064;
   fMin_1[1][4] = 0.0506580136716;
   fMax_1[1][4] = 0.985746324062;
   fMin_1[2][4] = 0.0501793064177;
   fMax_1[2][4] = 0.999834001064;
   fMin_1[0][5] = 0.0503450036049;
   fMax_1[0][5] = 0.999778449535;
   fMin_1[1][5] = 0.0513061583042;
   fMax_1[1][5] = 0.997355163097;
   fMin_1[2][5] = 0.0503450036049;
   fMax_1[2][5] = 0.999778449535;
   fMin_1[0][6] = 0.000363119848771;
   fMax_1[0][6] = 0.192721143365;
   fMin_1[1][6] = 0.00345219043083;
   fMax_1[1][6] = 0.199936017394;
   fMin_1[2][6] = 0.000363119848771;
   fMax_1[2][6] = 0.199936017394;
   fMin_1[0][7] = 0.00172958220355;
   fMax_1[0][7] = 0.199973419309;
   fMin_1[1][7] = 0.000838859472424;
   fMax_1[1][7] = 0.186899185181;
   fMin_1[2][7] = 0.000838859472424;
   fMax_1[2][7] = 0.199973419309;
   fMin_1[0][8] = 2.03125858307;
   fMax_1[0][8] = 350.292114258;
   fMin_1[1][8] = 2.00269937515;
   fMax_1[1][8] = 177.802001953;
   fMin_1[2][8] = 2.00269937515;
   fMax_1[2][8] = 350.292114258;
   fMin_1[0][9] = 2.00757074356;
   fMax_1[0][9] = 148.390914917;
   fMin_1[1][9] = 2.01058912277;
   fMax_1[1][9] = 31.8414821625;
   fMin_1[2][9] = 2.00757074356;
   fMax_1[2][9] = 148.390914917;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 10;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<10;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
