// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/13       [393741]
Creator        : leure
Date           : Mon Jun 26 17:58:55 2017
Host           : Linux vocms029.cern.ch 2.6.32-504.12.2.el6.x86_64 #1 SMP Thu Mar 12 07:33:00 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /data/leure/TMVA_Luke/myTMVA
Training events: 2336
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                                                         'F'    [0.501306593418,21.5219936371]
DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                                                      'F'    [0.611003220081,26.909122467]
DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                                                      'F'    [0.501210987568,25.7579021454]
DtktkRespt                    DtktkRespt                    DtktkRespt                    DtktkRespt                                                      'F'    [8.01282119751,29.5177097321]
Dchi2cl                       Dchi2cl                       Dchi2cl                       Dchi2cl                                                         'F'    [0.0503599233925,0.999834001064]
DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl                                                 'F'    [0.0503450036049,0.999168813229]
Dalpha                        Dalpha                        Dalpha                        Dalpha                                                          'F'    [0.000574055884499,0.198835387826]
DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                                                  'F'    [0.000838859472424,0.199973419309]
DsvpvDistance/DsvpvDisErr     DsvpvDistance_D_DsvpvDisErr   DsvpvDistance/DsvpvDisErr     DsvpvDistance/DsvpvDisErr                                       'F'    [2.00123548508,2133.9609375]
DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance_D_DtktkRes_svpvDisErr DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance/DtktkRes_svpvDisErr                                                   'F'    [2.00757074356,333.46270752]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Dtrk1Pt", "DRestrk1Pt", "DRestrk2Pt", "DtktkRespt", "Dchi2cl", "DtktkRes_chi2cl", "Dalpha", "DtktkRes_alpha", "DsvpvDistance/DsvpvDisErr", "DtktkRes_svpvDistance/DtktkRes_svpvDisErr" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 0.99999988079071;
      fVmin[9] = -1;
      fVmax[9] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][10];
   double fMax_1[3][10];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[16][11];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][16];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 11; fWeights[0] = new double[11]; 
   fLayerSize[1] = 16; fWeights[1] = new double[16]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.51997090077765;
   fWeightMatrix0to1[1][0] = 1.65518979659167;
   fWeightMatrix0to1[2][0] = 0.875768311217083;
   fWeightMatrix0to1[3][0] = 1.70332367665589;
   fWeightMatrix0to1[4][0] = -1.69043281469375;
   fWeightMatrix0to1[5][0] = -1.44324443004772;
   fWeightMatrix0to1[6][0] = -1.03273068415807;
   fWeightMatrix0to1[7][0] = 4.71065864916145;
   fWeightMatrix0to1[8][0] = -1.59905498508088;
   fWeightMatrix0to1[9][0] = -1.78195300324428;
   fWeightMatrix0to1[10][0] = -0.614550897566746;
   fWeightMatrix0to1[11][0] = -0.374146754792412;
   fWeightMatrix0to1[12][0] = -0.960502342111903;
   fWeightMatrix0to1[13][0] = -0.274830394879444;
   fWeightMatrix0to1[14][0] = -0.0378813855288919;
   fWeightMatrix0to1[0][1] = 0.804490746393949;
   fWeightMatrix0to1[1][1] = -0.896942848683791;
   fWeightMatrix0to1[2][1] = 1.6225262412511;
   fWeightMatrix0to1[3][1] = 0.494388609319686;
   fWeightMatrix0to1[4][1] = 1.23996009890535;
   fWeightMatrix0to1[5][1] = 0.998188146047847;
   fWeightMatrix0to1[6][1] = -0.915642033802178;
   fWeightMatrix0to1[7][1] = 0.506449325883971;
   fWeightMatrix0to1[8][1] = -0.420927929445475;
   fWeightMatrix0to1[9][1] = -1.09383008697981;
   fWeightMatrix0to1[10][1] = -0.622688696592129;
   fWeightMatrix0to1[11][1] = 1.27177846720834;
   fWeightMatrix0to1[12][1] = -0.984802136719898;
   fWeightMatrix0to1[13][1] = -1.99580278244587;
   fWeightMatrix0to1[14][1] = -0.17229518461591;
   fWeightMatrix0to1[0][2] = 1.08866418164462;
   fWeightMatrix0to1[1][2] = 1.25543363051946;
   fWeightMatrix0to1[2][2] = -0.490710795224447;
   fWeightMatrix0to1[3][2] = -0.150115263562734;
   fWeightMatrix0to1[4][2] = 0.489841889042868;
   fWeightMatrix0to1[5][2] = -0.926010029809457;
   fWeightMatrix0to1[6][2] = -1.60721517175911;
   fWeightMatrix0to1[7][2] = 0.437594664358083;
   fWeightMatrix0to1[8][2] = -1.25710532648175;
   fWeightMatrix0to1[9][2] = 0.595038773430855;
   fWeightMatrix0to1[10][2] = 0.744959556272461;
   fWeightMatrix0to1[11][2] = 0.780124608419069;
   fWeightMatrix0to1[12][2] = 0.854129619271928;
   fWeightMatrix0to1[13][2] = 0.872653117380465;
   fWeightMatrix0to1[14][2] = -1.1900909015539;
   fWeightMatrix0to1[0][3] = -1.23293235599771;
   fWeightMatrix0to1[1][3] = 0.414571339125414;
   fWeightMatrix0to1[2][3] = -0.0648459129670072;
   fWeightMatrix0to1[3][3] = 1.66476364967544;
   fWeightMatrix0to1[4][3] = 1.4051373791214;
   fWeightMatrix0to1[5][3] = 1.79509334247339;
   fWeightMatrix0to1[6][3] = 0.970181966777059;
   fWeightMatrix0to1[7][3] = -1.42999322016801;
   fWeightMatrix0to1[8][3] = 1.03212561513497;
   fWeightMatrix0to1[9][3] = -1.70315939783754;
   fWeightMatrix0to1[10][3] = -1.43320512185551;
   fWeightMatrix0to1[11][3] = -1.53287872227791;
   fWeightMatrix0to1[12][3] = -2.42467039172505;
   fWeightMatrix0to1[13][3] = 1.20295891213673;
   fWeightMatrix0to1[14][3] = 0.279448565434359;
   fWeightMatrix0to1[0][4] = -1.54552432269465;
   fWeightMatrix0to1[1][4] = -0.128576983511242;
   fWeightMatrix0to1[2][4] = -0.168499168349566;
   fWeightMatrix0to1[3][4] = 0.442795638914756;
   fWeightMatrix0to1[4][4] = 0.853179172076137;
   fWeightMatrix0to1[5][4] = 0.301756725447423;
   fWeightMatrix0to1[6][4] = -0.27136246232042;
   fWeightMatrix0to1[7][4] = 0.0501087195010012;
   fWeightMatrix0to1[8][4] = 0.49422627764235;
   fWeightMatrix0to1[9][4] = -0.27883211464728;
   fWeightMatrix0to1[10][4] = -0.684158783162778;
   fWeightMatrix0to1[11][4] = -0.925552626580053;
   fWeightMatrix0to1[12][4] = 0.335773416918396;
   fWeightMatrix0to1[13][4] = 0.928094849665874;
   fWeightMatrix0to1[14][4] = 0.590665765865907;
   fWeightMatrix0to1[0][5] = -0.135753593083631;
   fWeightMatrix0to1[1][5] = -1.86498729216643;
   fWeightMatrix0to1[2][5] = -1.67720057410633;
   fWeightMatrix0to1[3][5] = 0.808856394137473;
   fWeightMatrix0to1[4][5] = 0.571581956911523;
   fWeightMatrix0to1[5][5] = 1.6212075129047;
   fWeightMatrix0to1[6][5] = -0.0314585984582595;
   fWeightMatrix0to1[7][5] = 0.0727979276982032;
   fWeightMatrix0to1[8][5] = -0.498506997532585;
   fWeightMatrix0to1[9][5] = -0.157746008682184;
   fWeightMatrix0to1[10][5] = -0.708323856410789;
   fWeightMatrix0to1[11][5] = 0.847522946117839;
   fWeightMatrix0to1[12][5] = -1.1595692579213;
   fWeightMatrix0to1[13][5] = -1.95408259641657;
   fWeightMatrix0to1[14][5] = -1.74360783369143;
   fWeightMatrix0to1[0][6] = 0.255057628284106;
   fWeightMatrix0to1[1][6] = -0.544385547188345;
   fWeightMatrix0to1[2][6] = 1.29638383236769;
   fWeightMatrix0to1[3][6] = -1.36466434211696;
   fWeightMatrix0to1[4][6] = -1.21007953052257;
   fWeightMatrix0to1[5][6] = 1.37921774992527;
   fWeightMatrix0to1[6][6] = -1.13008741784107;
   fWeightMatrix0to1[7][6] = -0.837632109765305;
   fWeightMatrix0to1[8][6] = -1.17615848866533;
   fWeightMatrix0to1[9][6] = -1.59906896624564;
   fWeightMatrix0to1[10][6] = -2.37993072971094;
   fWeightMatrix0to1[11][6] = -1.64366406180424;
   fWeightMatrix0to1[12][6] = 0.346085561636359;
   fWeightMatrix0to1[13][6] = 1.34906124773998;
   fWeightMatrix0to1[14][6] = -0.90334909066883;
   fWeightMatrix0to1[0][7] = 1.22507036475513;
   fWeightMatrix0to1[1][7] = -1.09756973876843;
   fWeightMatrix0to1[2][7] = -0.666788994165203;
   fWeightMatrix0to1[3][7] = -0.0245962334386503;
   fWeightMatrix0to1[4][7] = 0.0171011554922257;
   fWeightMatrix0to1[5][7] = -1.26506726559723;
   fWeightMatrix0to1[6][7] = 0.700064115816884;
   fWeightMatrix0to1[7][7] = 0.490826427766252;
   fWeightMatrix0to1[8][7] = 0.11618400438295;
   fWeightMatrix0to1[9][7] = -0.59390235827799;
   fWeightMatrix0to1[10][7] = 1.29641060895198;
   fWeightMatrix0to1[11][7] = 0.279923575363329;
   fWeightMatrix0to1[12][7] = -0.515114688501632;
   fWeightMatrix0to1[13][7] = 1.02419625830739;
   fWeightMatrix0to1[14][7] = -0.368133061900313;
   fWeightMatrix0to1[0][8] = -1.30917747751655;
   fWeightMatrix0to1[1][8] = -0.774693235268169;
   fWeightMatrix0to1[2][8] = -0.570305018389782;
   fWeightMatrix0to1[3][8] = 1.95580924373523;
   fWeightMatrix0to1[4][8] = 1.10444242745774;
   fWeightMatrix0to1[5][8] = 0.747291009171171;
   fWeightMatrix0to1[6][8] = -0.448707496698431;
   fWeightMatrix0to1[7][8] = -1.96212859285133;
   fWeightMatrix0to1[8][8] = -2.1969154184641;
   fWeightMatrix0to1[9][8] = 0.410132400405729;
   fWeightMatrix0to1[10][8] = -0.569221334579203;
   fWeightMatrix0to1[11][8] = -2.04225463712616;
   fWeightMatrix0to1[12][8] = 0.0285574535840707;
   fWeightMatrix0to1[13][8] = -1.73113427021932;
   fWeightMatrix0to1[14][8] = -0.740624881130441;
   fWeightMatrix0to1[0][9] = 1.37385058285117;
   fWeightMatrix0to1[1][9] = 0.992571460843261;
   fWeightMatrix0to1[2][9] = -2.04887140430343;
   fWeightMatrix0to1[3][9] = 0.332056729712599;
   fWeightMatrix0to1[4][9] = 2.15949741218121;
   fWeightMatrix0to1[5][9] = 2.03715858521736;
   fWeightMatrix0to1[6][9] = 0.0353151557685322;
   fWeightMatrix0to1[7][9] = -0.0672638267534723;
   fWeightMatrix0to1[8][9] = -0.672218232521993;
   fWeightMatrix0to1[9][9] = -2.10108523873174;
   fWeightMatrix0to1[10][9] = 0.619464511764959;
   fWeightMatrix0to1[11][9] = 1.00835108754087;
   fWeightMatrix0to1[12][9] = -1.27878089096833;
   fWeightMatrix0to1[13][9] = -0.645510090663328;
   fWeightMatrix0to1[14][9] = -0.617793640752265;
   fWeightMatrix0to1[0][10] = -1.65277639748313;
   fWeightMatrix0to1[1][10] = 1.54220086935615;
   fWeightMatrix0to1[2][10] = 1.97069640686002;
   fWeightMatrix0to1[3][10] = -0.925440162237582;
   fWeightMatrix0to1[4][10] = -0.873887461415767;
   fWeightMatrix0to1[5][10] = -0.532133226213713;
   fWeightMatrix0to1[6][10] = 1.09747301812947;
   fWeightMatrix0to1[7][10] = 3.08561662496049;
   fWeightMatrix0to1[8][10] = 1.44716287918539;
   fWeightMatrix0to1[9][10] = -0.670009192538346;
   fWeightMatrix0to1[10][10] = 2.23082033928838;
   fWeightMatrix0to1[11][10] = 1.00304036626841;
   fWeightMatrix0to1[12][10] = 1.0734715584438;
   fWeightMatrix0to1[13][10] = 0.882470573556419;
   fWeightMatrix0to1[14][10] = 1.67230875910043;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.0360653638555791;
   fWeightMatrix1to2[0][1] = 0.0022757883979415;
   fWeightMatrix1to2[0][2] = 0.0135578583855851;
   fWeightMatrix1to2[0][3] = -0.586498364452366;
   fWeightMatrix1to2[0][4] = 0.351549195244723;
   fWeightMatrix1to2[0][5] = -0.150681314670104;
   fWeightMatrix1to2[0][6] = 1.14150668699632;
   fWeightMatrix1to2[0][7] = 0.664562655822715;
   fWeightMatrix1to2[0][8] = 1.37828724569052;
   fWeightMatrix1to2[0][9] = 0.393519498089314;
   fWeightMatrix1to2[0][10] = -0.39114192057785;
   fWeightMatrix1to2[0][11] = -0.016184845531465;
   fWeightMatrix1to2[0][12] = -0.203638078539747;
   fWeightMatrix1to2[0][13] = 0.00382341840633187;
   fWeightMatrix1to2[0][14] = -1.00146917846298;
   fWeightMatrix1to2[0][15] = -1.38278432848585;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.504267275333;
   fMax_1[0][0] = 21.5219936371;
   fMin_1[1][0] = 0.501306593418;
   fMax_1[1][0] = 19.6265964508;
   fMin_1[2][0] = 0.501306593418;
   fMax_1[2][0] = 21.5219936371;
   fMin_1[0][1] = 0.611003220081;
   fMax_1[0][1] = 26.909122467;
   fMin_1[1][1] = 0.626341223717;
   fMax_1[1][1] = 26.4953784943;
   fMin_1[2][1] = 0.611003220081;
   fMax_1[2][1] = 26.909122467;
   fMin_1[0][2] = 0.501210987568;
   fMax_1[0][2] = 24.6267719269;
   fMin_1[1][2] = 0.533021330833;
   fMax_1[1][2] = 25.7579021454;
   fMin_1[2][2] = 0.501210987568;
   fMax_1[2][2] = 25.7579021454;
   fMin_1[0][3] = 8.01282119751;
   fMax_1[0][3] = 29.5046138763;
   fMin_1[1][3] = 8.22736644745;
   fMax_1[1][3] = 29.5177097321;
   fMin_1[2][3] = 8.01282119751;
   fMax_1[2][3] = 29.5177097321;
   fMin_1[0][4] = 0.0503599233925;
   fMax_1[0][4] = 0.999834001064;
   fMin_1[1][4] = 0.0506580136716;
   fMax_1[1][4] = 0.985746324062;
   fMin_1[2][4] = 0.0503599233925;
   fMax_1[2][4] = 0.999834001064;
   fMin_1[0][5] = 0.0503450036049;
   fMax_1[0][5] = 0.999168813229;
   fMin_1[1][5] = 0.0591450817883;
   fMax_1[1][5] = 0.993897438049;
   fMin_1[2][5] = 0.0503450036049;
   fMax_1[2][5] = 0.999168813229;
   fMin_1[0][6] = 0.000574055884499;
   fMax_1[0][6] = 0.198835387826;
   fMin_1[1][6] = 0.00140371813904;
   fMax_1[1][6] = 0.191456958652;
   fMin_1[2][6] = 0.000574055884499;
   fMax_1[2][6] = 0.198835387826;
   fMin_1[0][7] = 0.00111110764556;
   fMax_1[0][7] = 0.199973419309;
   fMin_1[1][7] = 0.000838859472424;
   fMax_1[1][7] = 0.19325864315;
   fMin_1[2][7] = 0.000838859472424;
   fMax_1[2][7] = 0.199973419309;
   fMin_1[0][8] = 2.05175900459;
   fMax_1[0][8] = 350.292114258;
   fMin_1[1][8] = 2.00123548508;
   fMax_1[1][8] = 2133.9609375;
   fMin_1[2][8] = 2.00123548508;
   fMax_1[2][8] = 2133.9609375;
   fMin_1[0][9] = 2.00757074356;
   fMax_1[0][9] = 166.929763794;
   fMin_1[1][9] = 2.01058912277;
   fMax_1[1][9] = 333.46270752;
   fMin_1[2][9] = 2.00757074356;
   fMax_1[2][9] = 333.46270752;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 10;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<10;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
