// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/13       [393741]
Creator        : leure
Date           : Tue Jun  6 20:01:15 2017
Host           : Linux vocms029.cern.ch 2.6.32-504.12.2.el6.x86_64 #1 SMP Thu Mar 12 07:33:00 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /data/leure/TMVA_Luke/myTMVA
Training events: 4796
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                                                         'F'    [0.527766525745,86.1248016357]
DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                                                      'F'    [0.625463962555,81.7200317383]
DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                                                      'F'    [0.501080751419,86.0996932983]
DtktkRespt                    DtktkRespt                    DtktkRespt                    DtktkRespt                                                      'F'    [8.00294494629,95.8500442505]
Dchi2cl                       Dchi2cl                       Dchi2cl                       Dchi2cl                                                         'F'    [0.0500639639795,0.999920547009]
DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl                                                 'F'    [0.0500667504966,0.999419212341]
Dalpha                        Dalpha                        Dalpha                        Dalpha                                                          'F'    [3.74872288376e-05,0.191084235907]
DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                                                  'F'    [0.00027135910932,0.173992976546]
DsvpvDistance/DsvpvDisErr     DsvpvDistance_D_DsvpvDisErr   DsvpvDistance/DsvpvDisErr     DsvpvDistance/DsvpvDisErr                                       'F'    [2.00188946724,606.031921387]
DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance_D_DtktkRes_svpvDisErr DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance/DtktkRes_svpvDisErr                                                   'F'    [2.0140440464,525.526550293]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Dtrk1Pt", "DRestrk1Pt", "DRestrk2Pt", "DtktkRespt", "Dchi2cl", "DtktkRes_chi2cl", "Dalpha", "DtktkRes_alpha", "DsvpvDistance/DsvpvDisErr", "DtktkRes_svpvDistance/DtktkRes_svpvDisErr" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][10];
   double fMax_1[3][10];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[16][11];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][16];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 11; fWeights[0] = new double[11]; 
   fLayerSize[1] = 16; fWeights[1] = new double[16]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.404475942916609;
   fWeightMatrix0to1[1][0] = 1.97753375418529;
   fWeightMatrix0to1[2][0] = 0.994637775728852;
   fWeightMatrix0to1[3][0] = 1.77820177094173;
   fWeightMatrix0to1[4][0] = -1.9613409859772;
   fWeightMatrix0to1[5][0] = -1.17459215899389;
   fWeightMatrix0to1[6][0] = -0.692384049964605;
   fWeightMatrix0to1[7][0] = 1.89391467500291;
   fWeightMatrix0to1[8][0] = -1.25397686510211;
   fWeightMatrix0to1[9][0] = -1.14397028428766;
   fWeightMatrix0to1[10][0] = -1.92492095767116;
   fWeightMatrix0to1[11][0] = -0.598587545264158;
   fWeightMatrix0to1[12][0] = -1.31519889351017;
   fWeightMatrix0to1[13][0] = -0.350264024305188;
   fWeightMatrix0to1[14][0] = -0.67386025949099;
   fWeightMatrix0to1[0][1] = 0.791074350252456;
   fWeightMatrix0to1[1][1] = -0.309109739457669;
   fWeightMatrix0to1[2][1] = 1.43976408640949;
   fWeightMatrix0to1[3][1] = 0.455274587327744;
   fWeightMatrix0to1[4][1] = 1.39565134076091;
   fWeightMatrix0to1[5][1] = -0.0829079672019883;
   fWeightMatrix0to1[6][1] = -0.94278543143203;
   fWeightMatrix0to1[7][1] = 0.703932726634781;
   fWeightMatrix0to1[8][1] = -0.213415289254233;
   fWeightMatrix0to1[9][1] = -1.05651474979926;
   fWeightMatrix0to1[10][1] = -0.802852632244666;
   fWeightMatrix0to1[11][1] = 1.09929270062801;
   fWeightMatrix0to1[12][1] = -1.0256278630956;
   fWeightMatrix0to1[13][1] = -1.90570558782919;
   fWeightMatrix0to1[14][1] = -0.25303406839535;
   fWeightMatrix0to1[0][2] = 0.79964389123935;
   fWeightMatrix0to1[1][2] = 1.67138559126269;
   fWeightMatrix0to1[2][2] = -0.635302107837583;
   fWeightMatrix0to1[3][2] = 0.250576090611412;
   fWeightMatrix0to1[4][2] = 0.290650745878366;
   fWeightMatrix0to1[5][2] = -0.229117684897872;
   fWeightMatrix0to1[6][2] = -1.65932287174455;
   fWeightMatrix0to1[7][2] = 1.66515075545538;
   fWeightMatrix0to1[8][2] = -1.48299787447791;
   fWeightMatrix0to1[9][2] = -0.0300689290709834;
   fWeightMatrix0to1[10][2] = 0.872636295665196;
   fWeightMatrix0to1[11][2] = 0.628074075662958;
   fWeightMatrix0to1[12][2] = 1.88336204510784;
   fWeightMatrix0to1[13][2] = 1.21693420146096;
   fWeightMatrix0to1[14][2] = -1.0315522388684;
   fWeightMatrix0to1[0][3] = -1.49861791815603;
   fWeightMatrix0to1[1][3] = 0.802252524340992;
   fWeightMatrix0to1[2][3] = -0.207395867009592;
   fWeightMatrix0to1[3][3] = 1.69842137561374;
   fWeightMatrix0to1[4][3] = 1.4572717012979;
   fWeightMatrix0to1[5][3] = 1.53358222548237;
   fWeightMatrix0to1[6][3] = 1.07003727979832;
   fWeightMatrix0to1[7][3] = -1.67163520960222;
   fWeightMatrix0to1[8][3] = 1.05287518423165;
   fWeightMatrix0to1[9][3] = -1.96605573203273;
   fWeightMatrix0to1[10][3] = -1.10544554629761;
   fWeightMatrix0to1[11][3] = -1.49661474657144;
   fWeightMatrix0to1[12][3] = -1.70238099004158;
   fWeightMatrix0to1[13][3] = 1.45828335147796;
   fWeightMatrix0to1[14][3] = 0.397528547222531;
   fWeightMatrix0to1[0][4] = -1.54128634238322;
   fWeightMatrix0to1[1][4] = 0.411934133231076;
   fWeightMatrix0to1[2][4] = -0.0313486089293092;
   fWeightMatrix0to1[3][4] = 0.444486030288285;
   fWeightMatrix0to1[4][4] = 1.71493529202866;
   fWeightMatrix0to1[5][4] = 0.0227235877400106;
   fWeightMatrix0to1[6][4] = -0.0337373375274928;
   fWeightMatrix0to1[7][4] = -1.18707883641093;
   fWeightMatrix0to1[8][4] = 0.525037674860168;
   fWeightMatrix0to1[9][4] = -0.14143653957024;
   fWeightMatrix0to1[10][4] = -0.734454143711933;
   fWeightMatrix0to1[11][4] = -1.06309431162176;
   fWeightMatrix0to1[12][4] = 0.677110839458117;
   fWeightMatrix0to1[13][4] = 1.1699151793936;
   fWeightMatrix0to1[14][4] = 1.01242842485269;
   fWeightMatrix0to1[0][5] = -0.238316761758721;
   fWeightMatrix0to1[1][5] = -1.88570029140679;
   fWeightMatrix0to1[2][5] = -1.73103364316119;
   fWeightMatrix0to1[3][5] = 0.727770538934507;
   fWeightMatrix0to1[4][5] = 0.525634219623831;
   fWeightMatrix0to1[5][5] = 1.74594388908463;
   fWeightMatrix0to1[6][5] = 0.304052933651793;
   fWeightMatrix0to1[7][5] = 0.966776900116282;
   fWeightMatrix0to1[8][5] = -0.727429283245613;
   fWeightMatrix0to1[9][5] = -0.309335724145839;
   fWeightMatrix0to1[10][5] = -0.148274416328981;
   fWeightMatrix0to1[11][5] = 0.707768981482677;
   fWeightMatrix0to1[12][5] = -1.06093908909037;
   fWeightMatrix0to1[13][5] = -1.59519437084274;
   fWeightMatrix0to1[14][5] = -1.19988223163211;
   fWeightMatrix0to1[0][6] = -0.080568998761994;
   fWeightMatrix0to1[1][6] = -0.0227169032155848;
   fWeightMatrix0to1[2][6] = 1.18744845610051;
   fWeightMatrix0to1[3][6] = -0.952826845904424;
   fWeightMatrix0to1[4][6] = -0.730198778520052;
   fWeightMatrix0to1[5][6] = 1.81160334700733;
   fWeightMatrix0to1[6][6] = -0.898665703395932;
   fWeightMatrix0to1[7][6] = -1.58063891438591;
   fWeightMatrix0to1[8][6] = -1.79615070110867;
   fWeightMatrix0to1[9][6] = -1.69100810451163;
   fWeightMatrix0to1[10][6] = -1.73705188973542;
   fWeightMatrix0to1[11][6] = -2.33277819803634;
   fWeightMatrix0to1[12][6] = 0.764336855758278;
   fWeightMatrix0to1[13][6] = 1.6756497467774;
   fWeightMatrix0to1[14][6] = -1.39368243885624;
   fWeightMatrix0to1[0][7] = 1.63225933796931;
   fWeightMatrix0to1[1][7] = -0.885023980226573;
   fWeightMatrix0to1[2][7] = -0.869197073335051;
   fWeightMatrix0to1[3][7] = 0.273495878926636;
   fWeightMatrix0to1[4][7] = 0.371870623365481;
   fWeightMatrix0to1[5][7] = -1.35278108609525;
   fWeightMatrix0to1[6][7] = 0.280921920451629;
   fWeightMatrix0to1[7][7] = 0.13928235451114;
   fWeightMatrix0to1[8][7] = 0.332767106445983;
   fWeightMatrix0to1[9][7] = -1.83142611002186;
   fWeightMatrix0to1[10][7] = 1.00623058048419;
   fWeightMatrix0to1[11][7] = 0.093393021079123;
   fWeightMatrix0to1[12][7] = -1.03353740558655;
   fWeightMatrix0to1[13][7] = 0.912022603456564;
   fWeightMatrix0to1[14][7] = -1.23221438814745;
   fWeightMatrix0to1[0][8] = -1.52790401080873;
   fWeightMatrix0to1[1][8] = 0.236261531527234;
   fWeightMatrix0to1[2][8] = -0.456452363199662;
   fWeightMatrix0to1[3][8] = 1.95040294746081;
   fWeightMatrix0to1[4][8] = 0.822074437492659;
   fWeightMatrix0to1[5][8] = 0.509709553717132;
   fWeightMatrix0to1[6][8] = -0.397110955587056;
   fWeightMatrix0to1[7][8] = -0.020175545026937;
   fWeightMatrix0to1[8][8] = -1.72923701120726;
   fWeightMatrix0to1[9][8] = 0.51539922648056;
   fWeightMatrix0to1[10][8] = -0.881604355456856;
   fWeightMatrix0to1[11][8] = -1.85027096130886;
   fWeightMatrix0to1[12][8] = 0.589053639010661;
   fWeightMatrix0to1[13][8] = -1.33663333923098;
   fWeightMatrix0to1[14][8] = -0.556465945816267;
   fWeightMatrix0to1[0][9] = 1.17377287629181;
   fWeightMatrix0to1[1][9] = 1.82020208718341;
   fWeightMatrix0to1[2][9] = -1.94537443306465;
   fWeightMatrix0to1[3][9] = 0.53400928844548;
   fWeightMatrix0to1[4][9] = 1.60005396549379;
   fWeightMatrix0to1[5][9] = 2.12274228309987;
   fWeightMatrix0to1[6][9] = 0.0166968397722274;
   fWeightMatrix0to1[7][9] = -1.61698745750445;
   fWeightMatrix0to1[8][9] = -0.140014771441864;
   fWeightMatrix0to1[9][9] = -1.85097339114295;
   fWeightMatrix0to1[10][9] = 0.616201197225472;
   fWeightMatrix0to1[11][9] = 0.885811300804401;
   fWeightMatrix0to1[12][9] = -0.562600427322277;
   fWeightMatrix0to1[13][9] = -0.315166868018316;
   fWeightMatrix0to1[14][9] = -0.536227747731782;
   fWeightMatrix0to1[0][10] = -1.45772572098619;
   fWeightMatrix0to1[1][10] = 0.503272492172447;
   fWeightMatrix0to1[2][10] = 2.10972160046976;
   fWeightMatrix0to1[3][10] = -1.22337805856203;
   fWeightMatrix0to1[4][10] = -0.698796216959818;
   fWeightMatrix0to1[5][10] = -0.140258639663646;
   fWeightMatrix0to1[6][10] = 1.20127249451469;
   fWeightMatrix0to1[7][10] = 0.701551989782291;
   fWeightMatrix0to1[8][10] = 1.29614565430465;
   fWeightMatrix0to1[9][10] = -0.311986167649987;
   fWeightMatrix0to1[10][10] = 2.422251212147;
   fWeightMatrix0to1[11][10] = 1.34668358638922;
   fWeightMatrix0to1[12][10] = 0.49312089241855;
   fWeightMatrix0to1[13][10] = 0.528906251954059;
   fWeightMatrix0to1[14][10] = 1.48225258182545;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.00050244749511628;
   fWeightMatrix1to2[0][1] = 0.00267726793773732;
   fWeightMatrix1to2[0][2] = -0.00841300891979783;
   fWeightMatrix1to2[0][3] = 0.0909610411061264;
   fWeightMatrix1to2[0][4] = 0.00632478460278286;
   fWeightMatrix1to2[0][5] = -0.0189299938341725;
   fWeightMatrix1to2[0][6] = 1.2589091278142;
   fWeightMatrix1to2[0][7] = 0.00997795447135827;
   fWeightMatrix1to2[0][8] = 1.72427725861949;
   fWeightMatrix1to2[0][9] = 1.00762244399923;
   fWeightMatrix1to2[0][10] = -0.818884507751095;
   fWeightMatrix1to2[0][11] = 0.222361640506226;
   fWeightMatrix1to2[0][12] = 0.00140165706994739;
   fWeightMatrix1to2[0][13] = 0.00246311376490097;
   fWeightMatrix1to2[0][14] = -1.1075429251717;
   fWeightMatrix1to2[0][15] = -1.20613597902818;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.588397085667;
   fMax_1[0][0] = 86.1248016357;
   fMin_1[1][0] = 0.527766525745;
   fMax_1[1][0] = 75.455329895;
   fMin_1[2][0] = 0.527766525745;
   fMax_1[2][0] = 86.1248016357;
   fMin_1[0][1] = 0.671695172787;
   fMax_1[0][1] = 81.7200317383;
   fMin_1[1][1] = 0.625463962555;
   fMax_1[1][1] = 65.9077224731;
   fMin_1[2][1] = 0.625463962555;
   fMax_1[2][1] = 81.7200317383;
   fMin_1[0][2] = 0.501080751419;
   fMax_1[0][2] = 86.0996932983;
   fMin_1[1][2] = 1.38317227364;
   fMax_1[1][2] = 64.2518081665;
   fMin_1[2][2] = 0.501080751419;
   fMax_1[2][2] = 86.0996932983;
   fMin_1[0][3] = 8.00294494629;
   fMax_1[0][3] = 95.8500442505;
   fMin_1[1][3] = 9.83195781708;
   fMax_1[1][3] = 89.8447189331;
   fMin_1[2][3] = 8.00294494629;
   fMax_1[2][3] = 95.8500442505;
   fMin_1[0][4] = 0.0500639639795;
   fMax_1[0][4] = 0.999920547009;
   fMin_1[1][4] = 0.0727632343769;
   fMax_1[1][4] = 0.959187746048;
   fMin_1[2][4] = 0.0500639639795;
   fMax_1[2][4] = 0.999920547009;
   fMin_1[0][5] = 0.0500667504966;
   fMax_1[0][5] = 0.999419212341;
   fMin_1[1][5] = 0.0862152799964;
   fMax_1[1][5] = 0.92363858223;
   fMin_1[2][5] = 0.0500667504966;
   fMax_1[2][5] = 0.999419212341;
   fMin_1[0][6] = 3.74872288376e-05;
   fMax_1[0][6] = 0.176816552877;
   fMin_1[1][6] = 0.00400305725634;
   fMax_1[1][6] = 0.191084235907;
   fMin_1[2][6] = 3.74872288376e-05;
   fMax_1[2][6] = 0.191084235907;
   fMin_1[0][7] = 0.00027135910932;
   fMax_1[0][7] = 0.173992976546;
   fMin_1[1][7] = 0.000534758786671;
   fMax_1[1][7] = 0.0724445059896;
   fMin_1[2][7] = 0.00027135910932;
   fMax_1[2][7] = 0.173992976546;
   fMin_1[0][8] = 2.00188946724;
   fMax_1[0][8] = 606.031921387;
   fMin_1[1][8] = 2.09861850739;
   fMax_1[1][8] = 121.423728943;
   fMin_1[2][8] = 2.00188946724;
   fMax_1[2][8] = 606.031921387;
   fMin_1[0][9] = 2.0140440464;
   fMax_1[0][9] = 525.526550293;
   fMin_1[1][9] = 2.01771521568;
   fMax_1[1][9] = 267.912597656;
   fMin_1[2][9] = 2.0140440464;
   fMax_1[2][9] = 525.526550293;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 10;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<10;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
