// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/13       [393741]
Creator        : leure
Date           : Thu Jun  8 19:44:30 2017
Host           : Linux vocms029.cern.ch 2.6.32-504.12.2.el6.x86_64 #1 SMP Thu Mar 12 07:33:00 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /data/leure/TMVA_Luke/myTMVA
Training events: 928
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                                                         'F'    [0.50014847517,7.20036029816]
DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                                                      'F'    [0.638102293015,14.3522796631]
DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                                                      'F'    [0.501896739006,13.6910076141]
DtktkRespt                    DtktkRespt                    DtktkRespt                    DtktkRespt                                                      'F'    [8.00104999542,15.1344156265]
Dchi2cl                       Dchi2cl                       Dchi2cl                       Dchi2cl                                                         'F'    [0.0503078736365,0.999811887741]
DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl                                                 'F'    [0.0517275892198,0.999927341938]
Dalpha                        Dalpha                        Dalpha                        Dalpha                                                          'F'    [0.000702218851075,0.19975912571]
DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                                                  'F'    [0.000302527332678,0.198539033532]
DsvpvDistance/DsvpvDisErr     DsvpvDistance_D_DsvpvDisErr   DsvpvDistance/DsvpvDisErr     DsvpvDistance/DsvpvDisErr                                       'F'    [2.00435757637,1013.29718018]
DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance_D_DtktkRes_svpvDisErr DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance/DtktkRes_svpvDisErr                                                   'F'    [2.00124073029,167.399963379]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Dtrk1Pt", "DRestrk1Pt", "DRestrk2Pt", "DtktkRespt", "Dchi2cl", "DtktkRes_chi2cl", "Dalpha", "DtktkRes_alpha", "DsvpvDistance/DsvpvDisErr", "DtktkRes_svpvDistance/DtktkRes_svpvDisErr" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][10];
   double fMax_1[3][10];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[16][11];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][16];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 11; fWeights[0] = new double[11]; 
   fLayerSize[1] = 16; fWeights[1] = new double[16]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.828865755258551;
   fWeightMatrix0to1[1][0] = 1.76218158337696;
   fWeightMatrix0to1[2][0] = 0.842177194180713;
   fWeightMatrix0to1[3][0] = 1.76451086226252;
   fWeightMatrix0to1[4][0] = -1.97967819823749;
   fWeightMatrix0to1[5][0] = -1.62244018281151;
   fWeightMatrix0to1[6][0] = -0.95372322290657;
   fWeightMatrix0to1[7][0] = 3.12910547467711;
   fWeightMatrix0to1[8][0] = -1.8665093883783;
   fWeightMatrix0to1[9][0] = -0.896307734599263;
   fWeightMatrix0to1[10][0] = -2.64262073284025;
   fWeightMatrix0to1[11][0] = -0.314652115162881;
   fWeightMatrix0to1[12][0] = -1.10266579797535;
   fWeightMatrix0to1[13][0] = -0.425756690169765;
   fWeightMatrix0to1[14][0] = -0.828524289495442;
   fWeightMatrix0to1[0][1] = 0.49281016053326;
   fWeightMatrix0to1[1][1] = -0.33959907917628;
   fWeightMatrix0to1[2][1] = 1.56026081226839;
   fWeightMatrix0to1[3][1] = 0.215108618724538;
   fWeightMatrix0to1[4][1] = 1.37877088385604;
   fWeightMatrix0to1[5][1] = -0.199598355384762;
   fWeightMatrix0to1[6][1] = -1.23536434062326;
   fWeightMatrix0to1[7][1] = 1.35589942277196;
   fWeightMatrix0to1[8][1] = -0.256636458458767;
   fWeightMatrix0to1[9][1] = -1.04014590094619;
   fWeightMatrix0to1[10][1] = 0.305088259599114;
   fWeightMatrix0to1[11][1] = 1.62103570566484;
   fWeightMatrix0to1[12][1] = -1.06805867503488;
   fWeightMatrix0to1[13][1] = -1.93526107916802;
   fWeightMatrix0to1[14][1] = -0.120740057088992;
   fWeightMatrix0to1[0][2] = 0.894081799313448;
   fWeightMatrix0to1[1][2] = 1.5782020605507;
   fWeightMatrix0to1[2][2] = -0.522088360590208;
   fWeightMatrix0to1[3][2] = 0.00962750328738701;
   fWeightMatrix0to1[4][2] = 0.239955746165442;
   fWeightMatrix0to1[5][2] = -0.364609297098937;
   fWeightMatrix0to1[6][2] = -1.10921580951838;
   fWeightMatrix0to1[7][2] = 1.14175686545558;
   fWeightMatrix0to1[8][2] = -1.22288571565378;
   fWeightMatrix0to1[9][2] = 1.3847078807439;
   fWeightMatrix0to1[10][2] = 0.196883376760501;
   fWeightMatrix0to1[11][2] = 0.754159548807508;
   fWeightMatrix0to1[12][2] = 2.13061440048826;
   fWeightMatrix0to1[13][2] = 1.20476939023078;
   fWeightMatrix0to1[14][2] = -0.576634212377166;
   fWeightMatrix0to1[0][3] = -1.45634871215772;
   fWeightMatrix0to1[1][3] = 0.829939788667404;
   fWeightMatrix0to1[2][3] = -0.203758625958042;
   fWeightMatrix0to1[3][3] = 1.63839133029664;
   fWeightMatrix0to1[4][3] = 1.4344187534581;
   fWeightMatrix0to1[5][3] = 1.52252896455612;
   fWeightMatrix0to1[6][3] = 1.32000972333437;
   fWeightMatrix0to1[7][3] = -0.987749530096604;
   fWeightMatrix0to1[8][3] = 1.04451794045419;
   fWeightMatrix0to1[9][3] = -1.24020541748552;
   fWeightMatrix0to1[10][3] = -0.944211910886794;
   fWeightMatrix0to1[11][3] = -1.36647434469827;
   fWeightMatrix0to1[12][3] = -1.44145243009212;
   fWeightMatrix0to1[13][3] = 1.44998379142735;
   fWeightMatrix0to1[14][3] = 0.931912954898353;
   fWeightMatrix0to1[0][4] = -1.894795021174;
   fWeightMatrix0to1[1][4] = 0.428436501932303;
   fWeightMatrix0to1[2][4] = 0.0431511868679739;
   fWeightMatrix0to1[3][4] = 0.671185637591228;
   fWeightMatrix0to1[4][4] = 1.76211228540653;
   fWeightMatrix0to1[5][4] = -0.494295131311145;
   fWeightMatrix0to1[6][4] = -0.328342845974399;
   fWeightMatrix0to1[7][4] = 0.234340167644132;
   fWeightMatrix0to1[8][4] = 0.258564441575968;
   fWeightMatrix0to1[9][4] = -0.419830861102233;
   fWeightMatrix0to1[10][4] = -0.382861130958903;
   fWeightMatrix0to1[11][4] = -1.25666267046642;
   fWeightMatrix0to1[12][4] = 0.0276275963928887;
   fWeightMatrix0to1[13][4] = 1.11391712097799;
   fWeightMatrix0to1[14][4] = 0.623537400751249;
   fWeightMatrix0to1[0][5] = -0.181360366706918;
   fWeightMatrix0to1[1][5] = -2.07664572304377;
   fWeightMatrix0to1[2][5] = -1.5335610669263;
   fWeightMatrix0to1[3][5] = 0.949836786614482;
   fWeightMatrix0to1[4][5] = 0.477119642175584;
   fWeightMatrix0to1[5][5] = 1.57571307721459;
   fWeightMatrix0to1[6][5] = 0.568525968224848;
   fWeightMatrix0to1[7][5] = 0.139035083229765;
   fWeightMatrix0to1[8][5] = -1.06335620234295;
   fWeightMatrix0to1[9][5] = -0.872995241209441;
   fWeightMatrix0to1[10][5] = 0.245831604474079;
   fWeightMatrix0to1[11][5] = 1.14474666514448;
   fWeightMatrix0to1[12][5] = -1.01203128983327;
   fWeightMatrix0to1[13][5] = -1.56300680152956;
   fWeightMatrix0to1[14][5] = -1.10363578678359;
   fWeightMatrix0to1[0][6] = -0.101556894380832;
   fWeightMatrix0to1[1][6] = -0.156028564548625;
   fWeightMatrix0to1[2][6] = 1.11347979937167;
   fWeightMatrix0to1[3][6] = -1.31120512261657;
   fWeightMatrix0to1[4][6] = -0.823861087995148;
   fWeightMatrix0to1[5][6] = 1.66683083096966;
   fWeightMatrix0to1[6][6] = -0.907378498024954;
   fWeightMatrix0to1[7][6] = -2.04603171875333;
   fWeightMatrix0to1[8][6] = -1.29684352883592;
   fWeightMatrix0to1[9][6] = -0.145972542262526;
   fWeightMatrix0to1[10][6] = -1.39709181709629;
   fWeightMatrix0to1[11][6] = -1.65762783746958;
   fWeightMatrix0to1[12][6] = 0.6519075713212;
   fWeightMatrix0to1[13][6] = 1.55793024788868;
   fWeightMatrix0to1[14][6] = -1.17764127480805;
   fWeightMatrix0to1[0][7] = 1.10253836669981;
   fWeightMatrix0to1[1][7] = -0.920633422283339;
   fWeightMatrix0to1[2][7] = -0.964333165458893;
   fWeightMatrix0to1[3][7] = -0.265926622317033;
   fWeightMatrix0to1[4][7] = 0.267346854555952;
   fWeightMatrix0to1[5][7] = -1.78566021674154;
   fWeightMatrix0to1[6][7] = 0.338033973009246;
   fWeightMatrix0to1[7][7] = 0.5664143080133;
   fWeightMatrix0to1[8][7] = 0.0777762263036152;
   fWeightMatrix0to1[9][7] = -0.240427864822465;
   fWeightMatrix0to1[10][7] = 0.921803730564446;
   fWeightMatrix0to1[11][7] = 0.418028489688079;
   fWeightMatrix0to1[12][7] = -1.21941396614589;
   fWeightMatrix0to1[13][7] = 0.875663326540126;
   fWeightMatrix0to1[14][7] = -0.720570591084137;
   fWeightMatrix0to1[0][8] = -1.74928330008075;
   fWeightMatrix0to1[1][8] = 0.0576925072315565;
   fWeightMatrix0to1[2][8] = -0.801172160133841;
   fWeightMatrix0to1[3][8] = 2.02005979322412;
   fWeightMatrix0to1[4][8] = 0.803405006341519;
   fWeightMatrix0to1[5][8] = 0.11819885970119;
   fWeightMatrix0to1[6][8] = -0.421501399329719;
   fWeightMatrix0to1[7][8] = -0.649408959865494;
   fWeightMatrix0to1[8][8] = -1.31739346333559;
   fWeightMatrix0to1[9][8] = 1.33381359480868;
   fWeightMatrix0to1[10][8] = -0.833709225354651;
   fWeightMatrix0to1[11][8] = -1.7493544332407;
   fWeightMatrix0to1[12][8] = 0.837228233862851;
   fWeightMatrix0to1[13][8] = -1.46248812599581;
   fWeightMatrix0to1[14][8] = -0.570869800696015;
   fWeightMatrix0to1[0][9] = 0.904930975565349;
   fWeightMatrix0to1[1][9] = 1.71750140752362;
   fWeightMatrix0to1[2][9] = -2.06017159517592;
   fWeightMatrix0to1[3][9] = 0.60063038441305;
   fWeightMatrix0to1[4][9] = 1.58053974225533;
   fWeightMatrix0to1[5][9] = 1.56183565495168;
   fWeightMatrix0to1[6][9] = 0.0428790334163498;
   fWeightMatrix0to1[7][9] = 0.291259482118037;
   fWeightMatrix0to1[8][9] = -0.573595975400277;
   fWeightMatrix0to1[9][9] = -1.68093132731006;
   fWeightMatrix0to1[10][9] = 0.569990476850025;
   fWeightMatrix0to1[11][9] = 1.22295334175664;
   fWeightMatrix0to1[12][9] = 0.035250595931732;
   fWeightMatrix0to1[13][9] = -0.438687174032401;
   fWeightMatrix0to1[14][9] = -0.41430948153788;
   fWeightMatrix0to1[0][10] = -1.17923585062355;
   fWeightMatrix0to1[1][10] = 0.687251994270696;
   fWeightMatrix0to1[2][10] = 2.22859425738602;
   fWeightMatrix0to1[3][10] = -0.938526486795512;
   fWeightMatrix0to1[4][10] = -0.636257266327422;
   fWeightMatrix0to1[5][10] = 0.106429384426461;
   fWeightMatrix0to1[6][10] = 1.40941045052489;
   fWeightMatrix0to1[7][10] = 1.54495169211474;
   fWeightMatrix0to1[8][10] = 1.43955151411369;
   fWeightMatrix0to1[9][10] = -1.72972000610373;
   fWeightMatrix0to1[10][10] = 2.49912114424802;
   fWeightMatrix0to1[11][10] = 0.695557247347016;
   fWeightMatrix0to1[12][10] = 0.289745781307876;
   fWeightMatrix0to1[13][10] = 0.635041226916707;
   fWeightMatrix0to1[14][10] = 1.51554495506049;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.0446262653858365;
   fWeightMatrix1to2[0][1] = 0.0311548226727964;
   fWeightMatrix1to2[0][2] = 0.19875119094328;
   fWeightMatrix1to2[0][3] = -0.976327295747396;
   fWeightMatrix1to2[0][4] = -0.0143222780697924;
   fWeightMatrix1to2[0][5] = -0.00375875539517429;
   fWeightMatrix1to2[0][6] = 1.03140915802929;
   fWeightMatrix1to2[0][7] = 0.536723008785391;
   fWeightMatrix1to2[0][8] = 1.00570726723167;
   fWeightMatrix1to2[0][9] = -0.2026232843587;
   fWeightMatrix1to2[0][10] = -0.840871310785407;
   fWeightMatrix1to2[0][11] = -0.0749570286170916;
   fWeightMatrix1to2[0][12] = 0.149053726908783;
   fWeightMatrix1to2[0][13] = 0.0112915615299192;
   fWeightMatrix1to2[0][14] = -0.629982333988486;
   fWeightMatrix1to2[0][15] = -1.22200945830349;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.507495820522;
   fMax_1[0][0] = 7.20036029816;
   fMin_1[1][0] = 0.50014847517;
   fMax_1[1][0] = 4.43583250046;
   fMin_1[2][0] = 0.50014847517;
   fMax_1[2][0] = 7.20036029816;
   fMin_1[0][1] = 0.729051172733;
   fMax_1[0][1] = 14.2904396057;
   fMin_1[1][1] = 0.638102293015;
   fMax_1[1][1] = 14.3522796631;
   fMin_1[2][1] = 0.638102293015;
   fMax_1[2][1] = 14.3522796631;
   fMin_1[0][2] = 0.501896739006;
   fMax_1[0][2] = 12.0277862549;
   fMin_1[1][2] = 0.503266513348;
   fMax_1[1][2] = 13.6910076141;
   fMin_1[2][2] = 0.501896739006;
   fMax_1[2][2] = 13.6910076141;
   fMin_1[0][3] = 8.00104999542;
   fMax_1[0][3] = 14.7768802643;
   fMin_1[1][3] = 8.1483259201;
   fMax_1[1][3] = 15.1344156265;
   fMin_1[2][3] = 8.00104999542;
   fMax_1[2][3] = 15.1344156265;
   fMin_1[0][4] = 0.0535734333098;
   fMax_1[0][4] = 0.994582295418;
   fMin_1[1][4] = 0.0503078736365;
   fMax_1[1][4] = 0.999811887741;
   fMin_1[2][4] = 0.0503078736365;
   fMax_1[2][4] = 0.999811887741;
   fMin_1[0][5] = 0.0530742667615;
   fMax_1[0][5] = 0.999927341938;
   fMin_1[1][5] = 0.0517275892198;
   fMax_1[1][5] = 0.998076200485;
   fMin_1[2][5] = 0.0517275892198;
   fMax_1[2][5] = 0.999927341938;
   fMin_1[0][6] = 0.000702218851075;
   fMax_1[0][6] = 0.199459403753;
   fMin_1[1][6] = 0.000998831936158;
   fMax_1[1][6] = 0.19975912571;
   fMin_1[2][6] = 0.000702218851075;
   fMax_1[2][6] = 0.19975912571;
   fMin_1[0][7] = 0.00300091924146;
   fMax_1[0][7] = 0.197489976883;
   fMin_1[1][7] = 0.000302527332678;
   fMax_1[1][7] = 0.198539033532;
   fMin_1[2][7] = 0.000302527332678;
   fMax_1[2][7] = 0.198539033532;
   fMin_1[0][8] = 2.09239554405;
   fMax_1[0][8] = 123.124839783;
   fMin_1[1][8] = 2.00435757637;
   fMax_1[1][8] = 1013.29718018;
   fMin_1[2][8] = 2.00435757637;
   fMax_1[2][8] = 1013.29718018;
   fMin_1[0][9] = 2.03231906891;
   fMax_1[0][9] = 63.297290802;
   fMin_1[1][9] = 2.00124073029;
   fMax_1[1][9] = 167.399963379;
   fMin_1[2][9] = 2.00124073029;
   fMax_1[2][9] = 167.399963379;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 10;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<10;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
