// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/13       [393741]
Creator        : leure
Date           : Thu Jun  8 20:01:12 2017
Host           : Linux vocms029.cern.ch 2.6.32-504.12.2.el6.x86_64 #1 SMP Thu Mar 12 07:33:00 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /data/leure/TMVA_Luke/myTMVA
Training events: 2320
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                                                         'F'    [0.500997126102,12.2764291763]
DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                                                      'F'    [0.660297811031,18.7841835022]
DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                                                      'F'    [0.503957271576,18.0702095032]
DtktkRespt                    DtktkRespt                    DtktkRespt                    DtktkRespt                                                      'F'    [8.01337337494,20.0275936127]
Dchi2cl                       Dchi2cl                       Dchi2cl                       Dchi2cl                                                         'F'    [0.0500634536147,0.998736560345]
DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl                                                 'F'    [0.0503618642688,0.999740004539]
Dalpha                        Dalpha                        Dalpha                        Dalpha                                                          'F'    [9.7360854852e-05,0.199530050159]
DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                                                  'F'    [0.0012481494341,0.199770435691]
DsvpvDistance/DsvpvDisErr     DsvpvDistance_D_DsvpvDisErr   DsvpvDistance/DsvpvDisErr     DsvpvDistance/DsvpvDisErr                                       'F'    [2.00035476685,186.669784546]
DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance_D_DtktkRes_svpvDisErr DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance/DtktkRes_svpvDisErr                                                   'F'    [2.00586509705,96.4862823486]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Dtrk1Pt", "DRestrk1Pt", "DRestrk2Pt", "DtktkRespt", "Dchi2cl", "DtktkRes_chi2cl", "Dalpha", "DtktkRes_alpha", "DsvpvDistance/DsvpvDisErr", "DtktkRes_svpvDistance/DtktkRes_svpvDisErr" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][10];
   double fMax_1[3][10];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[16][11];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][16];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 11; fWeights[0] = new double[11]; 
   fLayerSize[1] = 16; fWeights[1] = new double[16]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.64442317572224;
   fWeightMatrix0to1[1][0] = 1.65917139337089;
   fWeightMatrix0to1[2][0] = 1.39747109022675;
   fWeightMatrix0to1[3][0] = 1.38121139310882;
   fWeightMatrix0to1[4][0] = -1.86371017173723;
   fWeightMatrix0to1[5][0] = -1.56113043488701;
   fWeightMatrix0to1[6][0] = -0.683288447682236;
   fWeightMatrix0to1[7][0] = 3.39019859972705;
   fWeightMatrix0to1[8][0] = -1.44312990161397;
   fWeightMatrix0to1[9][0] = -0.982588776019311;
   fWeightMatrix0to1[10][0] = -1.85623556334599;
   fWeightMatrix0to1[11][0] = -0.423932923358276;
   fWeightMatrix0to1[12][0] = -1.21917203818277;
   fWeightMatrix0to1[13][0] = -0.337919149522315;
   fWeightMatrix0to1[14][0] = -0.689411688891649;
   fWeightMatrix0to1[0][1] = 0.164475936174523;
   fWeightMatrix0to1[1][1] = -0.245733112431916;
   fWeightMatrix0to1[2][1] = 1.77578705796917;
   fWeightMatrix0to1[3][1] = -0.0739590421490382;
   fWeightMatrix0to1[4][1] = 1.44073536307833;
   fWeightMatrix0to1[5][1] = 0.0472537073178191;
   fWeightMatrix0to1[6][1] = -0.784624326036125;
   fWeightMatrix0to1[7][1] = 0.442857710871246;
   fWeightMatrix0to1[8][1] = -0.547448973665558;
   fWeightMatrix0to1[9][1] = -0.658540462155578;
   fWeightMatrix0to1[10][1] = 0.122091257908473;
   fWeightMatrix0to1[11][1] = 1.2265081604138;
   fWeightMatrix0to1[12][1] = -0.992586132129363;
   fWeightMatrix0to1[13][1] = -1.7535751001082;
   fWeightMatrix0to1[14][1] = 0.311122535792938;
   fWeightMatrix0to1[0][2] = 0.817513139427553;
   fWeightMatrix0to1[1][2] = 1.38803825961683;
   fWeightMatrix0to1[2][2] = -0.90156564623202;
   fWeightMatrix0to1[3][2] = 0.163248267448924;
   fWeightMatrix0to1[4][2] = 0.341863988224123;
   fWeightMatrix0to1[5][2] = 0.0100073158468905;
   fWeightMatrix0to1[6][2] = -1.55598318417227;
   fWeightMatrix0to1[7][2] = 0.351961725131763;
   fWeightMatrix0to1[8][2] = -1.49460373489408;
   fWeightMatrix0to1[9][2] = 0.656241081357471;
   fWeightMatrix0to1[10][2] = 0.721738979185278;
   fWeightMatrix0to1[11][2] = 0.512814768080431;
   fWeightMatrix0to1[12][2] = 1.77009382603877;
   fWeightMatrix0to1[13][2] = 1.00664714910195;
   fWeightMatrix0to1[14][2] = -0.331048398806057;
   fWeightMatrix0to1[0][3] = -1.4924435321112;
   fWeightMatrix0to1[1][3] = 0.905098506024443;
   fWeightMatrix0to1[2][3] = -0.502775069900428;
   fWeightMatrix0to1[3][3] = 1.8222591781058;
   fWeightMatrix0to1[4][3] = 1.74254928744182;
   fWeightMatrix0to1[5][3] = 2.05725518669381;
   fWeightMatrix0to1[6][3] = 1.18389128966391;
   fWeightMatrix0to1[7][3] = -0.687533362267529;
   fWeightMatrix0to1[8][3] = 0.77510683105805;
   fWeightMatrix0to1[9][3] = -1.84810031205017;
   fWeightMatrix0to1[10][3] = -0.918062629159292;
   fWeightMatrix0to1[11][3] = -1.7314119544663;
   fWeightMatrix0to1[12][3] = -1.74631898538837;
   fWeightMatrix0to1[13][3] = 1.40327484008614;
   fWeightMatrix0to1[14][3] = 0.997669829930023;
   fWeightMatrix0to1[0][4] = -0.950019009559091;
   fWeightMatrix0to1[1][4] = 0.0510031915977777;
   fWeightMatrix0to1[2][4] = 0.115756867451693;
   fWeightMatrix0to1[3][4] = 0.334873145829728;
   fWeightMatrix0to1[4][4] = 1.45979766832213;
   fWeightMatrix0to1[5][4] = -0.227802927896169;
   fWeightMatrix0to1[6][4] = -0.296477425966714;
   fWeightMatrix0to1[7][4] = 0.151418667598825;
   fWeightMatrix0to1[8][4] = 0.191098152197574;
   fWeightMatrix0to1[9][4] = -0.106772780891307;
   fWeightMatrix0to1[10][4] = -1.11843882643762;
   fWeightMatrix0to1[11][4] = -0.483710057272742;
   fWeightMatrix0to1[12][4] = 0.420254505254261;
   fWeightMatrix0to1[13][4] = 1.32028385452065;
   fWeightMatrix0to1[14][4] = 0.778474003571509;
   fWeightMatrix0to1[0][5] = -0.38572046164493;
   fWeightMatrix0to1[1][5] = -1.62600760069972;
   fWeightMatrix0to1[2][5] = -1.57931944931438;
   fWeightMatrix0to1[3][5] = 0.852948424447577;
   fWeightMatrix0to1[4][5] = 0.0378828600943119;
   fWeightMatrix0to1[5][5] = 1.29565435590942;
   fWeightMatrix0to1[6][5] = 0.486533919231097;
   fWeightMatrix0to1[7][5] = 0.0686556525560693;
   fWeightMatrix0to1[8][5] = -0.726365018414366;
   fWeightMatrix0to1[9][5] = -1.39747913827435;
   fWeightMatrix0to1[10][5] = 0.141855032705748;
   fWeightMatrix0to1[11][5] = 0.852126960750997;
   fWeightMatrix0to1[12][5] = -0.584303440451773;
   fWeightMatrix0to1[13][5] = -1.29388525499372;
   fWeightMatrix0to1[14][5] = -1.80638171228457;
   fWeightMatrix0to1[0][6] = -0.885346829647183;
   fWeightMatrix0to1[1][6] = -0.0994339051365963;
   fWeightMatrix0to1[2][6] = 1.17105392216165;
   fWeightMatrix0to1[3][6] = -1.75815377599466;
   fWeightMatrix0to1[4][6] = -0.857599905988791;
   fWeightMatrix0to1[5][6] = 1.36685250645777;
   fWeightMatrix0to1[6][6] = -0.983390119349973;
   fWeightMatrix0to1[7][6] = -0.35981648317907;
   fWeightMatrix0to1[8][6] = -1.30039555142468;
   fWeightMatrix0to1[9][6] = -0.401194829989474;
   fWeightMatrix0to1[10][6] = -2.36417533794305;
   fWeightMatrix0to1[11][6] = -1.83843559587408;
   fWeightMatrix0to1[12][6] = 0.573918192519798;
   fWeightMatrix0to1[13][6] = 1.40943271944781;
   fWeightMatrix0to1[14][6] = -0.379035253416516;
   fWeightMatrix0to1[0][7] = 1.47063756538124;
   fWeightMatrix0to1[1][7] = -1.06474027937117;
   fWeightMatrix0to1[2][7] = -0.0372164445367817;
   fWeightMatrix0to1[3][7] = -0.346064917203329;
   fWeightMatrix0to1[4][7] = -0.143330828517104;
   fWeightMatrix0to1[5][7] = -1.44065925188559;
   fWeightMatrix0to1[6][7] = 0.315351074287706;
   fWeightMatrix0to1[7][7] = 0.407103406607773;
   fWeightMatrix0to1[8][7] = 0.130690070931243;
   fWeightMatrix0to1[9][7] = -1.44270293341185;
   fWeightMatrix0to1[10][7] = 1.54183322446186;
   fWeightMatrix0to1[11][7] = 0.0683456512844451;
   fWeightMatrix0to1[12][7] = -1.29683236371848;
   fWeightMatrix0to1[13][7] = 0.975491940781552;
   fWeightMatrix0to1[14][7] = -1.63597839589705;
   fWeightMatrix0to1[0][8] = -2.31382772139679;
   fWeightMatrix0to1[1][8] = -0.0550168221870884;
   fWeightMatrix0to1[2][8] = -0.245924221994538;
   fWeightMatrix0to1[3][8] = 1.50746986061565;
   fWeightMatrix0to1[4][8] = 0.628650074466038;
   fWeightMatrix0to1[5][8] = 0.540006427872479;
   fWeightMatrix0to1[6][8] = -0.448411263801143;
   fWeightMatrix0to1[7][8] = -0.26083740519089;
   fWeightMatrix0to1[8][8] = -2.1923492384539;
   fWeightMatrix0to1[9][8] = 1.2420723126774;
   fWeightMatrix0to1[10][8] = -0.107109721560468;
   fWeightMatrix0to1[11][8] = -2.01611997744274;
   fWeightMatrix0to1[12][8] = 0.474652609599831;
   fWeightMatrix0to1[13][8] = -1.36861129627457;
   fWeightMatrix0to1[14][8] = 0.232978758422564;
   fWeightMatrix0to1[0][9] = 0.354712743019496;
   fWeightMatrix0to1[1][9] = 1.67566142868336;
   fWeightMatrix0to1[2][9] = -1.73606882720592;
   fWeightMatrix0to1[3][9] = -0.146978556534357;
   fWeightMatrix0to1[4][9] = 1.60401601350404;
   fWeightMatrix0to1[5][9] = 1.61051857971635;
   fWeightMatrix0to1[6][9] = -0.127318656370444;
   fWeightMatrix0to1[7][9] = 1.25653388113457;
   fWeightMatrix0to1[8][9] = -0.604238872293504;
   fWeightMatrix0to1[9][9] = -1.14476660607384;
   fWeightMatrix0to1[10][9] = 1.2934914074718;
   fWeightMatrix0to1[11][9] = 0.679968557987472;
   fWeightMatrix0to1[12][9] = -0.648860814305227;
   fWeightMatrix0to1[13][9] = -0.233403469362215;
   fWeightMatrix0to1[14][9] = 0.197264350135073;
   fWeightMatrix0to1[0][10] = -0.478471419316653;
   fWeightMatrix0to1[1][10] = 0.941810361238871;
   fWeightMatrix0to1[2][10] = 1.97052201987944;
   fWeightMatrix0to1[3][10] = -0.353392030371145;
   fWeightMatrix0to1[4][10] = -0.563349896899292;
   fWeightMatrix0to1[5][10] = -0.335720637191899;
   fWeightMatrix0to1[6][10] = 1.11729643948023;
   fWeightMatrix0to1[7][10] = 4.73714042466945;
   fWeightMatrix0to1[8][10] = 1.93235676945693;
   fWeightMatrix0to1[9][10] = -1.64155584264956;
   fWeightMatrix0to1[10][10] = 1.74131569264577;
   fWeightMatrix0to1[11][10] = 1.41404146432366;
   fWeightMatrix0to1[12][10] = 0.534469187776003;
   fWeightMatrix0to1[13][10] = 0.574356469736674;
   fWeightMatrix0to1[14][10] = 0.326680313930887;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.158260417699508;
   fWeightMatrix1to2[0][1] = -0.000207887338182632;
   fWeightMatrix1to2[0][2] = 0.0237011666310963;
   fWeightMatrix1to2[0][3] = 0.0271067429966049;
   fWeightMatrix1to2[0][4] = 0.0928570795068083;
   fWeightMatrix1to2[0][5] = 0.0525880531085601;
   fWeightMatrix1to2[0][6] = 0.890972459185373;
   fWeightMatrix1to2[0][7] = 0.889999591188834;
   fWeightMatrix1to2[0][8] = 0.970665548589299;
   fWeightMatrix1to2[0][9] = 0.00220824649930475;
   fWeightMatrix1to2[0][10] = -0.0713794979912903;
   fWeightMatrix1to2[0][11] = -0.254094386705388;
   fWeightMatrix1to2[0][12] = 0.0214026451871671;
   fWeightMatrix1to2[0][13] = -0.00151200582406616;
   fWeightMatrix1to2[0][14] = 0.00263009498057961;
   fWeightMatrix1to2[0][15] = -1.43088992331525;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.501355588436;
   fMax_1[0][0] = 12.2764291763;
   fMin_1[1][0] = 0.500997126102;
   fMax_1[1][0] = 10.1492881775;
   fMin_1[2][0] = 0.500997126102;
   fMax_1[2][0] = 12.2764291763;
   fMin_1[0][1] = 0.660297811031;
   fMax_1[0][1] = 17.9010639191;
   fMin_1[1][1] = 1.00966084003;
   fMax_1[1][1] = 18.7841835022;
   fMin_1[2][1] = 0.660297811031;
   fMax_1[2][1] = 18.7841835022;
   fMin_1[0][2] = 0.503957271576;
   fMax_1[0][2] = 17.1906490326;
   fMin_1[1][2] = 0.511234521866;
   fMax_1[1][2] = 18.0702095032;
   fMin_1[2][2] = 0.503957271576;
   fMax_1[2][2] = 18.0702095032;
   fMin_1[0][3] = 8.01337337494;
   fMax_1[0][3] = 19.785320282;
   fMin_1[1][3] = 8.23118686676;
   fMax_1[1][3] = 20.0275936127;
   fMin_1[2][3] = 8.01337337494;
   fMax_1[2][3] = 20.0275936127;
   fMin_1[0][4] = 0.0500634536147;
   fMax_1[0][4] = 0.998736560345;
   fMin_1[1][4] = 0.0509595423937;
   fMax_1[1][4] = 0.995793700218;
   fMin_1[2][4] = 0.0500634536147;
   fMax_1[2][4] = 0.998736560345;
   fMin_1[0][5] = 0.0503618642688;
   fMax_1[0][5] = 0.999740004539;
   fMin_1[1][5] = 0.0529076047242;
   fMax_1[1][5] = 0.98870319128;
   fMin_1[2][5] = 0.0503618642688;
   fMax_1[2][5] = 0.999740004539;
   fMin_1[0][6] = 9.7360854852e-05;
   fMax_1[0][6] = 0.199530050159;
   fMin_1[1][6] = 0.000548715470359;
   fMax_1[1][6] = 0.198484539986;
   fMin_1[2][6] = 9.7360854852e-05;
   fMax_1[2][6] = 0.199530050159;
   fMin_1[0][7] = 0.0012481494341;
   fMax_1[0][7] = 0.199770435691;
   fMin_1[1][7] = 0.00134446774609;
   fMax_1[1][7] = 0.175934433937;
   fMin_1[2][7] = 0.0012481494341;
   fMax_1[2][7] = 0.199770435691;
   fMin_1[0][8] = 2.00035476685;
   fMax_1[0][8] = 186.669784546;
   fMin_1[1][8] = 2.00457239151;
   fMax_1[1][8] = 182.887878418;
   fMin_1[2][8] = 2.00035476685;
   fMax_1[2][8] = 186.669784546;
   fMin_1[0][9] = 2.0597653389;
   fMax_1[0][9] = 96.4862823486;
   fMin_1[1][9] = 2.00586509705;
   fMax_1[1][9] = 46.9571380615;
   fMin_1[2][9] = 2.00586509705;
   fMax_1[2][9] = 96.4862823486;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 10;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<10;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
