// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/13       [393741]
Creator        : leure
Date           : Tue Jun  6 17:22:01 2017
Host           : Linux vocms029.cern.ch 2.6.32-504.12.2.el6.x86_64 #1 SMP Thu Mar 12 07:33:00 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /data/leure/TMVA_Luke/myTMVA
Training events: 8292
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                       Dtrk1Pt                                                         'F'    [0.504029989243,41.8308334351]
DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                    DRestrk1Pt                                                      'F'    [0.571486890316,47.9671859741]
DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                    DRestrk2Pt                                                      'F'    [0.501210987568,43.6604042053]
DtktkRespt                    DtktkRespt                    DtktkRespt                    DtktkRespt                                                      'F'    [8.00377178192,49.1006088257]
Dchi2cl                       Dchi2cl                       Dchi2cl                       Dchi2cl                                                         'F'    [0.0500181615353,0.999920845032]
DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl               DtktkRes_chi2cl                                                 'F'    [0.0501567982137,0.999939143658]
Dalpha                        Dalpha                        Dalpha                        Dalpha                                                          'F'    [3.9784146793e-05,0.199938639998]
DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                DtktkRes_alpha                                                  'F'    [0.000632901501376,0.199953570962]
DsvpvDistance/DsvpvDisErr     DsvpvDistance_D_DsvpvDisErr   DsvpvDistance/DsvpvDisErr     DsvpvDistance/DsvpvDisErr                                       'F'    [2.00123548508,633.239868164]
DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance_D_DtktkRes_svpvDisErr DtktkRes_svpvDistance/DtktkRes_svpvDisErr   DtktkRes_svpvDistance/DtktkRes_svpvDisErr                                                   'F'    [2.00574874878,248.740737915]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Dtrk1Pt", "DRestrk1Pt", "DRestrk2Pt", "DtktkRespt", "Dchi2cl", "DtktkRes_chi2cl", "Dalpha", "DtktkRes_alpha", "DsvpvDistance/DsvpvDisErr", "DtktkRes_svpvDistance/DtktkRes_svpvDisErr" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][10];
   double fMax_1[3][10];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[16][11];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][16];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 11; fWeights[0] = new double[11]; 
   fLayerSize[1] = 16; fWeights[1] = new double[16]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -2.63561790259906;
   fWeightMatrix0to1[1][0] = -102.867889870426;
   fWeightMatrix0to1[2][0] = -1.05095829435433;
   fWeightMatrix0to1[3][0] = 2.32784142066661;
   fWeightMatrix0to1[4][0] = -8.00718237483582;
   fWeightMatrix0to1[5][0] = 1.71626083823826;
   fWeightMatrix0to1[6][0] = -0.0306310020084312;
   fWeightMatrix0to1[7][0] = -0.842937796466812;
   fWeightMatrix0to1[8][0] = -1.81093028646261;
   fWeightMatrix0to1[9][0] = 4.79469835267228;
   fWeightMatrix0to1[10][0] = -2.28892475753723;
   fWeightMatrix0to1[11][0] = -3.42749137854431;
   fWeightMatrix0to1[12][0] = 1.8813631766956;
   fWeightMatrix0to1[13][0] = 2.85573780504938;
   fWeightMatrix0to1[14][0] = -2.95244847430473;
   fWeightMatrix0to1[0][1] = -1.54361070231576;
   fWeightMatrix0to1[1][1] = -104.810773714759;
   fWeightMatrix0to1[2][1] = 0.174297435156997;
   fWeightMatrix0to1[3][1] = 0.653067498232634;
   fWeightMatrix0to1[4][1] = -7.41438007209166;
   fWeightMatrix0to1[5][1] = 1.87757236254894;
   fWeightMatrix0to1[6][1] = -1.09851820652342;
   fWeightMatrix0to1[7][1] = -1.86554671131757;
   fWeightMatrix0to1[8][1] = -0.534233530421986;
   fWeightMatrix0to1[9][1] = 7.24161050288027;
   fWeightMatrix0to1[10][1] = -0.756029587460147;
   fWeightMatrix0to1[11][1] = -1.53090062718185;
   fWeightMatrix0to1[12][1] = 2.20355859936623;
   fWeightMatrix0to1[13][1] = 1.54194368888934;
   fWeightMatrix0to1[14][1] = -2.45419813850962;
   fWeightMatrix0to1[0][2] = -0.832353230547351;
   fWeightMatrix0to1[1][2] = -97.7957073111725;
   fWeightMatrix0to1[2][2] = -1.38923007363538;
   fWeightMatrix0to1[3][2] = 1.22552615766102;
   fWeightMatrix0to1[4][2] = -6.3287848190639;
   fWeightMatrix0to1[5][2] = 2.04785335653963;
   fWeightMatrix0to1[6][2] = -0.992572325205919;
   fWeightMatrix0to1[7][2] = 0.0058034143776835;
   fWeightMatrix0to1[8][2] = -1.7334542635219;
   fWeightMatrix0to1[9][2] = 7.226190692167;
   fWeightMatrix0to1[10][2] = 0.457288271556004;
   fWeightMatrix0to1[11][2] = -0.0202738479003066;
   fWeightMatrix0to1[12][2] = 3.29200659195713;
   fWeightMatrix0to1[13][2] = 2.37015455806943;
   fWeightMatrix0to1[14][2] = -2.94212053864604;
   fWeightMatrix0to1[0][3] = -3.07218533436709;
   fWeightMatrix0to1[1][3] = -97.7782763050908;
   fWeightMatrix0to1[2][3] = -0.0860645343764334;
   fWeightMatrix0to1[3][3] = 2.11236845961475;
   fWeightMatrix0to1[4][3] = -6.52955315844915;
   fWeightMatrix0to1[5][3] = 2.72009385704297;
   fWeightMatrix0to1[6][3] = 1.09539830131587;
   fWeightMatrix0to1[7][3] = -3.23692268869356;
   fWeightMatrix0to1[8][3] = 0.748131357487964;
   fWeightMatrix0to1[9][3] = 5.8294974430556;
   fWeightMatrix0to1[10][3] = -1.14094675722937;
   fWeightMatrix0to1[11][3] = -2.55305129720495;
   fWeightMatrix0to1[12][3] = -0.0644953371909156;
   fWeightMatrix0to1[13][3] = 3.10034409876312;
   fWeightMatrix0to1[14][3] = -1.34542585545761;
   fWeightMatrix0to1[0][4] = -0.207230169897652;
   fWeightMatrix0to1[1][4] = -141.164198963203;
   fWeightMatrix0to1[2][4] = 0.720712452188417;
   fWeightMatrix0to1[3][4] = 1.45631572916321;
   fWeightMatrix0to1[4][4] = 7.61109095877957;
   fWeightMatrix0to1[5][4] = -1.51393989955689;
   fWeightMatrix0to1[6][4] = -0.0135569730208228;
   fWeightMatrix0to1[7][4] = 0.276545742510463;
   fWeightMatrix0to1[8][4] = 0.197706714678098;
   fWeightMatrix0to1[9][4] = -5.79491365365354;
   fWeightMatrix0to1[10][4] = -0.465318947989967;
   fWeightMatrix0to1[11][4] = 1.69468329547688;
   fWeightMatrix0to1[12][4] = -2.53308891370184;
   fWeightMatrix0to1[13][4] = -1.79620835786249;
   fWeightMatrix0to1[14][4] = 1.86743323994545;
   fWeightMatrix0to1[0][5] = -1.72787303284607;
   fWeightMatrix0to1[1][5] = 10.4776087036227;
   fWeightMatrix0to1[2][5] = -2.34108731065764;
   fWeightMatrix0to1[3][5] = -1.14852686893715;
   fWeightMatrix0to1[4][5] = 6.46355344372884;
   fWeightMatrix0to1[5][5] = 0.0499912982670875;
   fWeightMatrix0to1[6][5] = -0.0052654776125404;
   fWeightMatrix0to1[7][5] = 1.30942370707529;
   fWeightMatrix0to1[8][5] = -0.530154957292808;
   fWeightMatrix0to1[9][5] = -7.01739856276323;
   fWeightMatrix0to1[10][5] = 0.462486096441425;
   fWeightMatrix0to1[11][5] = 0.634362193870153;
   fWeightMatrix0to1[12][5] = -0.33856421540888;
   fWeightMatrix0to1[13][5] = -0.570432970916979;
   fWeightMatrix0to1[14][5] = -0.23005761312899;
   fWeightMatrix0to1[0][6] = -1.86526934180101;
   fWeightMatrix0to1[1][6] = -105.919120245023;
   fWeightMatrix0to1[2][6] = -1.72456525408085;
   fWeightMatrix0to1[3][6] = 0.00689044313649743;
   fWeightMatrix0to1[4][6] = -7.96443196028851;
   fWeightMatrix0to1[5][6] = 0.418142341154905;
   fWeightMatrix0to1[6][6] = 0.0590099385170188;
   fWeightMatrix0to1[7][6] = 0.172027931394409;
   fWeightMatrix0to1[8][6] = -1.32521102684593;
   fWeightMatrix0to1[9][6] = 6.19256823495117;
   fWeightMatrix0to1[10][6] = -1.52469168054823;
   fWeightMatrix0to1[11][6] = 0.702164450952066;
   fWeightMatrix0to1[12][6] = -0.628770654666928;
   fWeightMatrix0to1[13][6] = -0.417804023578451;
   fWeightMatrix0to1[14][6] = -1.10688432548168;
   fWeightMatrix0to1[0][7] = 0.203777055870299;
   fWeightMatrix0to1[1][7] = 77.2484945414154;
   fWeightMatrix0to1[2][7] = -1.04879638126817;
   fWeightMatrix0to1[3][7] = 0.421106806353962;
   fWeightMatrix0to1[4][7] = -0.273884927925863;
   fWeightMatrix0to1[5][7] = 0.657665185158664;
   fWeightMatrix0to1[6][7] = 0.0130770999553244;
   fWeightMatrix0to1[7][7] = -1.47246138175152;
   fWeightMatrix0to1[8][7] = -0.097351918921351;
   fWeightMatrix0to1[9][7] = -0.766105995758433;
   fWeightMatrix0to1[10][7] = 0.99974455821476;
   fWeightMatrix0to1[11][7] = -1.516404904224;
   fWeightMatrix0to1[12][7] = 0.800043662855239;
   fWeightMatrix0to1[13][7] = 2.68954689403724;
   fWeightMatrix0to1[14][7] = -0.349438206951885;
   fWeightMatrix0to1[0][8] = -2.51309325854589;
   fWeightMatrix0to1[1][8] = -128.177295427976;
   fWeightMatrix0to1[2][8] = 0.0273772469798545;
   fWeightMatrix0to1[3][8] = 2.68600307412506;
   fWeightMatrix0to1[4][8] = -9.13960478462869;
   fWeightMatrix0to1[5][8] = 3.37993799339735;
   fWeightMatrix0to1[6][8] = -0.00232400925282658;
   fWeightMatrix0to1[7][8] = -3.74610488989578;
   fWeightMatrix0to1[8][8] = -1.9896526903463;
   fWeightMatrix0to1[9][8] = 10.4546042871719;
   fWeightMatrix0to1[10][8] = -1.25013116432272;
   fWeightMatrix0to1[11][8] = -5.46518851922261;
   fWeightMatrix0to1[12][8] = 4.07474094116991;
   fWeightMatrix0to1[13][8] = 2.75234257523612;
   fWeightMatrix0to1[14][8] = -3.82431397975038;
   fWeightMatrix0to1[0][9] = -1.91598632595117;
   fWeightMatrix0to1[1][9] = -106.205870994256;
   fWeightMatrix0to1[2][9] = -1.17271994601615;
   fWeightMatrix0to1[3][9] = 0.630224297552825;
   fWeightMatrix0to1[4][9] = -8.02272114458062;
   fWeightMatrix0to1[5][9] = 4.62844553832332;
   fWeightMatrix0to1[6][9] = -0.0683206907042166;
   fWeightMatrix0to1[7][9] = -4.87324626486536;
   fWeightMatrix0to1[8][9] = -0.843747238106486;
   fWeightMatrix0to1[9][9] = 7.74568075480059;
   fWeightMatrix0to1[10][9] = 0.207317283881859;
   fWeightMatrix0to1[11][9] = -2.43203484283711;
   fWeightMatrix0to1[12][9] = 2.86803705686809;
   fWeightMatrix0to1[13][9] = 3.73987135638307;
   fWeightMatrix0to1[14][9] = -3.9157215493068;
   fWeightMatrix0to1[0][10] = 1.79213038089794;
   fWeightMatrix0to1[1][10] = 147.185188901605;
   fWeightMatrix0to1[2][10] = 4.91228903603707;
   fWeightMatrix0to1[3][10] = -2.20842589166813;
   fWeightMatrix0to1[4][10] = 9.84031486740153;
   fWeightMatrix0to1[5][10] = -4.1440533110746;
   fWeightMatrix0to1[6][10] = 0.738389734617678;
   fWeightMatrix0to1[7][10] = 4.31583074039918;
   fWeightMatrix0to1[8][10] = 1.72664214396474;
   fWeightMatrix0to1[9][10] = -11.2621918926585;
   fWeightMatrix0to1[10][10] = 2.87678288581784;
   fWeightMatrix0to1[11][10] = 4.4549976814193;
   fWeightMatrix0to1[12][10] = -3.63487576979984;
   fWeightMatrix0to1[13][10] = -3.54904636261009;
   fWeightMatrix0to1[14][10] = 4.77381420394949;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 21.7152098012647;
   fWeightMatrix1to2[0][1] = 14.0685401627839;
   fWeightMatrix1to2[0][2] = 7.37473823168384;
   fWeightMatrix1to2[0][3] = 6.55426597853868;
   fWeightMatrix1to2[0][4] = 17.8331430554434;
   fWeightMatrix1to2[0][5] = 6.8740347833293;
   fWeightMatrix1to2[0][6] = -5.74808808021368;
   fWeightMatrix1to2[0][7] = -6.09763949793858;
   fWeightMatrix1to2[0][8] = -5.06243253783578;
   fWeightMatrix1to2[0][9] = -12.9827596122269;
   fWeightMatrix1to2[0][10] = -7.93604664523424;
   fWeightMatrix1to2[0][11] = -6.77032512258822;
   fWeightMatrix1to2[0][12] = 6.65712949212336;
   fWeightMatrix1to2[0][13] = 6.96709497705063;
   fWeightMatrix1to2[0][14] = -6.64771086033888;
   fWeightMatrix1to2[0][15] = -8.22488827325386;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.506181895733;
   fMax_1[0][0] = 41.8308334351;
   fMin_1[1][0] = 0.504029989243;
   fMax_1[1][0] = 33.694190979;
   fMin_1[2][0] = 0.504029989243;
   fMax_1[2][0] = 41.8308334351;
   fMin_1[0][1] = 0.571486890316;
   fMax_1[0][1] = 47.9671859741;
   fMin_1[1][1] = 0.626341223717;
   fMax_1[1][1] = 47.3239898682;
   fMin_1[2][1] = 0.571486890316;
   fMax_1[2][1] = 47.9671859741;
   fMin_1[0][2] = 0.501210987568;
   fMax_1[0][2] = 40.7651290894;
   fMin_1[1][2] = 0.51357614994;
   fMax_1[1][2] = 43.6604042053;
   fMin_1[2][2] = 0.501210987568;
   fMax_1[2][2] = 43.6604042053;
   fMin_1[0][3] = 8.00377178192;
   fMax_1[0][3] = 49.1006088257;
   fMin_1[1][3] = 8.22736644745;
   fMax_1[1][3] = 48.0580368042;
   fMin_1[2][3] = 8.00377178192;
   fMax_1[2][3] = 49.1006088257;
   fMin_1[0][4] = 0.0500181615353;
   fMax_1[0][4] = 0.999920845032;
   fMin_1[1][4] = 0.0507250055671;
   fMax_1[1][4] = 0.990152597427;
   fMin_1[2][4] = 0.0500181615353;
   fMax_1[2][4] = 0.999920845032;
   fMin_1[0][5] = 0.0501567982137;
   fMax_1[0][5] = 0.999939143658;
   fMin_1[1][5] = 0.0513061583042;
   fMax_1[1][5] = 0.992246687412;
   fMin_1[2][5] = 0.0501567982137;
   fMax_1[2][5] = 0.999939143658;
   fMin_1[0][6] = 3.9784146793e-05;
   fMax_1[0][6] = 0.199938639998;
   fMin_1[1][6] = 0.00345922051929;
   fMax_1[1][6] = 0.199936017394;
   fMin_1[2][6] = 3.9784146793e-05;
   fMax_1[2][6] = 0.199938639998;
   fMin_1[0][7] = 0.000632901501376;
   fMax_1[0][7] = 0.199953570962;
   fMin_1[1][7] = 0.000838859472424;
   fMax_1[1][7] = 0.19325864315;
   fMin_1[2][7] = 0.000632901501376;
   fMax_1[2][7] = 0.199953570962;
   fMin_1[0][8] = 2.0015206337;
   fMax_1[0][8] = 587.856567383;
   fMin_1[1][8] = 2.00123548508;
   fMax_1[1][8] = 633.239868164;
   fMin_1[2][8] = 2.00123548508;
   fMax_1[2][8] = 633.239868164;
   fMin_1[0][9] = 2.00574874878;
   fMax_1[0][9] = 248.740737915;
   fMin_1[1][9] = 2.01058912277;
   fMax_1[1][9] = 99.9331207275;
   fMin_1[2][9] = 2.00574874878;
   fMax_1[2][9] = 248.740737915;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 10;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<10;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
